from pathlib import Path
import json
from typing import List
from usa_signal_bot.release.release_models import ReleaseVersion, ReleaseManifest, ReleaseBuildResult
from usa_signal_bot.release.maintenance_models import MaintenanceRunResult
from usa_signal_bot.release.backup_restore import BackupResult, RestoreDryRunResult
from usa_signal_bot.release.config_profiles import ConfigProfileValidationResult
from usa_signal_bot.release.upgrade_precheck import UpgradePrecheckResult
from usa_signal_bot.release.release_validation import ReleaseValidationReport

def release_version_report_to_text(version: ReleaseVersion) -> str:
    return (
        f"Version: {version.version}\n"
        f"Build ID: {version.build_id}\n"
        f"Created At: {version.created_at_utc}\n"
    )

def release_manifest_report_to_text(manifest: ReleaseManifest) -> str:
    return (
        f"Manifest ID: {manifest.manifest_id}\n"
        f"Artifact Count: {manifest.artifact_count}\n"
        f"Total Size: {manifest.total_size_bytes} bytes\n"
    )

def release_build_result_to_text(result: ReleaseBuildResult) -> str:
    lines = [
        "=== Release Build Report ===",
        f"Build ID: {result.build_id}",
        f"Status: {result.status.value}",
        f"Validation: {result.validation_status.value}",
        f"Bundle Path: {result.bundle_path or 'None'}",
        "============================"
    ]
    if result.errors:
        lines.append("\nErrors:")
        for err in result.errors:
            lines.append(f" - {err}")
    return "\n".join(lines)

def maintenance_run_result_report_to_text(result: MaintenanceRunResult) -> str:
    return (
        f"Maintenance Run ID: {result.run_id}\n"
        f"Frequency: {result.frequency.value}\n"
        f"Status: {result.status.value}\n"
        f"Passed: {result.passed_count}, Failed: {result.failed_count}\n"
    )

def backup_result_report_to_text(result: BackupResult) -> str:
    return (
        f"Backup ID: {result.backup_id}\n"
        f"Status: {result.status.value}\n"
        f"Files: {result.file_count}, Size: {result.total_size_bytes}\n"
    )

def restore_dry_run_result_report_to_text(result: RestoreDryRunResult) -> str:
    return (
        f"Restore Dry Run ID: {result.restore_id}\n"
        f"Status: {result.status.value}\n"
        f"Checked: {result.files_checked}, Conflicts: {len(result.conflicts)}\n"
    )

def config_profile_validation_report_to_text(results: List[ConfigProfileValidationResult]) -> str:
    lines = ["Config Profile Validation Report"]
    for r in results:
        lines.append(f"- {r.name}: {r.status.value}")
    return "\n".join(lines)

def upgrade_precheck_report_to_text(result: UpgradePrecheckResult) -> str:
    lines = [f"Upgrade Precheck ID: {result.precheck_id}", f"Status: {result.status.value}"]
    for i in result.items:
        lines.append(f"  [{i.status.value}] {i.name}")
    return "\n".join(lines)

def release_store_summary_to_text(summary: dict) -> str:
    return f"Total Builds: {summary.get('total_builds', 0)}\nLatest Build Dir: {summary.get('latest_build_dir', 'None')}"

def release_limitations_text() -> str:
    return """
Release Limitations:
1. Local Package Only: This bundle is intended for local execution.
2. No Broker Execution: This package does not contain broker connection keys or logic to execute live trades.
3. Not Investment Advice: Outputs and signals generated by this software do not constitute financial advice.
4. Not a Live Approval: A successful release build does NOT imply readiness or approval for live trading.
5. No Executables: This bundle is raw source code and configs, not a compiled binary.
"""

def write_release_report_json(path: Path, result: ReleaseBuildResult, validation_report: ReleaseValidationReport = None) -> Path:
    from usa_signal_bot.release.release_models import release_build_result_to_dict
    data = {
        "build_result": release_build_result_to_dict(result),
        "limitations": release_limitations_text(),
    }
    if validation_report:
        from usa_signal_bot.release.release_validation import release_validation_report_to_text
        data["validation_report"] = release_validation_report_to_text(validation_report)

    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    return path
