import re

with open("usa_signal_bot/core/enums.py", "r") as f:
    content = f.read()

new_enums = """
class StrategyFamily(str, Enum):
    TREND_FOLLOWING = "TREND_FOLLOWING"
    MEAN_REVERSION = "MEAN_REVERSION"
    MOMENTUM = "MOMENTUM"
    BREAKOUT = "BREAKOUT"
    VOLATILITY_EXPANSION = "VOLATILITY_EXPANSION"
    VOLATILITY_COMPRESSION = "VOLATILITY_COMPRESSION"
    RANGE_TRADING = "RANGE_TRADING"
    DIVERGENCE = "DIVERGENCE"
    BREADTH_CONFIRMATION = "BREADTH_CONFIRMATION"
    RISK_OFF_DEFENSIVE = "RISK_OFF_DEFENSIVE"
    HYBRID = "HYBRID"
    UNKNOWN = "UNKNOWN"

class StrategyRegimeCompatibility(str, Enum):
    STRONGLY_COMPATIBLE = "STRONGLY_COMPATIBLE"
    COMPATIBLE = "COMPATIBLE"
    NEUTRAL = "NEUTRAL"
    WEAKLY_COMPATIBLE = "WEAKLY_COMPATIBLE"
    INCOMPATIBLE = "INCOMPATIBLE"
    BLOCKED = "BLOCKED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class StrategyGateDecision(str, Enum):
    ALLOW = "ALLOW"
    ALLOW_WITH_PENALTY = "ALLOW_WITH_PENALTY"
    REVIEW = "REVIEW"
    SUPPRESS = "SUPPRESS"
    BLOCK = "BLOCK"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class StrategyConflictType(str, Enum):
    LONG_SHORT_CONFLICT = "LONG_SHORT_CONFLICT"
    TREND_MEAN_REVERSION_CONFLICT = "TREND_MEAN_REVERSION_CONFLICT"
    MOMENTUM_DIVERGENCE_CONFLICT = "MOMENTUM_DIVERGENCE_CONFLICT"
    BREAKOUT_RANGE_CONFLICT = "BREAKOUT_RANGE_CONFLICT"
    RISK_ON_RISK_OFF_CONFLICT = "RISK_ON_RISK_OFF_CONFLICT"
    COST_REALISM_CONFLICT = "COST_REALISM_CONFLICT"
    REGIME_ALIGNMENT_CONFLICT = "REGIME_ALIGNMENT_CONFLICT"
    UNKNOWN = "UNKNOWN"

class StrategyEnsembleDecision(str, Enum):
    STRONG_CONSENSUS = "STRONG_CONSENSUS"
    CONSENSUS = "CONSENSUS"
    MIXED = "MIXED"
    WEAK_CONSENSUS = "WEAK_CONSENSUS"
    CONFLICTED = "CONFLICTED"
    NO_SIGNAL = "NO_SIGNAL"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class AdaptiveWeightStatus(str, Enum):
    BASELINE = "BASELINE"
    BOOSTED = "BOOSTED"
    PENALIZED = "PENALIZED"
    SUPPRESSED = "SUPPRESSED"
    BLOCKED = "BLOCKED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class StrategyAdaptationRisk(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class StrategyAdaptationReportType(str, Enum):
    STRATEGY_COMPATIBILITY = "STRATEGY_COMPATIBILITY"
    STRATEGY_GATING = "STRATEGY_GATING"
    ENSEMBLE_CONSENSUS = "ENSEMBLE_CONSENSUS"
    ADAPTIVE_WEIGHTING = "ADAPTIVE_WEIGHTING"
    FULL_STRATEGY_ADAPTATION_REVIEW = "FULL_STRATEGY_ADAPTATION_REVIEW"
"""

if "class StrategyFamily" not in content:
    content += "\n" + new_enums

# Add to NotificationType
if "STRATEGY_GATING_REPORT" not in content:
    content = content.replace(
        'class NotificationType(str, Enum):',
        'class NotificationType(str, Enum):\n    STRATEGY_GATING_REPORT = "STRATEGY_GATING_REPORT"\n    STRATEGY_CONFLICT_WARNING = "STRATEGY_CONFLICT_WARNING"\n    ADAPTIVE_ENSEMBLE_REPORT = "ADAPTIVE_ENSEMBLE_REPORT"'
    )

# Add to AlertType
if "STRATEGY_GATED_OFF" not in content:
    content = content.replace(
        'class AlertType(str, Enum):',
        'class AlertType(str, Enum):\n    STRATEGY_GATED_OFF = "STRATEGY_GATED_OFF"\n    STRATEGY_CONFLICT_DETECTED = "STRATEGY_CONFLICT_DETECTED"\n    ENSEMBLE_CONSENSUS_DEGRADED = "ENSEMBLE_CONSENSUS_DEGRADED"'
    )


with open("usa_signal_bot/core/enums.py", "w") as f:
    f.write(content)
