import re

with open('usa_signal_bot/app/cli.py', 'r') as f:
    content = f.read()

# Instead of click commands, argparse functions are used
content = content.replace("@cli.command(\"feature-enrichment-info\")\ndef", "def")
content = content.replace("@cli.command(\"feature-enrichment-ingest-advanced\")\ndef", "def")
content = content.replace("@cli.command(\"event-context-load\")\ndef", "def")
content = content.replace("@cli.command(\"quality-metadata-load\")\ndef", "def")
content = content.replace("@cli.command(\"calendar-metadata-load\")\ndef", "def")
content = content.replace("@cli.command(\"event-enrichment-specs\")\ndef", "def")
content = content.replace("@cli.command(\"quality-enrichment-specs\")\ndef", "def")
content = content.replace("@cli.command(\"calendar-enrichment-specs\")\ndef", "def")
content = content.replace("@cli.command(\"compute-event-aware-features\")\ndef", "def")
content = content.replace("@cli.command(\"compute-quality-aware-features\")\ndef", "def")
content = content.replace("@cli.command(\"compute-calendar-aware-features\")\ndef", "def")
content = content.replace("@cli.command(\"feature-freshness-profile\")\ndef", "def")
content = content.replace("@cli.command(\"feature-confidence-profile\")\ndef", "def")
content = content.replace("@cli.command(\"feature-anomaly-context\")\ndef", "def")
content = content.replace("@cli.command(\"feature-interaction-specs\")\ndef", "def")
content = content.replace("@cli.command(\"build-feature-interactions\")\ndef", "def")
content = content.replace("@cli.command(\"interaction-schema-check\")\ndef", "def")
content = content.replace("@cli.command(\"build-enriched-feature-table\")\ndef", "def")
content = content.replace("@cli.command(\"enriched-feature-computation-validate\")\ndef", "def")
content = content.replace("@cli.command(\"enriched-feature-output-safety-check\")\ndef", "def")
content = content.replace("@cli.command(\"feature-enrichment-context\")\ndef", "def")
content = content.replace("@cli.command(\"feature-enrichment-review\")\ndef", "def")
content = content.replace("@cli.command(\"feature-enrichment-summary\")\ndef", "def")
content = content.replace("@cli.command(\"feature-enrichment-validate\")\ndef", "def")

content = content.replace("@cli.command(\"factor-validation-info\")\ndef", "def")
content = content.replace("@cli.command(\"factor-validation-ingest-scoring\")\ndef", "def")
content = content.replace("@cli.command(\"factor-table-load\")\ndef", "def")
content = content.replace("@cli.command(\"factor-validation-rules\")\ndef", "def")
content = content.replace("@cli.command(\"run-factor-validation\")\ndef", "def")
content = content.replace("@cli.command(\"build-factor-drift-baseline\")\ndef", "def")
content = content.replace("@cli.command(\"factor-drift-metrics\")\ndef", "def")
content = content.replace("@cli.command(\"run-factor-drift-monitor\")\ndef", "def")
content = content.replace("@cli.command(\"factor-drift-report\")\ndef", "def")
content = content.replace("@cli.command(\"factor-schema-signature\")\ndef", "def")
content = content.replace("@cli.command(\"factor-version-metadata\")\ndef", "def")
content = content.replace("@cli.command(\"factor-artifact-manifest\")\ndef", "def")
content = content.replace("@cli.command(\"factor-store-snapshot\")\ndef", "def")
content = content.replace("@cli.command(\"factor-retention-policy\")\ndef", "def")
content = content.replace("@cli.command(\"factor-rollback-metadata\")\ndef", "def")
content = content.replace("@cli.command(\"factor-store-hardening\")\ndef", "def")
content = content.replace("@cli.command(\"factor-persistence-safety-check\")\ndef", "def")
content = content.replace("@cli.command(\"factor-validation-context\")\ndef", "def")
content = content.replace("@cli.command(\"factor-validation-review\")\ndef", "def")
content = content.replace("@cli.command(\"factor-validation-summary\")\ndef", "def")
content = content.replace("@cli.command(\"factor-validation-validate\")\ndef", "def")


with open('usa_signal_bot/app/cli.py', 'w') as f:
    f.write(content)
