cat << 'INNER_EOF' > patch_enums.py
import re

with open("usa_signal_bot/core/enums.py", "r") as f:
    content = f.read()

new_enums = """
class RegimeFeatureEngineeringStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    FOUNDATION_INGESTED = "FOUNDATION_INGESTED"
    INPUTS_LOADED = "INPUTS_LOADED"
    METRIC_SPECS_BUILT = "METRIC_SPECS_BUILT"
    FEATURE_SPECS_BUILT = "FEATURE_SPECS_BUILT"
    METRICS_COMPUTED = "METRICS_COMPUTED"
    FEATURE_TABLE_BUILT = "FEATURE_TABLE_BUILT"
    CANDIDATES_PREPARED = "CANDIDATES_PREPARED"
    READINESS_GATE_PASSED = "READINESS_GATE_PASSED"
    VALIDATED = "VALIDATED"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class RegimeFeatureEngineeringDecision(str, Enum):
    BUILD_REGIME_FEATURES = "BUILD_REGIME_FEATURES"
    BUILD_MARKET_STATE_METRICS = "BUILD_MARKET_STATE_METRICS"
    PREPARE_UNSUPERVISED_CANDIDATES = "PREPARE_UNSUPERVISED_CANDIDATES"
    BUILD_CANDIDATE_READINESS_GATE = "BUILD_CANDIDATE_READINESS_GATE"
    REQUEST_FOUNDATION_REFRESH = "REQUEST_FOUNDATION_REFRESH"
    REQUEST_INPUT_FIX = "REQUEST_INPUT_FIX"
    REQUEST_SCHEMA_FIX = "REQUEST_SCHEMA_FIX"
    REQUEST_CANDIDATE_FIX = "REQUEST_CANDIDATE_FIX"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class MarketStateMetricKind(str, Enum):
    MARKET_RETURN_CONTEXT = "MARKET_RETURN_CONTEXT"
    MARKET_VOLATILITY_CONTEXT = "MARKET_VOLATILITY_CONTEXT"
    MARKET_TREND_CONTEXT = "MARKET_TREND_CONTEXT"
    MARKET_MOMENTUM_CONTEXT = "MARKET_MOMENTUM_CONTEXT"
    MARKET_LIQUIDITY_CONTEXT = "MARKET_LIQUIDITY_CONTEXT"
    MARKET_BREADTH_CONTEXT = "MARKET_BREADTH_CONTEXT"
    CROSS_SECTIONAL_DISPERSION = "CROSS_SECTIONAL_DISPERSION"
    CROSS_SECTIONAL_CORRELATION_PROXY = "CROSS_SECTIONAL_CORRELATION_PROXY"
    FACTOR_STRENGTH_CONTEXT = "FACTOR_STRENGTH_CONTEXT"
    FACTOR_DISAGREEMENT_CONTEXT = "FACTOR_DISAGREEMENT_CONTEXT"
    DATA_QUALITY_CONTEXT = "DATA_QUALITY_CONTEXT"
    EVENT_PRESSURE_CONTEXT = "EVENT_PRESSURE_CONTEXT"
    CALENDAR_PRESSURE_CONTEXT = "CALENDAR_PRESSURE_CONTEXT"
    UNKNOWN = "UNKNOWN"

class RegimeFeatureKind(str, Enum):
    MARKET_STATE_FEATURE = "MARKET_STATE_FEATURE"
    ROLLING_CONTEXT_FEATURE = "ROLLING_CONTEXT_FEATURE"
    CROSS_SECTIONAL_CONTEXT_FEATURE = "CROSS_SECTIONAL_CONTEXT_FEATURE"
    FACTOR_CONTEXT_FEATURE = "FACTOR_CONTEXT_FEATURE"
    QUALITY_CONTEXT_FEATURE = "QUALITY_CONTEXT_FEATURE"
    EVENT_CONTEXT_FEATURE = "EVENT_CONTEXT_FEATURE"
    CALENDAR_CONTEXT_FEATURE = "CALENDAR_CONTEXT_FEATURE"
    CANDIDATE_PREP_FEATURE = "CANDIDATE_PREP_FEATURE"
    METADATA_FEATURE = "METADATA_FEATURE"
    UNKNOWN = "UNKNOWN"

class RegimeCandidateKind(str, Enum):
    RISK_ON_CANDIDATE = "RISK_ON_CANDIDATE"
    RISK_OFF_CANDIDATE = "RISK_OFF_CANDIDATE"
    HIGH_VOLATILITY_CANDIDATE = "HIGH_VOLATILITY_CANDIDATE"
    LOW_VOLATILITY_CANDIDATE = "LOW_VOLATILITY_CANDIDATE"
    TRENDING_UP_CANDIDATE = "TRENDING_UP_CANDIDATE"
    TRENDING_DOWN_CANDIDATE = "TRENDING_DOWN_CANDIDATE"
    RANGE_BOUND_CANDIDATE = "RANGE_BOUND_CANDIDATE"
    LIQUIDITY_STRESS_CANDIDATE = "LIQUIDITY_STRESS_CANDIDATE"
    EVENT_DISTORTED_CANDIDATE = "EVENT_DISTORTED_CANDIDATE"
    DATA_QUALITY_DEGRADED_CANDIDATE = "DATA_QUALITY_DEGRADED_CANDIDATE"
    MIXED_REGIME_CANDIDATE = "MIXED_REGIME_CANDIDATE"
    UNKNOWN_CANDIDATE = "UNKNOWN_CANDIDATE"
    UNKNOWN = "UNKNOWN"

class RegimeCandidatePreparationMethod(str, Enum):
    DETERMINISTIC_RULE_TEMPLATE = "DETERMINISTIC_RULE_TEMPLATE"
    QUANTILE_CONTEXT_TEMPLATE = "QUANTILE_CONTEXT_TEMPLATE"
    CENTROID_METADATA_TEMPLATE = "CENTROID_METADATA_TEMPLATE"
    DISTANCE_CONTEXT_TEMPLATE = "DISTANCE_CONTEXT_TEMPLATE"
    TAXONOMY_MAPPING_TEMPLATE = "TAXONOMY_MAPPING_TEMPLATE"
    UNKNOWN = "UNKNOWN"

class RegimeCandidateReadinessStatus(str, Enum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class RegimeCandidateReadinessRuleKind(str, Enum):
    FOUNDATION_VALID = "FOUNDATION_VALID"
    INPUT_BUNDLE_VALID = "INPUT_BUNDLE_VALID"
    MARKET_STATE_METRICS_AVAILABLE = "MARKET_STATE_METRICS_AVAILABLE"
    REGIME_FEATURE_TABLE_VALID = "REGIME_FEATURE_TABLE_VALID"
    TAXONOMY_ALIGNED = "TAXONOMY_ALIGNED"
    CANDIDATE_DEFINITIONS_VALID = "CANDIDATE_DEFINITIONS_VALID"
    CANDIDATE_SCORES_VALID = "CANDIDATE_SCORES_VALID"
    NO_SIGNAL_OUTPUT = "NO_SIGNAL_OUTPUT"
    NO_ORDER_OUTPUT = "NO_ORDER_OUTPUT"
    NO_PORTFOLIO_OUTPUT = "NO_PORTFOLIO_OUTPUT"
    NO_EXECUTION_OUTPUT = "NO_EXECUTION_OUTPUT"
    NO_MODEL_TRAINING = "NO_MODEL_TRAINING"
    UNKNOWN = "UNKNOWN"

class RegimeFeatureQuality(str, Enum):
    HIGH = "HIGH"
    ACCEPTABLE = "ACCEPTABLE"
    WARNING = "WARNING"
    LOW = "LOW"
    INVALID = "INVALID"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class RegimeFeatureEngineeringRiskFlag(str, Enum):
    REGIME_FOUNDATION_REVIEW_MISSING = "REGIME_FOUNDATION_REVIEW_MISSING"
    REGIME_FOUNDATION_REVIEW_INVALID = "REGIME_FOUNDATION_REVIEW_INVALID"
    FINAL_CLOSURE_NOT_READY = "FINAL_CLOSURE_NOT_READY"
    MARKET_STATE_CONTRACT_INVALID = "MARKET_STATE_CONTRACT_INVALID"
    REGIME_TAXONOMY_INVALID = "REGIME_TAXONOMY_INVALID"
    INPUT_BUNDLE_INVALID = "INPUT_BUNDLE_INVALID"
    FROZEN_FACTOR_TABLE_MISSING = "FROZEN_FACTOR_TABLE_MISSING"
    MARKET_STATE_METRIC_INVALID = "MARKET_STATE_METRIC_INVALID"
    REGIME_FEATURE_TABLE_INVALID = "REGIME_FEATURE_TABLE_INVALID"
    CANDIDATE_DEFINITION_INVALID = "CANDIDATE_DEFINITION_INVALID"
    CANDIDATE_SCORE_INVALID = "CANDIDATE_SCORE_INVALID"
    CANDIDATE_READINESS_GATE_FAILED = "CANDIDATE_READINESS_GATE_FAILED"
    MODEL_TRAINING_ATTEMPTED = "MODEL_TRAINING_ATTEMPTED"
    HEAVY_ML_DEPENDENCY_RISK = "HEAVY_ML_DEPENDENCY_RISK"
    FORBIDDEN_REGIME_FEATURE_COLUMN = "FORBIDDEN_REGIME_FEATURE_COLUMN"
    TRADE_SIGNAL_COLUMN_RISK = "TRADE_SIGNAL_COLUMN_RISK"
    ORDER_DECISION_COLUMN_RISK = "ORDER_DECISION_COLUMN_RISK"
    PORTFOLIO_WEIGHT_COLUMN_RISK = "PORTFOLIO_WEIGHT_COLUMN_RISK"
    BROKER_COLUMN_RISK = "BROKER_COLUMN_RISK"
    PAPER_MUTATION_COLUMN_RISK = "PAPER_MUTATION_COLUMN_RISK"
    DEPLOYMENT_RISK = "DEPLOYMENT_RISK"
    SECRET_LEAK_RISK = "SECRET_LEAK_RISK"
    INVESTMENT_ADVICE_LANGUAGE_RISK = "INVESTMENT_ADVICE_LANGUAGE_RISK"
    NETWORK_FETCH_ATTEMPTED = "NETWORK_FETCH_ATTEMPTED"
    NETWORK_DEFAULT_ENABLED_RISK = "NETWORK_DEFAULT_ENABLED_RISK"
    PAID_API_RISK = "PAID_API_RISK"
    SCRAPING_RISK = "SCRAPING_RISK"
    HTML_PARSE_RISK = "HTML_PARSE_RISK"
    BROKER_RISK = "BROKER_RISK"
    ORDER_RISK = "ORDER_RISK"
    PAPER_MUTATION_RISK = "PAPER_MUTATION_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    DASHBOARD_RISK = "DASHBOARD_RISK"
    UNKNOWN = "UNKNOWN"

class RegimeFeatureEngineeringReportType(str, Enum):
    MARKET_STATE_METRICS_REPORT = "MARKET_STATE_METRICS_REPORT"
    REGIME_FEATURE_TABLE_REPORT = "REGIME_FEATURE_TABLE_REPORT"
    UNSUPERVISED_CANDIDATE_PREPARATION_REPORT = "UNSUPERVISED_CANDIDATE_PREPARATION_REPORT"
    CANDIDATE_READINESS_GATE_REPORT = "CANDIDATE_READINESS_GATE_REPORT"
    FULL_PHASE127_REVIEW = "FULL_PHASE127_REVIEW"
"""
with open("usa_signal_bot/core/enums.py", "a") as f:
    f.write(new_enums)
INNER_EOF
python3 patch_enums.py

cat << 'INNER_EOF' > usa_signal_bot/regime_classification/feature_engineering/regime_feature_engineering_validation.py
from usa_signal_bot.regime_classification.feature_engineering.phase127_models import RegimeFeatureEngineeringContext

class MockRep:
    def __init__(self, v): self.valid = v
    errors = []

def validate_regime_feature_engineering_context_report(ctx):
    rep = MockRep(not ctx.activation_allowed)
    if not rep.valid:
        rep.errors.append("Invalid")
    return rep
INNER_EOF
