import re

with open('usa_signal_bot/core/enums.py', 'r') as f:
    content = f.read()

# Add new enums at the bottom
new_enums = """

class FeatureFoundationStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    REGISTRY_READY = "REGISTRY_READY"
    CONTRACT_READY = "CONTRACT_READY"
    SCHEMA_READY = "SCHEMA_READY"
    VALIDATED = "VALIDATED"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class FeatureFoundationDecision(str, Enum):
    BUILD_FEATURE_FOUNDATION = "BUILD_FEATURE_FOUNDATION"
    BUILD_INDICATOR_REGISTRY = "BUILD_INDICATOR_REGISTRY"
    BUILD_FEATURE_REGISTRY = "BUILD_FEATURE_REGISTRY"
    BUILD_FACTOR_REGISTRY = "BUILD_FACTOR_REGISTRY"
    CREATE_PHASE117_READY_GATE = "CREATE_PHASE117_READY_GATE"
    REQUEST_KICKOFF_REFRESH = "REQUEST_KICKOFF_REFRESH"
    REQUEST_CONTRACT_FIX = "REQUEST_CONTRACT_FIX"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class IndicatorCategory(str, Enum):
    PRICE = "PRICE"
    VOLUME = "VOLUME"
    VOLATILITY = "VOLATILITY"
    TREND = "TREND"
    MOMENTUM = "MOMENTUM"
    MEAN_REVERSION = "MEAN_REVERSION"
    BREADTH = "BREADTH"
    LIQUIDITY = "LIQUIDITY"
    EVENT_CONTEXT = "EVENT_CONTEXT"
    QUALITY_CONTEXT = "QUALITY_CONTEXT"
    CALENDAR_CONTEXT = "CALENDAR_CONTEXT"
    UNKNOWN = "UNKNOWN"

class FeatureCategory(str, Enum):
    RAW_OHLCV = "RAW_OHLCV"
    RETURN_FEATURE = "RETURN_FEATURE"
    ROLLING_WINDOW = "ROLLING_WINDOW"
    PRICE_ACTION = "PRICE_ACTION"
    VOLUME_FEATURE = "VOLUME_FEATURE"
    VOLATILITY_FEATURE = "VOLATILITY_FEATURE"
    TREND_FEATURE = "TREND_FEATURE"
    MOMENTUM_FEATURE = "MOMENTUM_FEATURE"
    NORMALIZATION_FEATURE = "NORMALIZATION_FEATURE"
    CROSS_SECTIONAL_FEATURE = "CROSS_SECTIONAL_FEATURE"
    EVENT_CONTEXT_FEATURE = "EVENT_CONTEXT_FEATURE"
    QUALITY_CONTEXT_FEATURE = "QUALITY_CONTEXT_FEATURE"
    CALENDAR_CONTEXT_FEATURE = "CALENDAR_CONTEXT_FEATURE"
    LINEAGE_FEATURE = "LINEAGE_FEATURE"
    UNKNOWN = "UNKNOWN"

class FactorCategory(str, Enum):
    VALUE = "VALUE"
    QUALITY = "QUALITY"
    MOMENTUM = "MOMENTUM"
    LOW_VOLATILITY = "LOW_VOLATILITY"
    SIZE = "SIZE"
    LIQUIDITY = "LIQUIDITY"
    TREND = "TREND"
    REVERSAL = "REVERSAL"
    EVENT_RISK_CONTEXT = "EVENT_RISK_CONTEXT"
    DATA_QUALITY_CONTEXT = "DATA_QUALITY_CONTEXT"
    UNKNOWN = "UNKNOWN"

class FeatureDataType(str, Enum):
    FLOAT = "FLOAT"
    INTEGER = "INTEGER"
    BOOLEAN = "BOOLEAN"
    STRING = "STRING"
    DATETIME = "DATETIME"
    CATEGORY = "CATEGORY"
    JSON = "JSON"
    UNKNOWN = "UNKNOWN"

class FeatureComputationMode(str, Enum):
    METADATA_ONLY = "METADATA_ONLY"
    LOCAL_FIXTURE_ONLY = "LOCAL_FIXTURE_ONLY"
    LOCAL_CACHE_ONLY = "LOCAL_CACHE_ONLY"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    PLANNED = "PLANNED"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class FeatureOutputKind(str, Enum):
    FEATURE_METADATA = "FEATURE_METADATA"
    FEATURE_SCHEMA = "FEATURE_SCHEMA"
    FEATURE_PLAN = "FEATURE_PLAN"
    FEATURE_VALUE_PLACEHOLDER = "FEATURE_VALUE_PLACEHOLDER"
    FACTOR_METADATA = "FACTOR_METADATA"
    LINEAGE_METADATA = "LINEAGE_METADATA"
    VALIDATION_REPORT = "VALIDATION_REPORT"
    UNKNOWN = "UNKNOWN"

class FeatureBlockedOutputKind(str, Enum):
    TRADE_SIGNAL = "TRADE_SIGNAL"
    ORDER_DECISION = "ORDER_DECISION"
    BROKER_INSTRUCTION = "BROKER_INSTRUCTION"
    PAPER_STATE_MUTATION = "PAPER_STATE_MUTATION"
    LIVE_ORDER = "LIVE_ORDER"
    DEMO_ORDER = "DEMO_ORDER"
    TELEGRAM_REAL_SEND = "TELEGRAM_REAL_SEND"
    DASHBOARD_PAYLOAD = "DASHBOARD_PAYLOAD"
    SCRAPED_HTML = "SCRAPED_HTML"
    PAID_API_PAYLOAD = "PAID_API_PAYLOAD"
    UNKNOWN = "UNKNOWN"

class FeatureFoundationRiskFlag(str, Enum):
    KICKOFF_GATE_MISSING = "KICKOFF_GATE_MISSING"
    KICKOFF_GATE_INVALID = "KICKOFF_GATE_INVALID"
    FEATURE_INPUT_CONTRACT_INVALID = "FEATURE_INPUT_CONTRACT_INVALID"
    FEATURE_SCHEMA_INVALID = "FEATURE_SCHEMA_INVALID"
    FEATURE_REGISTRY_INVALID = "FEATURE_REGISTRY_INVALID"
    FACTOR_REGISTRY_INVALID = "FACTOR_REGISTRY_INVALID"
    FEATURE_OUTPUT_CONTRACT_INVALID = "FEATURE_OUTPUT_CONTRACT_INVALID"
    FEATURE_COMPUTATION_UNSAFE = "FEATURE_COMPUTATION_UNSAFE"
    TRADE_SIGNAL_LANGUAGE_RISK = "TRADE_SIGNAL_LANGUAGE_RISK"
    INVESTMENT_ADVICE_LANGUAGE_RISK = "INVESTMENT_ADVICE_LANGUAGE_RISK"
    NETWORK_FETCH_ATTEMPTED = "NETWORK_FETCH_ATTEMPTED"
    NETWORK_DEFAULT_ENABLED_RISK = "NETWORK_DEFAULT_ENABLED_RISK"
    PAID_API_RISK = "PAID_API_RISK"
    SCRAPING_RISK = "SCRAPING_RISK"
    HTML_PARSE_RISK = "HTML_PARSE_RISK"
    BROKER_RISK = "BROKER_RISK"
    ORDER_RISK = "ORDER_RISK"
    PAPER_MUTATION_RISK = "PAPER_MUTATION_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    DASHBOARD_RISK = "DASHBOARD_RISK"
    SECRET_LEAK_RISK = "SECRET_LEAK_RISK"
    UNKNOWN = "UNKNOWN"

class FeatureFoundationReportType(str, Enum):
    FEATURE_FOUNDATION_REPORT = "FEATURE_FOUNDATION_REPORT"
    INDICATOR_REGISTRY_REPORT = "INDICATOR_REGISTRY_REPORT"
    FEATURE_REGISTRY_REPORT = "FEATURE_REGISTRY_REPORT"
    FACTOR_REGISTRY_REPORT = "FACTOR_REGISTRY_REPORT"
    FEATURE_INPUT_CONTRACT_REPORT = "FEATURE_INPUT_CONTRACT_REPORT"
    FULL_PHASE116_REVIEW = "FULL_PHASE116_REVIEW"
"""

content += new_enums

notification_additions = """    FEATURE_FOUNDATION_REPORT = "FEATURE_FOUNDATION_REPORT"
    FEATURE_CONTRACT_WARNING = "FEATURE_CONTRACT_WARNING"
    FEATURE_REGISTRY_WARNING = "FEATURE_REGISTRY_WARNING"
"""
content = re.sub(r'(class NotificationType\(str, Enum\):\n)', r'\1' + notification_additions, content)

alert_additions = """    FEATURE_FOUNDATION_BLOCKED = "FEATURE_FOUNDATION_BLOCKED"
    FEATURE_CONTRACT_BLOCKED = "FEATURE_CONTRACT_BLOCKED"
    FEATURE_REGISTRY_BLOCKED = "FEATURE_REGISTRY_BLOCKED"
"""
content = re.sub(r'(class AlertType\(str, Enum\):\n)', r'\1' + alert_additions, content)

with open('usa_signal_bot/core/enums.py', 'w') as f:
    f.write(content)
