import os

def write_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"Created {path}")

# --- Docs ---
write_file("docs/PORTFOLIO_CONSTRUCTION.md", """# Portfolio Construction

This module takes sized candidates from the `allocation` module and processes them into a unified portfolio plan.

## Purpose
- Manages portfolio-level limits (gross, net, long, short exposure).
- Enforces concentration guards (symbol, strategy, sector, cluster).
- Balances candidates based on configurable weighting modes (e.g., EQUAL_WEIGHT, SCORE_WEIGHTED, HYBRID).

## Local Proxy Warning
**This system is entirely local.** It does NOT generate broker orders and should NOT be considered investment advice. The output is strictly local metadata representing a theoretical allocation.

## Example CLI Commands
```bash
python -m usa_signal_bot portfolio-construction-info
python -m usa_signal_bot portfolio-plan --equity 100000 --write
```
""")

write_file("docs/EXPOSURE_BALANCING.md", """# Exposure Balancing

The Exposure Balancing layer calculates portfolio snapshots based on theoretical candidates or current allocations.

## Types of Exposure
- **Gross Exposure**: Absolute sum of all notional values.
- **Net Exposure**: Sum of long (+ve) and short (-ve) notionals.
- **Long/Short Exposure**: Absolute sums of specific sides.

Limits can be configured to `WARNING`, `REDUCE`, or `BLOCK` allocations that push the portfolio past defined bounds.

## Example CLI Commands
```bash
python -m usa_signal_bot exposure-snapshot --equity 100000
python -m usa_signal_bot exposure-limits --equity 100000
```
""")

write_file("docs/SECTOR_CLUSTER_RISK_CONTROL.md", """# Sector & Cluster Risk Control

This module provides heuristics for tracking sector and cluster exposure without relying on external paid APIs or scraping.

## Registry
A local registry (`config/portfolio/sector_cluster_registry.example.json`) can be maintained manually.
The system uses heuristics (like "SPY" -> "broad_market") for common index ETFs.

## Example CLI Commands
```bash
python -m usa_signal_bot sector-cluster-write-example
python -m usa_signal_bot sector-cluster-resolve --symbol AAPL
```
""")

write_file("docs/CORRELATION_PROXY_AND_CONCENTRATION.md", """# Correlation Proxy and Concentration

Since downloading full correlation matrices can be expensive or slow, we use a heuristic proxy based on shared metadata (sectors, clusters).

## Heuristics
- **Same Symbol**: VERY HIGH risk
- **Same Cluster**: HIGH risk
- **Same Sector**: MODERATE risk

Concentration guards evaluate exposures against configurable percentage thresholds (e.g., max 10% per symbol).

## Example CLI Commands
```bash
python -m usa_signal_bot correlation-proxy --symbols AAPL,MSFT,NVDA
python -m usa_signal_bot concentration-review --equity 100000
```
""")

write_file("docs/PORTFOLIO_CONSTRUCTION_LIMITATIONS.md", """# Portfolio Construction Limitations

**CRITICAL WARNINGS:**
1. This is a local metadata layer and NOT an official broker portfolio.
2. Sector/cluster mappings are local heuristics/proxies, not official classifications.
3. Correlation proxies are rough heuristics, not true statistical correlations.
4. This plan is NOT investment advice and makes no claims of future profitability.
5. 'APPROVED' or 'PASS' status is NOT an authorization for live trading.
6. No real or demo broker orders are generated by this system.
""")

write_file("docs/PHASE_61_SUMMARY.md", """# Phase 61 Summary

In Phase 61, the Portfolio Construction and Exposure Balancing layer was implemented.

## Key Additions
- **Portfolio Models**: Added dataclasses for Candidates, Allocations, Plans, and Reviews.
- **Sector/Cluster Registry**: Built local, manual JSONL/JSON-based proxy for categorizing symbols without external APIs.
- **Exposure Calculator**: Computes Gross, Net, Long, and Short exposures.
- **Concentration Guards**: Enforces limits on symbols, strategies, sectors, clusters, liquidity, and cost buckets.
- **Correlation Proxy**: A heuristic approach to estimating portfolio correlation risk.
- **Portfolio Balancer & Planner**: Implemented weighting (hybrid, equal, score) and conflict resolution.
- **Adapters**: Integrated portfolio metadata into Signals, Candidates, Paper Trading, Walk-Forward, and Backtest outputs.

## Principles Maintained
- No broker routing.
- No live orders.
- No paid sector APIs or web scraping.
- Output explicitly labeled as "NOT investment advice".
""")

# --- Add to main __init__.py ---
write_file("usa_signal_bot/portfolio_construction/__init__.py", """# Portfolio Construction Module
# Handles portfolio level allocation, risk sizing, and concentration guards locally.
""")

print("Generated step 12")
