import os

# ENUMS
enums_path = "usa_signal_bot/core/enums.py"
with open(enums_path, "r") as f:
    enums_content = f.read()

new_enums = """
class BacktestRunStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    BACKTEST_FOUNDATION_INGESTED = "BACKTEST_FOUNDATION_INGESTED"
    ARTIFACTS_LOADED = "ARTIFACTS_LOADED"
    INPUTS_RESOLVED = "INPUTS_RESOLVED"
    RUN_CONFIG_BUILT = "RUN_CONFIG_BUILT"
    RESEARCH_DECISION_STREAM_BUILT = "RESEARCH_DECISION_STREAM_BUILT"
    SIMULATION_CLOCK_BUILT = "SIMULATION_CLOCK_BUILT"
    PRICE_EVENT_STREAM_BUILT = "PRICE_EVENT_STREAM_BUILT"
    SIMULATED_EXECUTION_BUILT = "SIMULATED_EXECUTION_BUILT"
    COSTS_APPLIED = "COSTS_APPLIED"
    LIQUIDITY_PARTIAL_FILL_EVALUATED = "LIQUIDITY_PARTIAL_FILL_EVALUATED"
    EXPOSURE_TIMELINE_BUILT = "EXPOSURE_TIMELINE_BUILT"
    EQUITY_CURVE_BUILT = "EQUITY_CURVE_BUILT"
    DRAWDOWN_CURVE_BUILT = "DRAWDOWN_CURVE_BUILT"
    LEDGERS_BUILT = "LEDGERS_BUILT"
    BASIC_PERFORMANCE_BUILT = "BASIC_PERFORMANCE_BUILT"
    SAFETY_BOUNDARY_VALIDATED = "SAFETY_BOUNDARY_VALIDATED"
    VALIDATION_GATE_BUILT = "VALIDATION_GATE_BUILT"
    VALIDATION_GATE_PASSED = "VALIDATION_GATE_PASSED"
    VALIDATED = "VALIDATED"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class BacktestRunDecision(str, Enum):
    LOAD_FOUNDATION_ARTIFACTS = "LOAD_FOUNDATION_ARTIFACTS"
    RESOLVE_RUN_INPUTS = "RESOLVE_RUN_INPUTS"
    BUILD_RUN_CONFIG = "BUILD_RUN_CONFIG"
    BUILD_RESEARCH_DECISION_STREAM = "BUILD_RESEARCH_DECISION_STREAM"
    BUILD_SIMULATION_CLOCK = "BUILD_SIMULATION_CLOCK"
    BUILD_PRICE_EVENT_STREAM = "BUILD_PRICE_EVENT_STREAM"
    RUN_SIMULATED_EXECUTION = "RUN_SIMULATED_EXECUTION"
    APPLY_COSTS = "APPLY_COSTS"
    EVALUATE_LIQUIDITY_PARTIAL_FILLS = "EVALUATE_LIQUIDITY_PARTIAL_FILLS"
    BUILD_EXPOSURE_TIMELINE = "BUILD_EXPOSURE_TIMELINE"
    BUILD_EQUITY_CURVE = "BUILD_EQUITY_CURVE"
    BUILD_DRAWDOWN_CURVE = "BUILD_DRAWDOWN_CURVE"
    BUILD_LEDGERS = "BUILD_LEDGERS"
    BUILD_BASIC_PERFORMANCE = "BUILD_BASIC_PERFORMANCE"
    VALIDATE_SAFETY_BOUNDARY = "VALIDATE_SAFETY_BOUNDARY"
    BUILD_VALIDATION_GATE = "BUILD_VALIDATION_GATE"
    REQUEST_FOUNDATION_REFRESH = "REQUEST_FOUNDATION_REFRESH"
    REQUEST_INPUT_FIX = "REQUEST_INPUT_FIX"
    REQUEST_RUN_CONFIG_FIX = "REQUEST_RUN_CONFIG_FIX"
    REQUEST_LEDGER_FIX = "REQUEST_LEDGER_FIX"
    REQUEST_SAFETY_FIX = "REQUEST_SAFETY_FIX"
    REQUEST_SCHEMA_FIX = "REQUEST_SCHEMA_FIX"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class ResearchDecisionKind(str, Enum):
    NO_ACTION_METADATA = "NO_ACTION_METADATA"
    ENTER_EXPOSURE_METADATA = "ENTER_EXPOSURE_METADATA"
    EXIT_EXPOSURE_METADATA = "EXIT_EXPOSURE_METADATA"
    HOLD_EXPOSURE_METADATA = "HOLD_EXPOSURE_METADATA"
    REDUCE_EXPOSURE_METADATA = "REDUCE_EXPOSURE_METADATA"
    CONTRACT_ONLY = "CONTRACT_ONLY"
    UNKNOWN = "UNKNOWN"

class ResearchExposureSide(str, Enum):
    FLAT = "FLAT"
    LONG_ONLY_RESEARCH = "LONG_ONLY_RESEARCH"
    CASH_ONLY_RESEARCH = "CASH_ONLY_RESEARCH"
    UNKNOWN = "UNKNOWN"

class SimulationClockKind(str, Enum):
    DAILY_BAR_CLOCK = "DAILY_BAR_CLOCK"
    EOD_RESEARCH_CLOCK = "EOD_RESEARCH_CLOCK"
    NEXT_BAR_EXECUTION_CLOCK = "NEXT_BAR_EXECUTION_CLOCK"
    CONTRACT_ONLY = "CONTRACT_ONLY"
    UNKNOWN = "UNKNOWN"

class PriceEventKind(str, Enum):
    BAR_OPEN = "BAR_OPEN"
    BAR_HIGH = "BAR_HIGH"
    BAR_LOW = "BAR_LOW"
    BAR_CLOSE = "BAR_CLOSE"
    BAR_VOLUME = "BAR_VOLUME"
    ADJUSTED_CLOSE = "ADJUSTED_CLOSE"
    UNKNOWN = "UNKNOWN"

class SimulatedFillKind(str, Enum):
    FULL_SIMULATED_FILL = "FULL_SIMULATED_FILL"
    PARTIAL_SIMULATED_FILL = "PARTIAL_SIMULATED_FILL"
    NO_SIMULATED_FILL_LIQUIDITY_BLOCK = "NO_SIMULATED_FILL_LIQUIDITY_BLOCK"
    NO_SIMULATED_FILL_MISSING_PRICE = "NO_SIMULATED_FILL_MISSING_PRICE"
    NO_SIMULATED_FILL_CONTRACT_ONLY = "NO_SIMULATED_FILL_CONTRACT_ONLY"
    UNKNOWN = "UNKNOWN"

class CostApplicationKind(str, Enum):
    TRANSACTION_COST = "TRANSACTION_COST"
    COMMISSION = "COMMISSION"
    SPREAD_COST = "SPREAD_COST"
    SLIPPAGE_COST = "SLIPPAGE_COST"
    TOTAL_SIMULATED_COST = "TOTAL_SIMULATED_COST"
    UNKNOWN = "UNKNOWN"

class BacktestRunMetricKind(str, Enum):
    TOTAL_RETURN = "TOTAL_RETURN"
    ANNUALIZED_RETURN_APPROX = "ANNUALIZED_RETURN_APPROX"
    VOLATILITY_APPROX = "VOLATILITY_APPROX"
    MAX_DRAWDOWN = "MAX_DRAWDOWN"
    HIT_RATE_APPROX = "HIT_RATE_APPROX"
    AVERAGE_SIMULATED_GAIN = "AVERAGE_SIMULATED_GAIN"
    AVERAGE_SIMULATED_LOSS = "AVERAGE_SIMULATED_LOSS"
    SIMULATED_TURNOVER = "SIMULATED_TURNOVER"
    SIMULATED_COST_TOTAL = "SIMULATED_COST_TOTAL"
    SIMULATED_FILL_COUNT = "SIMULATED_FILL_COUNT"
    SIMULATED_NO_FILL_COUNT = "SIMULATED_NO_FILL_COUNT"
    UNKNOWN = "UNKNOWN"

class BacktestRunSafetyRuleKind(str, Enum):
    OFFLINE_BACKTEST_ONLY = "OFFLINE_BACKTEST_ONLY"
    DETERMINISTIC_RUN_ONLY = "DETERMINISTIC_RUN_ONLY"
    NO_LIVE_TRADING = "NO_LIVE_TRADING"
    NO_PAPER_TRADING = "NO_PAPER_TRADING"
    NO_BROKER_EXECUTION = "NO_BROKER_EXECUTION"
    NO_REAL_ORDER_CREATION = "NO_REAL_ORDER_CREATION"
    NO_PAPER_STATE_MUTATION = "NO_PAPER_STATE_MUTATION"
    NO_TELEGRAM_REAL_SEND = "NO_TELEGRAM_REAL_SEND"
    NO_STRATEGY_ACTIVATION = "NO_STRATEGY_ACTIVATION"
    NO_PORTFOLIO_OPTIMIZATION = "NO_PORTFOLIO_OPTIMIZATION"
    NO_DEPLOYMENT = "NO_DEPLOYMENT"
    NO_NETWORK = "NO_NETWORK"
    NO_DASHBOARD = "NO_DASHBOARD"
    NO_DAEMON = "NO_DAEMON"
    NO_SCHEDULER = "NO_SCHEDULER"
    NO_WALK_FORWARD_PHASE147 = "NO_WALK_FORWARD_PHASE147"
    NO_STRESS_TEST_PHASE147 = "NO_STRESS_TEST_PHASE147"
    NO_MONTE_CARLO_PHASE147 = "NO_MONTE_CARLO_PHASE147"
    NO_BENCHMARK_COMPARISON_PHASE147 = "NO_BENCHMARK_COMPARISON_PHASE147"
    UNKNOWN = "UNKNOWN"

class BacktestRunValidationStatus(str, Enum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class BacktestRunValidationRuleKind(str, Enum):
    FOUNDATION_VALID = "FOUNDATION_VALID"
    RUN_INPUTS_VALID = "RUN_INPUTS_VALID"
    RUN_CONFIG_VALID = "RUN_CONFIG_VALID"
    RESEARCH_DECISION_STREAM_VALID = "RESEARCH_DECISION_STREAM_VALID"
    SIMULATION_CLOCK_VALID = "SIMULATION_CLOCK_VALID"
    PRICE_EVENT_STREAM_VALID = "PRICE_EVENT_STREAM_VALID"
    SIMULATED_FILL_LEDGER_VALID = "SIMULATED_FILL_LEDGER_VALID"
    COST_LEDGER_VALID = "COST_LEDGER_VALID"
    EXPOSURE_TIMELINE_VALID = "EXPOSURE_TIMELINE_VALID"
    EQUITY_CURVE_VALID = "EQUITY_CURVE_VALID"
    DRAWDOWN_CURVE_VALID = "DRAWDOWN_CURVE_VALID"
    BASIC_PERFORMANCE_VALID = "BASIC_PERFORMANCE_VALID"
    SAFETY_BOUNDARY_VALID = "SAFETY_BOUNDARY_VALID"
    DETERMINISM_VALID = "DETERMINISM_VALID"
    NO_REAL_ORDER_OUTPUT = "NO_REAL_ORDER_OUTPUT"
    NO_PAPER_MUTATION = "NO_PAPER_MUTATION"
    NO_LIVE_TRADING = "NO_LIVE_TRADING"
    READY_FOR_PHASE148 = "READY_FOR_PHASE148"
    UNKNOWN = "UNKNOWN"

class BacktestRunQuality(str, Enum):
    HIGH = "HIGH"
    ACCEPTABLE = "ACCEPTABLE"
    WARNING = "WARNING"
    LOW = "LOW"
    INVALID = "INVALID"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class BacktestRunRiskFlag(str, Enum):
    BACKTEST_FOUNDATION_REVIEW_MISSING = "BACKTEST_FOUNDATION_REVIEW_MISSING"
    BACKTEST_FOUNDATION_REVIEW_INVALID = "BACKTEST_FOUNDATION_REVIEW_INVALID"
    PHASE146_NOT_READY = "PHASE146_NOT_READY"
    FOUNDATION_SAFETY_BOUNDARY_FAILED = "FOUNDATION_SAFETY_BOUNDARY_FAILED"
    RUN_INPUT_MISSING = "RUN_INPUT_MISSING"
    RUN_INPUT_INVALID = "RUN_INPUT_INVALID"
    RUN_CONFIG_INVALID = "RUN_CONFIG_INVALID"
    RESEARCH_DECISION_STREAM_INVALID = "RESEARCH_DECISION_STREAM_INVALID"
    SIMULATION_CLOCK_INVALID = "SIMULATION_CLOCK_INVALID"
    PRICE_EVENT_STREAM_INVALID = "PRICE_EVENT_STREAM_INVALID"
    SIMULATED_FILL_LEDGER_INVALID = "SIMULATED_FILL_LEDGER_INVALID"
    COST_LEDGER_INVALID = "COST_LEDGER_INVALID"
    EXPOSURE_TIMELINE_INVALID = "EXPOSURE_TIMELINE_INVALID"
    EQUITY_CURVE_INVALID = "EQUITY_CURVE_INVALID"
    DRAWDOWN_CURVE_INVALID = "DRAWDOWN_CURVE_INVALID"
    BASIC_PERFORMANCE_INVALID = "BASIC_PERFORMANCE_INVALID"
    DETERMINISM_FAILED = "DETERMINISM_FAILED"
    LOOKAHEAD_RISK = "LOOKAHEAD_RISK"
    SAME_BAR_EXECUTION_RISK = "SAME_BAR_EXECUTION_RISK"
    LIVE_TRADING_RISK = "LIVE_TRADING_RISK"
    PAPER_TRADING_RISK = "PAPER_TRADING_RISK"
    BROKER_RISK = "BROKER_RISK"
    REAL_ORDER_RISK = "REAL_ORDER_RISK"
    PAPER_MUTATION_RISK = "PAPER_MUTATION_RISK"
    STRATEGY_ACTIVATION_RISK = "STRATEGY_ACTIVATION_RISK"
    PORTFOLIO_OPTIMIZATION_RISK = "PORTFOLIO_OPTIMIZATION_RISK"
    DEPLOYMENT_RISK = "DEPLOYMENT_RISK"
    NETWORK_FETCH_ATTEMPTED = "NETWORK_FETCH_ATTEMPTED"
    PAID_API_RISK = "PAID_API_RISK"
    SCRAPING_RISK = "SCRAPING_RISK"
    HTML_PARSE_RISK = "HTML_PARSE_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    DASHBOARD_RISK = "DASHBOARD_RISK"
    DAEMON_RISK = "DAEMON_RISK"
    SCHEDULER_RISK = "SCHEDULER_RISK"
    WALK_FORWARD_ATTEMPTED = "WALK_FORWARD_ATTEMPTED"
    STRESS_TEST_ATTEMPTED = "STRESS_TEST_ATTEMPTED"
    MONTE_CARLO_ATTEMPTED = "MONTE_CARLO_ATTEMPTED"
    BENCHMARK_COMPARISON_ATTEMPTED = "BENCHMARK_COMPARISON_ATTEMPTED"
    SECRET_LEAK_RISK = "SECRET_LEAK_RISK"
    INVESTMENT_ADVICE_LANGUAGE_RISK = "INVESTMENT_ADVICE_LANGUAGE_RISK"
    FORBIDDEN_BACKTEST_RUN_COLUMN = "FORBIDDEN_BACKTEST_RUN_COLUMN"
    UNKNOWN = "UNKNOWN"

class BacktestRunReportType(str, Enum):
    BACKTEST_RUN_LEDGER_REPORT = "BACKTEST_RUN_LEDGER_REPORT"
    BASIC_PERFORMANCE_REPORT = "BASIC_PERFORMANCE_REPORT"
    BACKTEST_RUN_SAFETY_REPORT = "BACKTEST_RUN_SAFETY_REPORT"
    FULL_PHASE147_REVIEW = "FULL_PHASE147_REVIEW"
"""

if "BacktestRunStatus" not in enums_content:
    with open(enums_path, "a") as f:
        f.write("\n" + new_enums)

    import re
    # Add NotificationType and AlertType enum values
    with open(enums_path, "r") as f:
        enums_content = f.read()

    enums_content = re.sub(r'(class NotificationType\(str, Enum\):)', r'\1\n    BACKTEST_RUN_REPORT = "BACKTEST_RUN_REPORT"\n    BACKTEST_RUN_WARNING = "BACKTEST_RUN_WARNING"\n    BACKTEST_DETERMINISM_WARNING = "BACKTEST_DETERMINISM_WARNING"', enums_content)
    enums_content = re.sub(r'(class AlertType\(str, Enum\):)', r'\1\n    BACKTEST_RUN_BLOCKED = "BACKTEST_RUN_BLOCKED"\n    BACKTEST_DETERMINISM_BLOCKED = "BACKTEST_DETERMINISM_BLOCKED"\n    BACKTEST_RUN_SAFETY_BLOCKED = "BACKTEST_RUN_SAFETY_BLOCKED"', enums_content)

    with open(enums_path, "w") as f:
        f.write(enums_content)

print("Enums updated.")

# EXCEPTIONS
exceptions_path = "usa_signal_bot/core/exceptions.py"
new_exceptions = """
class BacktestRunError(USASignalBotError): pass
class BacktestFoundationIngestionError(BacktestRunError): pass
class BacktestRunInputResolverError(BacktestRunError): pass
class BacktestRunConfigError(BacktestRunError): pass
class ResearchDecisionStreamError(BacktestRunError): pass
class DeterministicSimulationClockError(BacktestRunError): pass
class PriceEventStreamError(BacktestRunError): pass
class ExecutionSimulatorError(BacktestRunError): pass
class CostSpreadSlippageApplierError(BacktestRunError): pass
class LiquidityPartialFillEvaluatorError(BacktestRunError): pass
class ExposureStateTrackerError(BacktestRunError): pass
class EquityCurveBuilderError(BacktestRunError): pass
class DrawdownCurveBuilderError(BacktestRunError): pass
class BacktestLedgerBuilderError(BacktestRunError): pass
class BasicPerformanceSummaryError(BacktestRunError): pass
class BacktestRunSafetyBoundaryError(BacktestRunError): pass
class BacktestRunValidationGateError(BacktestRunError): pass
class BacktestRunSchemaValidationError(BacktestRunError): pass
class BacktestRunSafetyValidationError(BacktestRunError): pass
class BacktestRunStoreError(BacktestRunError): pass
class BacktestRunValidationError(BacktestRunError): pass
class BacktestRunReportingError(BacktestRunError): pass
"""

with open(exceptions_path, "r") as f:
    exceptions_content = f.read()

if "BacktestRunError" not in exceptions_content:
    with open(exceptions_path, "a") as f:
        f.write("\n" + new_exceptions)
    print("Exceptions updated.")
