import re

with open("usa_signal_bot/core/enums.py", "r") as f:
    content = f.read()

new_enums = """
class PortfolioRiskReportingStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    OPTIMIZER_PROTOTYPE_INGESTED = "OPTIMIZER_PROTOTYPE_INGESTED"
    ARTIFACTS_LOADED = "ARTIFACTS_LOADED"
    INPUTS_RESOLVED = "INPUTS_RESOLVED"
    SANDBOX_EXPOSURE_GOVERNANCE_BUILT = "SANDBOX_EXPOSURE_GOVERNANCE_BUILT"
    PORTFOLIO_RISK_SUMMARY_BUILT = "PORTFOLIO_RISK_SUMMARY_BUILT"
    CONCENTRATION_RISK_REPORT_BUILT = "CONCENTRATION_RISK_REPORT_BUILT"
    DIVERSIFICATION_GOVERNANCE_REPORT_BUILT = "DIVERSIFICATION_GOVERNANCE_REPORT_BUILT"
    RISK_BUDGET_GOVERNANCE_REPORT_BUILT = "RISK_BUDGET_GOVERNANCE_REPORT_BUILT"
    TURNOVER_GOVERNANCE_REPORT_BUILT = "TURNOVER_GOVERNANCE_REPORT_BUILT"
    OPTIMIZER_OBJECTIVE_GOVERNANCE_REPORT_BUILT = "OPTIMIZER_OBJECTIVE_GOVERNANCE_REPORT_BUILT"
    CONSTRAINT_GOVERNANCE_REPORT_BUILT = "CONSTRAINT_GOVERNANCE_REPORT_BUILT"
    PORTFOLIO_LIMITATIONS_REPORT_BUILT = "PORTFOLIO_LIMITATIONS_REPORT_BUILT"
    PORTFOLIO_BAND_LINEAGE_BUILT = "PORTFOLIO_BAND_LINEAGE_BUILT"
    PORTFOLIO_BAND_COMPLIANCE_AUDIT_BUILT = "PORTFOLIO_BAND_COMPLIANCE_AUDIT_BUILT"
    PORTFOLIO_BAND_FINAL_REVIEW_BUILT = "PORTFOLIO_BAND_FINAL_REVIEW_BUILT"
    PORTFOLIO_BAND_CLOSURE_CERTIFICATE_BUILT = "PORTFOLIO_BAND_CLOSURE_CERTIFICATE_BUILT"
    PHASE158_HANDOFF_CONTRACT_BUILT = "PHASE158_HANDOFF_CONTRACT_BUILT"
    PHASE158_HANDOFF_PACKAGE_BUILT = "PHASE158_HANDOFF_PACKAGE_BUILT"
    SAFETY_BOUNDARY_VALIDATED = "SAFETY_BOUNDARY_VALIDATED"
    PHASE158_READINESS_GATE_BUILT = "PHASE158_READINESS_GATE_BUILT"
    PHASE158_READINESS_GATE_PASSED = "PHASE158_READINESS_GATE_PASSED"
    VALIDATED = "VALIDATED"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class PortfolioRiskReportingDecision(str, Enum):
    LOAD_OPTIMIZER_PROTOTYPE_ARTIFACTS = "LOAD_OPTIMIZER_PROTOTYPE_ARTIFACTS"
    RESOLVE_GOVERNANCE_INPUTS = "RESOLVE_GOVERNANCE_INPUTS"
    BUILD_SANDBOX_EXPOSURE_GOVERNANCE = "BUILD_SANDBOX_EXPOSURE_GOVERNANCE"
    BUILD_PORTFOLIO_RISK_SUMMARY = "BUILD_PORTFOLIO_RISK_SUMMARY"
    BUILD_CONCENTRATION_RISK_REPORT = "BUILD_CONCENTRATION_RISK_REPORT"
    BUILD_DIVERSIFICATION_GOVERNANCE_REPORT = "BUILD_DIVERSIFICATION_GOVERNANCE_REPORT"
    BUILD_RISK_BUDGET_GOVERNANCE_REPORT = "BUILD_RISK_BUDGET_GOVERNANCE_REPORT"
    BUILD_TURNOVER_GOVERNANCE_REPORT = "BUILD_TURNOVER_GOVERNANCE_REPORT"
    BUILD_OBJECTIVE_GOVERNANCE_REPORT = "BUILD_OBJECTIVE_GOVERNANCE_REPORT"
    BUILD_CONSTRAINT_GOVERNANCE_REPORT = "BUILD_CONSTRAINT_GOVERNANCE_REPORT"
    BUILD_PORTFOLIO_LIMITATIONS_REPORT = "BUILD_PORTFOLIO_LIMITATIONS_REPORT"
    BUILD_PORTFOLIO_BAND_LINEAGE = "BUILD_PORTFOLIO_BAND_LINEAGE"
    BUILD_PORTFOLIO_BAND_COMPLIANCE_AUDIT = "BUILD_PORTFOLIO_BAND_COMPLIANCE_AUDIT"
    BUILD_PORTFOLIO_BAND_FINAL_REVIEW = "BUILD_PORTFOLIO_BAND_FINAL_REVIEW"
    BUILD_PORTFOLIO_BAND_CLOSURE_CERTIFICATE = "BUILD_PORTFOLIO_BAND_CLOSURE_CERTIFICATE"
    BUILD_PHASE158_HANDOFF_CONTRACT = "BUILD_PHASE158_HANDOFF_CONTRACT"
    BUILD_PHASE158_HANDOFF_PACKAGE = "BUILD_PHASE158_HANDOFF_PACKAGE"
    VALIDATE_SAFETY_BOUNDARY = "VALIDATE_SAFETY_BOUNDARY"
    BUILD_PHASE158_READINESS_GATE = "BUILD_PHASE158_READINESS_GATE"
    REQUEST_OPTIMIZER_REFRESH = "REQUEST_OPTIMIZER_REFRESH"
    REQUEST_GOVERNANCE_FIX = "REQUEST_GOVERNANCE_FIX"
    REQUEST_REPORT_FIX = "REQUEST_REPORT_FIX"
    REQUEST_CLOSURE_FIX = "REQUEST_CLOSURE_FIX"
    REQUEST_HANDOFF_FIX = "REQUEST_HANDOFF_FIX"
    REQUEST_BOUNDARY_FIX = "REQUEST_BOUNDARY_FIX"
    REQUEST_SAFETY_FIX = "REQUEST_SAFETY_FIX"
    REQUEST_SCHEMA_FIX = "REQUEST_SCHEMA_FIX"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class PortfolioRiskInputKind(str, Enum):
    OPTIMIZER_PROTOTYPE_REVIEW = "OPTIMIZER_PROTOTYPE_REVIEW"
    OPTIMIZER_POLICY = "OPTIMIZER_POLICY"
    OBJECTIVE_COMPARISON_REPORT = "OBJECTIVE_COMPARISON_REPORT"
    OPTIMIZER_VALIDATION_REPORT = "OPTIMIZER_VALIDATION_REPORT"
    OPTIMIZER_SAFETY_BOUNDARY = "OPTIMIZER_SAFETY_BOUNDARY"
    OPTIMIZER_RESULTS = "OPTIMIZER_RESULTS"
    OBJECTIVE_SCORES = "OBJECTIVE_SCORES"
    OPTIMIZER_DIAGNOSTICS = "OPTIMIZER_DIAGNOSTICS"
    PHASE157_READINESS_GATE = "PHASE157_READINESS_GATE"
    UNKNOWN = "UNKNOWN"

class PortfolioRiskReportKind(str, Enum):
    SANDBOX_EXPOSURE_GOVERNANCE = "SANDBOX_EXPOSURE_GOVERNANCE"
    PORTFOLIO_RISK_SUMMARY = "PORTFOLIO_RISK_SUMMARY"
    CONCENTRATION_RISK = "CONCENTRATION_RISK"
    DIVERSIFICATION_GOVERNANCE = "DIVERSIFICATION_GOVERNANCE"
    RISK_BUDGET_GOVERNANCE = "RISK_BUDGET_GOVERNANCE"
    TURNOVER_GOVERNANCE = "TURNOVER_GOVERNANCE"
    OBJECTIVE_GOVERNANCE = "OBJECTIVE_GOVERNANCE"
    CONSTRAINT_GOVERNANCE = "CONSTRAINT_GOVERNANCE"
    LIMITATIONS = "LIMITATIONS"
    BAND_CLOSURE = "BAND_CLOSURE"
    UNKNOWN = "UNKNOWN"

class ExposureGovernanceKind(str, Enum):
    SANDBOX_WEIGHT_EXPOSURE = "SANDBOX_WEIGHT_EXPOSURE"
    GROUP_SANDBOX_EXPOSURE = "GROUP_SANDBOX_EXPOSURE"
    MAX_SANDBOX_EXPOSURE = "MAX_SANDBOX_EXPOSURE"
    TOP_N_SANDBOX_EXPOSURE = "TOP_N_SANDBOX_EXPOSURE"
    ZERO_WEIGHT_EXPOSURE = "ZERO_WEIGHT_EXPOSURE"
    METHOD_LEVEL_EXPOSURE = "METHOD_LEVEL_EXPOSURE"
    UNKNOWN = "UNKNOWN"

class PortfolioRiskMetricKind(str, Enum):
    EFFECTIVE_NAME_COUNT = "EFFECTIVE_NAME_COUNT"
    HERFINDAHL_INDEX = "HERFINDAHL_INDEX"
    TOP_N_CONCENTRATION = "TOP_N_CONCENTRATION"
    MAX_SANDBOX_WEIGHT = "MAX_SANDBOX_WEIGHT"
    GROUP_EXPOSURE = "GROUP_EXPOSURE"
    RISK_BUDGET_USAGE = "RISK_BUDGET_USAGE"
    TURNOVER_ESTIMATE = "TURNOVER_ESTIMATE"
    OBJECTIVE_SCORE = "OBJECTIVE_SCORE"
    CONSTRAINT_BREACH_COUNT = "CONSTRAINT_BREACH_COUNT"
    STABILITY_SCORE = "STABILITY_SCORE"
    UNKNOWN = "UNKNOWN"

class PortfolioBandPhase(str, Enum):
    PHASE153_FOUNDATION = "PHASE153_FOUNDATION"
    PHASE154_SIZING_PROTOTYPES = "PHASE154_SIZING_PROTOTYPES"
    PHASE155_ALLOCATION_SANDBOX = "PHASE155_ALLOCATION_SANDBOX"
    PHASE156_OPTIMIZER_SANDBOX = "PHASE156_OPTIMIZER_SANDBOX"
    PHASE157_RISK_REPORTING_CLOSURE = "PHASE157_RISK_REPORTING_CLOSURE"
    UNKNOWN = "UNKNOWN"

class PortfolioBandClosureStatus(str, Enum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class PortfolioRiskSafetyRuleKind(str, Enum):
    RISK_REPORTING_ONLY = "RISK_REPORTING_ONLY"
    READ_ONLY_OPTIMIZER_ARTIFACTS = "READ_ONLY_OPTIMIZER_ARTIFACTS"
    NO_ACTUAL_TARGET_WEIGHTS = "NO_ACTUAL_TARGET_WEIGHTS"
    NO_ACTUAL_PORTFOLIO_WEIGHTS = "NO_ACTUAL_PORTFOLIO_WEIGHTS"
    NO_ACTUAL_ALLOCATION = "NO_ACTUAL_ALLOCATION"
    NO_ACTUAL_POSITION_SIZE = "NO_ACTUAL_POSITION_SIZE"
    NO_ORDER_SIZE = "NO_ORDER_SIZE"
    NO_CAPITAL_DEPLOYMENT = "NO_CAPITAL_DEPLOYMENT"
    NO_ACTUAL_PORTFOLIO_OPTIMIZATION = "NO_ACTUAL_PORTFOLIO_OPTIMIZATION"
    NO_REBALANCING_EXECUTION = "NO_REBALANCING_EXECUTION"
    NO_LIVE_TRADING = "NO_LIVE_TRADING"
    NO_PAPER_TRADING = "NO_PAPER_TRADING"
    NO_BROKER_EXECUTION = "NO_BROKER_EXECUTION"
    NO_REAL_ORDER_CREATION = "NO_REAL_ORDER_CREATION"
    NO_PAPER_STATE_MUTATION = "NO_PAPER_STATE_MUTATION"
    NO_TELEGRAM_REAL_SEND = "NO_TELEGRAM_REAL_SEND"
    NO_STRATEGY_ACTIVATION = "NO_STRATEGY_ACTIVATION"
    NO_DEPLOYMENT = "NO_DEPLOYMENT"
    NO_NETWORK = "NO_NETWORK"
    NO_DASHBOARD = "NO_DASHBOARD"
    NO_DAEMON = "NO_DAEMON"
    NO_SCHEDULER = "NO_SCHEDULER"
    RESEARCH_DATA_ONLY = "RESEARCH_DATA_ONLY"
    UNKNOWN = "UNKNOWN"

class Phase158ReadinessStatus(str, Enum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class Phase158ReadinessRuleKind(str, Enum):
    OPTIMIZER_PROTOTYPE_VALID = "OPTIMIZER_PROTOTYPE_VALID"
    PORTFOLIO_RISK_INPUTS_VALID = "PORTFOLIO_RISK_INPUTS_VALID"
    EXPOSURE_GOVERNANCE_VALID = "EXPOSURE_GOVERNANCE_VALID"
    PORTFOLIO_RISK_SUMMARY_VALID = "PORTFOLIO_RISK_SUMMARY_VALID"
    CONCENTRATION_REPORT_VALID = "CONCENTRATION_REPORT_VALID"
    DIVERSIFICATION_REPORT_VALID = "DIVERSIFICATION_REPORT_VALID"
    RISK_BUDGET_REPORT_VALID = "RISK_BUDGET_REPORT_VALID"
    TURNOVER_REPORT_VALID = "TURNOVER_REPORT_VALID"
    OBJECTIVE_GOVERNANCE_VALID = "OBJECTIVE_GOVERNANCE_VALID"
    CONSTRAINT_GOVERNANCE_VALID = "CONSTRAINT_GOVERNANCE_VALID"
    LIMITATIONS_REPORT_VALID = "LIMITATIONS_REPORT_VALID"
    PORTFOLIO_BAND_LINEAGE_VALID = "PORTFOLIO_BAND_LINEAGE_VALID"
    PORTFOLIO_BAND_COMPLIANCE_AUDIT_VALID = "PORTFOLIO_BAND_COMPLIANCE_AUDIT_VALID"
    PORTFOLIO_BAND_CLOSURE_CERTIFICATE_VALID = "PORTFOLIO_BAND_CLOSURE_CERTIFICATE_VALID"
    PHASE158_HANDOFF_PACKAGE_VALID = "PHASE158_HANDOFF_PACKAGE_VALID"
    SAFETY_BOUNDARY_VALID = "SAFETY_BOUNDARY_VALID"
    NO_ACTUAL_TARGET_WEIGHT_OUTPUT = "NO_ACTUAL_TARGET_WEIGHT_OUTPUT"
    NO_ACTUAL_ALLOCATION_OUTPUT = "NO_ACTUAL_ALLOCATION_OUTPUT"
    NO_REAL_ORDER_OUTPUT = "NO_REAL_ORDER_OUTPUT"
    NO_PAPER_MUTATION = "NO_PAPER_MUTATION"
    NO_LIVE_TRADING = "NO_LIVE_TRADING"
    READY_FOR_PHASE158 = "READY_FOR_PHASE158"
    UNKNOWN = "UNKNOWN"

class PortfolioRiskReportingQuality(str, Enum):
    HIGH = "HIGH"
    ACCEPTABLE = "ACCEPTABLE"
    WARNING = "WARNING"
    LOW = "LOW"
    INVALID = "INVALID"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class PortfolioRiskReportingRiskFlag(str, Enum):
    OPTIMIZER_PROTOTYPE_REVIEW_MISSING = "OPTIMIZER_PROTOTYPE_REVIEW_MISSING"
    OPTIMIZER_PROTOTYPE_REVIEW_INVALID = "OPTIMIZER_PROTOTYPE_REVIEW_INVALID"
    PHASE157_NOT_READY = "PHASE157_NOT_READY"
    OPTIMIZER_SAFETY_BOUNDARY_FAILED = "OPTIMIZER_SAFETY_BOUNDARY_FAILED"
    GOVERNANCE_INPUT_MISSING = "GOVERNANCE_INPUT_MISSING"
    GOVERNANCE_INPUT_INVALID = "GOVERNANCE_INPUT_INVALID"
    EXPOSURE_GOVERNANCE_INVALID = "EXPOSURE_GOVERNANCE_INVALID"
    PORTFOLIO_RISK_SUMMARY_INVALID = "PORTFOLIO_RISK_SUMMARY_INVALID"
    CONCENTRATION_REPORT_INVALID = "CONCENTRATION_REPORT_INVALID"
    DIVERSIFICATION_REPORT_INVALID = "DIVERSIFICATION_REPORT_INVALID"
    RISK_BUDGET_REPORT_INVALID = "RISK_BUDGET_REPORT_INVALID"
    TURNOVER_REPORT_INVALID = "TURNOVER_REPORT_INVALID"
    OBJECTIVE_GOVERNANCE_INVALID = "OBJECTIVE_GOVERNANCE_INVALID"
    CONSTRAINT_GOVERNANCE_INVALID = "CONSTRAINT_GOVERNANCE_INVALID"
    LIMITATIONS_REPORT_INVALID = "LIMITATIONS_REPORT_INVALID"
    PORTFOLIO_BAND_LINEAGE_INVALID = "PORTFOLIO_BAND_LINEAGE_INVALID"
    PORTFOLIO_BAND_COMPLIANCE_AUDIT_INVALID = "PORTFOLIO_BAND_COMPLIANCE_AUDIT_INVALID"
    PORTFOLIO_BAND_FINAL_REVIEW_INVALID = "PORTFOLIO_BAND_FINAL_REVIEW_INVALID"
    PORTFOLIO_BAND_CLOSURE_CERTIFICATE_INVALID = "PORTFOLIO_BAND_CLOSURE_CERTIFICATE_INVALID"
    PHASE158_HANDOFF_CONTRACT_INVALID = "PHASE158_HANDOFF_CONTRACT_INVALID"
    PHASE158_HANDOFF_PACKAGE_INVALID = "PHASE158_HANDOFF_PACKAGE_INVALID"
    SAFETY_BOUNDARY_FAILED = "SAFETY_BOUNDARY_FAILED"
    LIVE_TRADING_RISK = "LIVE_TRADING_RISK"
    PAPER_TRADING_RISK = "PAPER_TRADING_RISK"
    BROKER_RISK = "BROKER_RISK"
    REAL_ORDER_RISK = "REAL_ORDER_RISK"
    PAPER_MUTATION_RISK = "PAPER_MUTATION_RISK"
    STRATEGY_ACTIVATION_RISK = "STRATEGY_ACTIVATION_RISK"
    ACTUAL_TARGET_WEIGHT_RISK = "ACTUAL_TARGET_WEIGHT_RISK"
    ACTUAL_PORTFOLIO_WEIGHT_RISK = "ACTUAL_PORTFOLIO_WEIGHT_RISK"
    ACTUAL_ALLOCATION_RISK = "ACTUAL_ALLOCATION_RISK"
    ACTUAL_POSITION_SIZE_RISK = "ACTUAL_POSITION_SIZE_RISK"
    ORDER_SIZE_RISK = "ORDER_SIZE_RISK"
    CAPITAL_DEPLOYMENT_RISK = "CAPITAL_DEPLOYMENT_RISK"
    ACTUAL_PORTFOLIO_OPTIMIZATION_RISK = "ACTUAL_PORTFOLIO_OPTIMIZATION_RISK"
    REBALANCING_EXECUTION_RISK = "REBALANCING_EXECUTION_RISK"
    DEPLOYMENT_RISK = "DEPLOYMENT_RISK"
    NETWORK_FETCH_ATTEMPTED = "NETWORK_FETCH_ATTEMPTED"
    PAID_API_RISK = "PAID_API_RISK"
    SCRAPING_RISK = "SCRAPING_RISK"
    HTML_PARSE_RISK = "HTML_PARSE_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    DASHBOARD_RISK = "DASHBOARD_RISK"
    DAEMON_RISK = "DAEMON_RISK"
    SCHEDULER_RISK = "SCHEDULER_RISK"
    SECRET_LEAK_RISK = "SECRET_LEAK_RISK"
    INVESTMENT_ADVICE_LANGUAGE_RISK = "INVESTMENT_ADVICE_LANGUAGE_RISK"
    FORBIDDEN_PORTFOLIO_RISK_COLUMN = "FORBIDDEN_PORTFOLIO_RISK_COLUMN"
    UNKNOWN = "UNKNOWN"

class PortfolioRiskReportType(str, Enum):
    PORTFOLIO_RISK_SUMMARY_REPORT = "PORTFOLIO_RISK_SUMMARY_REPORT"
    EXPOSURE_GOVERNANCE_REPORT = "EXPOSURE_GOVERNANCE_REPORT"
    PORTFOLIO_BAND_CLOSURE_REPORT = "PORTFOLIO_BAND_CLOSURE_REPORT"
    PHASE158_HANDOFF_REPORT = "PHASE158_HANDOFF_REPORT"
    FULL_PHASE157_REVIEW = "FULL_PHASE157_REVIEW"

"""

# Add values to existing NotificationType and AlertType enum
notification_type_additions = [
    'PORTFOLIO_RISK_REPORT = "PORTFOLIO_RISK_REPORT"',
    'PORTFOLIO_RISK_WARNING = "PORTFOLIO_RISK_WARNING"',
    'PORTFOLIO_BAND_CLOSURE_WARNING = "PORTFOLIO_BAND_CLOSURE_WARNING"'
]

alert_type_additions = [
    'PORTFOLIO_RISK_REPORT_BLOCKED = "PORTFOLIO_RISK_REPORT_BLOCKED"',
    'PORTFOLIO_RISK_SAFETY_BOUNDARY_BLOCKED = "PORTFOLIO_RISK_SAFETY_BOUNDARY_BLOCKED"',
    'PORTFOLIO_BAND_CLOSURE_BLOCKED = "PORTFOLIO_BAND_CLOSURE_BLOCKED"'
]

def add_to_enum(content, enum_name, additions):
    lines = content.split('\n')
    for i, line in enumerate(lines):
        if line.startswith(f'class {enum_name}('):
            j = i + 1
            while j < len(lines) and (lines[j].strip() == '' or lines[j].startswith('    ')):
                j += 1
            for add in reversed(additions):
                lines.insert(j, f'    {add}')
            break
    return '\n'.join(lines)

content = add_to_enum(content, "NotificationType", notification_type_additions)
content = add_to_enum(content, "AlertType", alert_type_additions)

with open("usa_signal_bot/core/enums.py", "w") as f:
    f.write(content + "\n" + new_enums)
