import re

with open("usa_signal_bot/core/enums.py", "r") as f:
    content = f.read()

new_enums = """
class RegimeLabelingStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    FEATURE_ENGINEERING_INGESTED = "FEATURE_ENGINEERING_INGESTED"
    INPUTS_LOADED = "INPUTS_LOADED"
    LABELING_SPECS_BUILT = "LABELING_SPECS_BUILT"
    HEURISTIC_LABELS_BUILT = "HEURISTIC_LABELS_BUILT"
    ROLLING_WINDOWS_BUILT = "ROLLING_WINDOWS_BUILT"
    CANDIDATES_VALIDATED = "CANDIDATES_VALIDATED"
    LABEL_STABILITY_PROFILED = "LABEL_STABILITY_PROFILED"
    READINESS_GATE_PASSED = "READINESS_GATE_PASSED"
    VALIDATED = "VALIDATED"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class RegimeLabelingDecision(str, Enum):
    BUILD_HEURISTIC_LABELS = "BUILD_HEURISTIC_LABELS"
    BUILD_ROLLING_REGIME_WINDOWS = "BUILD_ROLLING_REGIME_WINDOWS"
    VALIDATE_REGIME_CANDIDATES = "VALIDATE_REGIME_CANDIDATES"
    BUILD_LABEL_STABILITY = "BUILD_LABEL_STABILITY"
    BUILD_LABELING_READINESS_GATE = "BUILD_LABELING_READINESS_GATE"
    REQUEST_FEATURE_ENGINEERING_REFRESH = "REQUEST_FEATURE_ENGINEERING_REFRESH"
    REQUEST_INPUT_FIX = "REQUEST_INPUT_FIX"
    REQUEST_SCHEMA_FIX = "REQUEST_SCHEMA_FIX"
    REQUEST_LABELING_RULE_FIX = "REQUEST_LABELING_RULE_FIX"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class RegimeLabelingMethod(str, Enum):
    DETERMINISTIC_TOP_CANDIDATE = "DETERMINISTIC_TOP_CANDIDATE"
    DETERMINISTIC_THRESHOLD_RULES = "DETERMINISTIC_THRESHOLD_RULES"
    HEURISTIC_SCORE_PRIORITY = "HEURISTIC_SCORE_PRIORITY"
    HEURISTIC_CONFLICT_RESOLUTION = "HEURISTIC_CONFLICT_RESOLUTION"
    ROLLING_WINDOW_MAJORITY = "ROLLING_WINDOW_MAJORITY"
    ROLLING_WINDOW_WEIGHTED = "ROLLING_WINDOW_WEIGHTED"
    FALLBACK_UNKNOWN = "FALLBACK_UNKNOWN"
    FALLBACK_MIXED = "FALLBACK_MIXED"
    UNKNOWN = "UNKNOWN"

class RegimeWindowKind(str, Enum):
    SHORT_TERM = "SHORT_TERM"
    MEDIUM_TERM = "MEDIUM_TERM"
    LONG_TERM = "LONG_TERM"
    CUSTOM = "CUSTOM"
    UNKNOWN = "UNKNOWN"

class RegimeLabelConfidenceKind(str, Enum):
    SCORE_GAP_CONFIDENCE = "SCORE_GAP_CONFIDENCE"
    SCORE_LEVEL_CONFIDENCE = "SCORE_LEVEL_CONFIDENCE"
    CANDIDATE_AGREEMENT_CONFIDENCE = "CANDIDATE_AGREEMENT_CONFIDENCE"
    ROLLING_PERSISTENCE_CONFIDENCE = "ROLLING_PERSISTENCE_CONFIDENCE"
    DATA_QUALITY_CONFIDENCE = "DATA_QUALITY_CONFIDENCE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    UNKNOWN = "UNKNOWN"

class RegimeLabelConflictKind(str, Enum):
    MULTIPLE_HIGH_SCORE_CANDIDATES = "MULTIPLE_HIGH_SCORE_CANDIDATES"
    LOW_SCORE_ALL_CANDIDATES = "LOW_SCORE_ALL_CANDIDATES"
    TAXONOMY_MISMATCH = "TAXONOMY_MISMATCH"
    DATA_QUALITY_DEGRADED = "DATA_QUALITY_DEGRADED"
    EVENT_DISTORTED_CONTEXT = "EVENT_DISTORTED_CONTEXT"
    WINDOW_DISAGREEMENT = "WINDOW_DISAGREEMENT"
    UNKNOWN = "UNKNOWN"

class RegimeCandidateValidationStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class RegimeCandidateValidationRuleKind(str, Enum):
    CANDIDATE_DEFINITIONS_AVAILABLE = "CANDIDATE_DEFINITIONS_AVAILABLE"
    CANDIDATE_SCORES_AVAILABLE = "CANDIDATE_SCORES_AVAILABLE"
    SCORES_WITHIN_RANGE = "SCORES_WITHIN_RANGE"
    NORMALIZED_SCORES_WITHIN_RANGE = "NORMALIZED_SCORES_WITHIN_RANGE"
    TAXONOMY_LABELS_ALIGNED = "TAXONOMY_LABELS_ALIGNED"
    NO_MODEL_PREDICTION = "NO_MODEL_PREDICTION"
    NO_MODEL_TRAINING = "NO_MODEL_TRAINING"
    NO_SIGNAL_OUTPUT = "NO_SIGNAL_OUTPUT"
    NO_ORDER_OUTPUT = "NO_ORDER_OUTPUT"
    NO_PORTFOLIO_OUTPUT = "NO_PORTFOLIO_OUTPUT"
    NO_EXECUTION_OUTPUT = "NO_EXECUTION_OUTPUT"
    SAFE_LABEL_NAMES = "SAFE_LABEL_NAMES"
    UNKNOWN = "UNKNOWN"

class RegimeLabelingReadinessStatus(str, Enum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class RegimeLabelingReadinessRuleKind(str, Enum):
    FEATURE_ENGINEERING_VALID = "FEATURE_ENGINEERING_VALID"
    INPUT_TABLES_AVAILABLE = "INPUT_TABLES_AVAILABLE"
    LABELING_SPECS_VALID = "LABELING_SPECS_VALID"
    HEURISTIC_LABELS_VALID = "HEURISTIC_LABELS_VALID"
    ROLLING_WINDOWS_VALID = "ROLLING_WINDOWS_VALID"
    CANDIDATE_VALIDATION_PASSED = "CANDIDATE_VALIDATION_PASSED"
    LABEL_STABILITY_ACCEPTABLE = "LABEL_STABILITY_ACCEPTABLE"
    NO_SIGNAL_OUTPUT = "NO_SIGNAL_OUTPUT"
    NO_ORDER_OUTPUT = "NO_ORDER_OUTPUT"
    NO_PORTFOLIO_OUTPUT = "NO_PORTFOLIO_OUTPUT"
    NO_EXECUTION_OUTPUT = "NO_EXECUTION_OUTPUT"
    NO_MODEL_TRAINING = "NO_MODEL_TRAINING"
    READY_FOR_PHASE129 = "READY_FOR_PHASE129"
    UNKNOWN = "UNKNOWN"

class RegimeLabelingQuality(str, Enum):
    HIGH = "HIGH"
    ACCEPTABLE = "ACCEPTABLE"
    WARNING = "WARNING"
    LOW = "LOW"
    INVALID = "INVALID"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class RegimeLabelingRiskFlag(str, Enum):
    REGIME_FEATURE_ENGINEERING_REVIEW_MISSING = "REGIME_FEATURE_ENGINEERING_REVIEW_MISSING"
    REGIME_FEATURE_ENGINEERING_REVIEW_INVALID = "REGIME_FEATURE_ENGINEERING_REVIEW_INVALID"
    PHASE127_NOT_READY = "PHASE127_NOT_READY"
    FEATURE_TABLE_MISSING = "FEATURE_TABLE_MISSING"
    CANDIDATE_SCORES_MISSING = "CANDIDATE_SCORES_MISSING"
    CANDIDATE_DEFINITIONS_INVALID = "CANDIDATE_DEFINITIONS_INVALID"
    CANDIDATE_READINESS_GATE_FAILED = "CANDIDATE_READINESS_GATE_FAILED"
    LABELING_SPEC_INVALID = "LABELING_SPEC_INVALID"
    HEURISTIC_LABEL_INVALID = "HEURISTIC_LABEL_INVALID"
    ROLLING_WINDOW_INVALID = "ROLLING_WINDOW_INVALID"
    CANDIDATE_VALIDATION_FAILED = "CANDIDATE_VALIDATION_FAILED"
    LABEL_STABILITY_LOW = "LABEL_STABILITY_LOW"
    LABEL_CONFLICT_HIGH = "LABEL_CONFLICT_HIGH"
    MODEL_TRAINING_ATTEMPTED = "MODEL_TRAINING_ATTEMPTED"
    MODEL_PREDICTION_RISK = "MODEL_PREDICTION_RISK"
    HEAVY_ML_DEPENDENCY_RISK = "HEAVY_ML_DEPENDENCY_RISK"
    FORBIDDEN_REGIME_LABEL_COLUMN = "FORBIDDEN_REGIME_LABEL_COLUMN"
    TRADE_SIGNAL_COLUMN_RISK = "TRADE_SIGNAL_COLUMN_RISK"
    ORDER_DECISION_COLUMN_RISK = "ORDER_DECISION_COLUMN_RISK"
    PORTFOLIO_WEIGHT_COLUMN_RISK = "PORTFOLIO_WEIGHT_COLUMN_RISK"
    BROKER_COLUMN_RISK = "BROKER_COLUMN_RISK"
    PAPER_MUTATION_COLUMN_RISK = "PAPER_MUTATION_COLUMN_RISK"
    DEPLOYMENT_RISK = "DEPLOYMENT_RISK"
    SECRET_LEAK_RISK = "SECRET_LEAK_RISK"
    INVESTMENT_ADVICE_LANGUAGE_RISK = "INVESTMENT_ADVICE_LANGUAGE_RISK"
    NETWORK_FETCH_ATTEMPTED = "NETWORK_FETCH_ATTEMPTED"
    NETWORK_DEFAULT_ENABLED_RISK = "NETWORK_DEFAULT_ENABLED_RISK"
    PAID_API_RISK = "PAID_API_RISK"
    SCRAPING_RISK = "SCRAPING_RISK"
    HTML_PARSE_RISK = "HTML_PARSE_RISK"
    BROKER_RISK = "BROKER_RISK"
    ORDER_RISK = "ORDER_RISK"
    PAPER_MUTATION_RISK = "PAPER_MUTATION_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    DASHBOARD_RISK = "DASHBOARD_RISK"
    UNKNOWN = "UNKNOWN"

class RegimeLabelingReportType(str, Enum):
    HEURISTIC_LABELING_REPORT = "HEURISTIC_LABELING_REPORT"
    ROLLING_REGIME_WINDOW_REPORT = "ROLLING_REGIME_WINDOW_REPORT"
    CANDIDATE_VALIDATION_REPORT = "CANDIDATE_VALIDATION_REPORT"
    LABEL_STABILITY_REPORT = "LABEL_STABILITY_REPORT"
    FULL_PHASE128_REVIEW = "FULL_PHASE128_REVIEW"
"""

if "RegimeLabelingStatus" not in content:
    content += "\n" + new_enums

# Update NotificationType
if "REGIME_LABELING_REPORT = " not in content:
    content = re.sub(
        r'(class NotificationType\(str, Enum\):[^}]+?)(?=\n\n|\Z)',
        r'\1\n    REGIME_LABELING_REPORT = "REGIME_LABELING_REPORT"\n    REGIME_LABELING_WARNING = "REGIME_LABELING_WARNING"\n    REGIME_CANDIDATE_VALIDATION_WARNING = "REGIME_CANDIDATE_VALIDATION_WARNING"',
        content
    )

# Update AlertType
if "REGIME_LABELING_BLOCKED = " not in content:
    content = re.sub(
        r'(class AlertType\(str, Enum\):[^}]+?)(?=\n\n|\Z)',
        r'\1\n    REGIME_LABELING_BLOCKED = "REGIME_LABELING_BLOCKED"\n    REGIME_CANDIDATE_VALIDATION_BLOCKED = "REGIME_CANDIDATE_VALIDATION_BLOCKED"\n    REGIME_LABEL_STABILITY_BLOCKED = "REGIME_LABEL_STABILITY_BLOCKED"',
        content
    )

with open("usa_signal_bot/core/enums.py", "w") as f:
    f.write(content)
