import re

with open('usa_signal_bot/core/enums.py', 'r') as f:
    content = f.read()

new_enums = """

class PaperModeAdmissionReviewStatus(str, Enum):
    DRAFT = "DRAFT"
    READY = "READY"
    REVIEWING = "REVIEWING"
    COMPLETED_NO_WRITE = "COMPLETED_NO_WRITE"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    BLOCKED = "BLOCKED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class PaperModeAdmissionReviewDecision(str, Enum):
    PASS_TO_NO_WRITE_TRANSITION_CHECKPOINT = "PASS_TO_NO_WRITE_TRANSITION_CHECKPOINT"
    REQUEST_DRY_ADMISSION_REFRESH = "REQUEST_DRY_ADMISSION_REFRESH"
    REQUEST_LEDGER_RECONCILIATION = "REQUEST_LEDGER_RECONCILIATION"
    REQUEST_WRITE_LOCK_REFRESH = "REQUEST_WRITE_LOCK_REFRESH"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    REJECT = "REJECT"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class AdmissionReviewGateStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    NOT_REVIEWED = "NOT_REVIEWED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class LedgerReconciliationStatus(str, Enum):
    DRAFT = "DRAFT"
    RECONCILED = "RECONCILED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class LedgerReconciliationDecision(str, Enum):
    ACCEPT_NO_WRITE_ACKNOWLEDGEMENT = "ACCEPT_NO_WRITE_ACKNOWLEDGEMENT"
    REQUEST_LEDGER_CORRECTION = "REQUEST_LEDGER_CORRECTION"
    REQUEST_MISSING_SCOPE_REVIEW = "REQUEST_MISSING_SCOPE_REVIEW"
    REQUEST_UNSAFE_NOTE_REVIEW = "REQUEST_UNSAFE_NOTE_REVIEW"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    REJECT = "REJECT"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class NoWriteTransitionCheckpointStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    VALIDATED_NO_WRITE = "VALIDATED_NO_WRITE"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    BLOCKED = "BLOCKED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class NoWriteTransitionCheckpointDecision(str, Enum):
    CONTINUE_TO_NO_WRITE_TRANSITION_DOSSIER = "CONTINUE_TO_NO_WRITE_TRANSITION_DOSSIER"
    REQUEST_ADMISSION_REVIEW_REFRESH = "REQUEST_ADMISSION_REVIEW_REFRESH"
    REQUEST_LEDGER_RECONCILIATION_REFRESH = "REQUEST_LEDGER_RECONCILIATION_REFRESH"
    REQUEST_EVIDENCE_SEAL_REFRESH = "REQUEST_EVIDENCE_SEAL_REFRESH"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    REJECT = "REJECT"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class AdmissionEvidenceSealStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    SEALED = "SEALED"
    VALIDATED = "VALIDATED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class AdmissionReviewRiskFlag(str, Enum):
    REAL_ORDER_RISK = "REAL_ORDER_RISK"
    PAPER_ORDER_RISK = "PAPER_ORDER_RISK"
    BROKER_ORDER_RISK = "BROKER_ORDER_RISK"
    PAPER_STATE_MUTATION_RISK = "PAPER_STATE_MUTATION_RISK"
    PAPER_POSITION_MUTATION_RISK = "PAPER_POSITION_MUTATION_RISK"
    PAPER_PORTFOLIO_MUTATION_RISK = "PAPER_PORTFOLIO_MUTATION_RISK"
    PAPER_CASH_MUTATION_RISK = "PAPER_CASH_MUTATION_RISK"
    PAPER_EQUITY_MUTATION_RISK = "PAPER_EQUITY_MUTATION_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    PRODUCTION_CONFIG_WRITE_RISK = "PRODUCTION_CONFIG_WRITE_RISK"
    ACTIVE_PAPER_ENABLE_RISK = "ACTIVE_PAPER_ENABLE_RISK"
    ACTIVATION_ALLOWED_RISK = "ACTIVATION_ALLOWED_RISK"
    DRY_ADMISSION_STALE = "DRY_ADMISSION_STALE"
    DRY_ADMISSION_FAILED = "DRY_ADMISSION_FAILED"
    WRITE_LOCK_REFRESH_FAILED = "WRITE_LOCK_REFRESH_FAILED"
    LEDGER_MISSING = "LEDGER_MISSING"
    LEDGER_SCOPE_MISSING = "LEDGER_SCOPE_MISSING"
    LEDGER_UNSAFE_NOTE = "LEDGER_UNSAFE_NOTE"
    LEDGER_ACTIVATION_RISK = "LEDGER_ACTIVATION_RISK"
    NO_WRITE_CONTINUITY_FAILED = "NO_WRITE_CONTINUITY_FAILED"
    EVIDENCE_MISSING = "EVIDENCE_MISSING"
    EVIDENCE_STALE = "EVIDENCE_STALE"
    EVIDENCE_SEAL_FAILED = "EVIDENCE_SEAL_FAILED"
    TRANSITION_CHECKPOINT_INVALID = "TRANSITION_CHECKPOINT_INVALID"
    SECRET_RISK = "SECRET_RISK"
    UNKNOWN = "UNKNOWN"

class AdmissionReviewReportType(str, Enum):
    ADMISSION_REVIEW_REPORT = "ADMISSION_REVIEW_REPORT"
    LEDGER_RECONCILIATION_REPORT = "LEDGER_RECONCILIATION_REPORT"
    NO_WRITE_TRANSITION_CHECKPOINT_REPORT = "NO_WRITE_TRANSITION_CHECKPOINT_REPORT"
    SAFETY_REVIEW = "SAFETY_REVIEW"
    FULL_ADMISSION_REVIEW = "FULL_ADMISSION_REVIEW"

"""

if "class PaperModeAdmissionReviewStatus" not in content:
    content = content + new_enums

# Update NotificationType safely
notif_match = re.search(r'(class NotificationType\(str, Enum\):.*?)(?=\n\n|\nclass)', content, re.MULTILINE | re.DOTALL)
if notif_match:
    block = notif_match.group(1)
    if "ADMISSION_REVIEW_REPORT" not in block:
        content = content.replace(block, block + "\n    ADMISSION_REVIEW_REPORT = \"ADMISSION_REVIEW_REPORT\"\n    LEDGER_RECONCILIATION_WARNING = \"LEDGER_RECONCILIATION_WARNING\"\n    NO_WRITE_TRANSITION_CHECKPOINT_WARNING = \"NO_WRITE_TRANSITION_CHECKPOINT_WARNING\"")

# Update AlertType safely
alert_match = re.search(r'(class AlertType\(str, Enum\):.*?)(?=\n\n|\nclass)', content, re.MULTILINE | re.DOTALL)
if alert_match:
    block = alert_match.group(1)
    if "ADMISSION_REVIEW_BLOCKED" not in block:
        content = content.replace(block, block + "\n    ADMISSION_REVIEW_BLOCKED = \"ADMISSION_REVIEW_BLOCKED\"\n    LEDGER_RECONCILIATION_BLOCKED = \"LEDGER_RECONCILIATION_BLOCKED\"\n    NO_WRITE_TRANSITION_CHECKPOINT_BLOCKED = \"NO_WRITE_TRANSITION_CHECKPOINT_BLOCKED\"")

with open('usa_signal_bot/core/enums.py', 'w') as f:
    f.write(content)
