import re

file_path = "usa_signal_bot/core/enums.py"

with open(file_path, "r") as f:
    content = f.read()

new_enums = """
class RegimeResearchFreezeStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    MONITORING_INGESTED = "MONITORING_INGESTED"
    MONITORING_ARTIFACTS_LOADED = "MONITORING_ARTIFACTS_LOADED"
    MONITORING_VALIDATED = "MONITORING_VALIDATED"
    DRIFT_REPORT_BUILT = "DRIFT_REPORT_BUILT"
    DRIFT_REPORT_QA_PASSED = "DRIFT_REPORT_QA_PASSED"
    FREEZE_PACKAGE_BUILT = "FREEZE_PACKAGE_BUILT"
    FREEZE_PACKAGE_VALIDATED = "FREEZE_PACKAGE_VALIDATED"
    READINESS_GATE_BUILT = "READINESS_GATE_BUILT"
    READINESS_GATE_PASSED = "READINESS_GATE_PASSED"
    VALIDATED = "VALIDATED"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class RegimeResearchFreezeDecision(str, Enum):
    VALIDATE_MONITORING = "VALIDATE_MONITORING"
    BUILD_DRIFT_REPORT = "BUILD_DRIFT_REPORT"
    RUN_DRIFT_REPORT_QA = "RUN_DRIFT_REPORT_QA"
    BUILD_FREEZE_PACKAGE = "BUILD_FREEZE_PACKAGE"
    VALIDATE_FREEZE_PACKAGE = "VALIDATE_FREEZE_PACKAGE"
    BUILD_READINESS_GATE = "BUILD_READINESS_GATE"
    REQUEST_MONITORING_REFRESH = "REQUEST_MONITORING_REFRESH"
    REQUEST_DRIFT_REPORT_FIX = "REQUEST_DRIFT_REPORT_FIX"
    REQUEST_FREEZE_PACKAGE_FIX = "REQUEST_FREEZE_PACKAGE_FIX"
    REQUEST_SCHEMA_FIX = "REQUEST_SCHEMA_FIX"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class MonitoringValidationRuleKind(str, Enum):
    MONITORING_REVIEW_VALID = "MONITORING_REVIEW_VALID"
    BASELINE_AVAILABLE = "BASELINE_AVAILABLE"
    SNAPSHOT_AVAILABLE = "SNAPSHOT_AVAILABLE"
    DRIFT_RESULT_AVAILABLE = "DRIFT_RESULT_AVAILABLE"
    DEGRADATION_DIAGNOSTICS_AVAILABLE = "DEGRADATION_DIAGNOSTICS_AVAILABLE"
    MONITORING_READINESS_GATE_PASSED = "MONITORING_READINESS_GATE_PASSED"
    BASELINE_HASH_VALID = "BASELINE_HASH_VALID"
    SNAPSHOT_HASH_VALID = "SNAPSHOT_HASH_VALID"
    DRIFT_RESULT_VALID = "DRIFT_RESULT_VALID"
    DEGRADATION_RESULT_VALID = "DEGRADATION_RESULT_VALID"
    CONSISTENCY_VALID = "CONSISTENCY_VALID"
    SAFETY_BOUNDARY_VALID = "SAFETY_BOUNDARY_VALID"
    NO_SIGNAL_OUTPUT = "NO_SIGNAL_OUTPUT"
    NO_ORDER_OUTPUT = "NO_ORDER_OUTPUT"
    NO_PORTFOLIO_OUTPUT = "NO_PORTFOLIO_OUTPUT"
    NO_EXECUTION_OUTPUT = "NO_EXECUTION_OUTPUT"
    NO_MODEL_TRAINING = "NO_MODEL_TRAINING"
    UNKNOWN = "UNKNOWN"

class MonitoringValidationStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class DriftReportQaStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class DriftReportLanguageRiskKind(str, Enum):
    INVESTMENT_ADVICE_LANGUAGE = "INVESTMENT_ADVICE_LANGUAGE"
    TRADE_SIGNAL_LANGUAGE = "TRADE_SIGNAL_LANGUAGE"
    ORDER_DECISION_LANGUAGE = "ORDER_DECISION_LANGUAGE"
    PORTFOLIO_ALLOCATION_LANGUAGE = "PORTFOLIO_ALLOCATION_LANGUAGE"
    GUARANTEE_LANGUAGE = "GUARANTEE_LANGUAGE"
    BROKER_EXECUTION_LANGUAGE = "BROKER_EXECUTION_LANGUAGE"
    DEPLOYMENT_LANGUAGE = "DEPLOYMENT_LANGUAGE"
    LIVE_MONITORING_LANGUAGE = "LIVE_MONITORING_LANGUAGE"
    SECRET_LANGUAGE = "SECRET_LANGUAGE"
    UNKNOWN = "UNKNOWN"

class DriftReportSectionKind(str, Enum):
    EXECUTIVE_SUMMARY = "EXECUTIVE_SUMMARY"
    DATA_SCOPE = "DATA_SCOPE"
    BASELINE_SUMMARY = "BASELINE_SUMMARY"
    SNAPSHOT_SUMMARY = "SNAPSHOT_SUMMARY"
    DRIFT_SUMMARY = "DRIFT_SUMMARY"
    DEGRADATION_SUMMARY = "DEGRADATION_SUMMARY"
    CONSISTENCY_SUMMARY = "CONSISTENCY_SUMMARY"
    SAFETY_BOUNDARY = "SAFETY_BOUNDARY"
    LIMITATIONS = "LIMITATIONS"
    APPENDIX = "APPENDIX"
    UNKNOWN = "UNKNOWN"

class ResearchFreezeArtifactKind(str, Enum):
    REGIME_FOUNDATION_REVIEW = "REGIME_FOUNDATION_REVIEW"
    REGIME_FEATURE_ENGINEERING_REVIEW = "REGIME_FEATURE_ENGINEERING_REVIEW"
    REGIME_LABELING_REVIEW = "REGIME_LABELING_REVIEW"
    REGIME_TRANSITION_REVIEW = "REGIME_TRANSITION_REVIEW"
    MARKET_BEHAVIOR_REVIEW = "MARKET_BEHAVIOR_REVIEW"
    REGIME_ALIGNMENT_REVIEW = "REGIME_ALIGNMENT_REVIEW"
    CONTEXT_VALIDATION_REVIEW = "CONTEXT_VALIDATION_REVIEW"
    REGIME_MONITORING_REVIEW = "REGIME_MONITORING_REVIEW"
    DRIFT_REPORT = "DRIFT_REPORT"
    FREEZE_PACKAGE_MANIFEST = "FREEZE_PACKAGE_MANIFEST"
    SAFETY_BOUNDARY_REPORT = "SAFETY_BOUNDARY_REPORT"
    UNKNOWN = "UNKNOWN"

class ResearchFreezeReadinessStatus(str, Enum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class ResearchFreezeReadinessRuleKind(str, Enum):
    MONITORING_VALIDATION_PASSED = "MONITORING_VALIDATION_PASSED"
    DRIFT_REPORT_QA_PASSED = "DRIFT_REPORT_QA_PASSED"
    FREEZE_PACKAGE_COMPLETE = "FREEZE_PACKAGE_COMPLETE"
    FREEZE_PACKAGE_HASH_VALID = "FREEZE_PACKAGE_HASH_VALID"
    REQUIRED_ARTIFACTS_REFERENCED = "REQUIRED_ARTIFACTS_REFERENCED"
    SAFETY_BOUNDARY_VALID = "SAFETY_BOUNDARY_VALID"
    NO_SIGNAL_OUTPUT = "NO_SIGNAL_OUTPUT"
    NO_ORDER_OUTPUT = "NO_ORDER_OUTPUT"
    NO_PORTFOLIO_OUTPUT = "NO_PORTFOLIO_OUTPUT"
    NO_EXECUTION_OUTPUT = "NO_EXECUTION_OUTPUT"
    NO_MODEL_TRAINING = "NO_MODEL_TRAINING"
    READY_FOR_PHASE135 = "READY_FOR_PHASE135"
    UNKNOWN = "UNKNOWN"

class ResearchFreezeQuality(str, Enum):
    HIGH = "HIGH"
    ACCEPTABLE = "ACCEPTABLE"
    WARNING = "WARNING"
    LOW = "LOW"
    INVALID = "INVALID"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class ResearchFreezeRiskFlag(str, Enum):
    REGIME_MONITORING_REVIEW_MISSING = "REGIME_MONITORING_REVIEW_MISSING"
    REGIME_MONITORING_REVIEW_INVALID = "REGIME_MONITORING_REVIEW_INVALID"
    PHASE133_NOT_READY = "PHASE133_NOT_READY"
    MONITORING_BASELINE_MISSING = "MONITORING_BASELINE_MISSING"
    MONITORING_SNAPSHOT_MISSING = "MONITORING_SNAPSHOT_MISSING"
    DRIFT_RESULT_MISSING = "DRIFT_RESULT_MISSING"
    DEGRADATION_DIAGNOSTICS_MISSING = "DEGRADATION_DIAGNOSTICS_MISSING"
    MONITORING_VALIDATION_FAILED = "MONITORING_VALIDATION_FAILED"
    DRIFT_REPORT_INVALID = "DRIFT_REPORT_INVALID"
    DRIFT_REPORT_QA_FAILED = "DRIFT_REPORT_QA_FAILED"
    FREEZE_PACKAGE_INVALID = "FREEZE_PACKAGE_INVALID"
    REQUIRED_ARTIFACT_MISSING = "REQUIRED_ARTIFACT_MISSING"
    FREEZE_HASH_INVALID = "FREEZE_HASH_INVALID"
    CONSISTENCY_VALIDATION_FAILED = "CONSISTENCY_VALIDATION_FAILED"
    MODEL_TRAINING_ATTEMPTED = "MODEL_TRAINING_ATTEMPTED"
    MODEL_PREDICTION_RISK = "MODEL_PREDICTION_RISK"
    HEAVY_ML_DEPENDENCY_RISK = "HEAVY_ML_DEPENDENCY_RISK"
    FORBIDDEN_RESEARCH_FREEZE_COLUMN = "FORBIDDEN_RESEARCH_FREEZE_COLUMN"
    TRADE_SIGNAL_COLUMN_RISK = "TRADE_SIGNAL_COLUMN_RISK"
    ORDER_DECISION_COLUMN_RISK = "ORDER_DECISION_COLUMN_RISK"
    PORTFOLIO_WEIGHT_COLUMN_RISK = "PORTFOLIO_WEIGHT_COLUMN_RISK"
    BROKER_COLUMN_RISK = "BROKER_COLUMN_RISK"
    PAPER_MUTATION_COLUMN_RISK = "PAPER_MUTATION_COLUMN_RISK"
    DEPLOYMENT_RISK = "DEPLOYMENT_RISK"
    SECRET_LEAK_RISK = "SECRET_LEAK_RISK"
    INVESTMENT_ADVICE_LANGUAGE_RISK = "INVESTMENT_ADVICE_LANGUAGE_RISK"
    NETWORK_FETCH_ATTEMPTED = "NETWORK_FETCH_ATTEMPTED"
    NETWORK_DEFAULT_ENABLED_RISK = "NETWORK_DEFAULT_ENABLED_RISK"
    PAID_API_RISK = "PAID_API_RISK"
    SCRAPING_RISK = "SCRAPING_RISK"
    HTML_PARSE_RISK = "HTML_PARSE_RISK"
    BROKER_RISK = "BROKER_RISK"
    ORDER_RISK = "ORDER_RISK"
    PAPER_MUTATION_RISK = "PAPER_MUTATION_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    DASHBOARD_RISK = "DASHBOARD_RISK"
    DAEMON_RISK = "DAEMON_RISK"
    SCHEDULER_RISK = "SCHEDULER_RISK"
    UNKNOWN = "UNKNOWN"

class RegimeResearchFreezeReportType(str, Enum):
    MONITORING_VALIDATION_REPORT = "MONITORING_VALIDATION_REPORT"
    DRIFT_REPORT_QA_REPORT = "DRIFT_REPORT_QA_REPORT"
    RESEARCH_FREEZE_PACKAGE_REPORT = "RESEARCH_FREEZE_PACKAGE_REPORT"
    RESEARCH_FREEZE_READINESS_REPORT = "RESEARCH_FREEZE_READINESS_REPORT"
    FULL_PHASE134_REVIEW = "FULL_PHASE134_REVIEW"
"""

if "RegimeResearchFreezeStatus" not in content:
    content += "\n" + new_enums

# Also add elements to NotificationType and AlertType if needed (I will just add them via string replacement)
if "REGIME_RESEARCH_FREEZE_REPORT" not in content:
    content = content.replace(
        "    FEATURE_FACTOR_CLOSURE_REPORT = \"FEATURE_FACTOR_CLOSURE_REPORT\"",
        "    FEATURE_FACTOR_CLOSURE_REPORT = \"FEATURE_FACTOR_CLOSURE_REPORT\"\n    REGIME_RESEARCH_FREEZE_REPORT = \"REGIME_RESEARCH_FREEZE_REPORT\"\n    DRIFT_REPORT_QA_WARNING = \"DRIFT_REPORT_QA_WARNING\"\n    RESEARCH_FREEZE_PACKAGE_WARNING = \"RESEARCH_FREEZE_PACKAGE_WARNING\""
    )

if "REGIME_RESEARCH_FREEZE_BLOCKED" not in content:
    content = content.replace(
        "    FEATURE_FACTOR_CLOSURE_BLOCKED = \"FEATURE_FACTOR_CLOSURE_BLOCKED\"",
        "    FEATURE_FACTOR_CLOSURE_BLOCKED = \"FEATURE_FACTOR_CLOSURE_BLOCKED\"\n    REGIME_RESEARCH_FREEZE_BLOCKED = \"REGIME_RESEARCH_FREEZE_BLOCKED\"\n    DRIFT_REPORT_QA_BLOCKED = \"DRIFT_REPORT_QA_BLOCKED\"\n    RESEARCH_FREEZE_PACKAGE_BLOCKED = \"RESEARCH_FREEZE_PACKAGE_BLOCKED\""
    )

with open(file_path, "w") as f:
    f.write(content)
