import re

# 1. Update enums.py
with open("usa_signal_bot/core/enums.py", "r") as f:
    content = f.read()

enums_to_add = """
class MarketBehaviorStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    TRANSITION_ANALYTICS_INGESTED = "TRANSITION_ANALYTICS_INGESTED"
    DIAGNOSTICS_LOADED = "DIAGNOSTICS_LOADED"
    PROFILE_SPECS_BUILT = "PROFILE_SPECS_BUILT"
    BEHAVIOR_PROFILES_BUILT = "BEHAVIOR_PROFILES_BUILT"
    REGIME_SUMMARIES_BUILT = "REGIME_SUMMARIES_BUILT"
    DIAGNOSTICS_INTERPRETED = "DIAGNOSTICS_INTERPRETED"
    REPORT_BUILT = "REPORT_BUILT"
    REPORT_QA_PASSED = "REPORT_QA_PASSED"
    READINESS_GATE_PASSED = "READINESS_GATE_PASSED"
    VALIDATED = "VALIDATED"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class MarketBehaviorDecision(str, Enum):
    BUILD_BEHAVIOR_PROFILES = "BUILD_BEHAVIOR_PROFILES"
    BUILD_REGIME_SUMMARIES = "BUILD_REGIME_SUMMARIES"
    BUILD_DIAGNOSTICS_REPORT = "BUILD_DIAGNOSTICS_REPORT"
    RUN_REPORT_QA = "RUN_REPORT_QA"
    BUILD_READINESS_GATE = "BUILD_READINESS_GATE"
    REQUEST_TRANSITION_ANALYTICS_REFRESH = "REQUEST_TRANSITION_ANALYTICS_REFRESH"
    REQUEST_DIAGNOSTICS_FIX = "REQUEST_DIAGNOSTICS_FIX"
    REQUEST_REPORT_LANGUAGE_FIX = "REQUEST_REPORT_LANGUAGE_FIX"
    REQUEST_SCHEMA_FIX = "REQUEST_SCHEMA_FIX"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class MarketBehaviorProfileKind(str, Enum):
    TREND_BEHAVIOR = "TREND_BEHAVIOR"
    VOLATILITY_BEHAVIOR = "VOLATILITY_BEHAVIOR"
    MOMENTUM_BEHAVIOR = "MOMENTUM_BEHAVIOR"
    LIQUIDITY_BEHAVIOR = "LIQUIDITY_BEHAVIOR"
    CHURN_BEHAVIOR = "CHURN_BEHAVIOR"
    PERSISTENCE_BEHAVIOR = "PERSISTENCE_BEHAVIOR"
    STABILITY_BEHAVIOR = "STABILITY_BEHAVIOR"
    TRANSITION_BEHAVIOR = "TRANSITION_BEHAVIOR"
    DATA_QUALITY_BEHAVIOR = "DATA_QUALITY_BEHAVIOR"
    CROSS_SYMBOL_BEHAVIOR = "CROSS_SYMBOL_BEHAVIOR"
    UNKNOWN = "UNKNOWN"

class RegimeBehaviorSummaryKind(str, Enum):
    REGIME_TRANSITION_SUMMARY = "REGIME_TRANSITION_SUMMARY"
    REGIME_PERSISTENCE_SUMMARY = "REGIME_PERSISTENCE_SUMMARY"
    REGIME_DURATION_SUMMARY = "REGIME_DURATION_SUMMARY"
    REGIME_CHURN_SUMMARY = "REGIME_CHURN_SUMMARY"
    REGIME_STABILITY_SUMMARY = "REGIME_STABILITY_SUMMARY"
    REGIME_CONFIDENCE_SUMMARY = "REGIME_CONFIDENCE_SUMMARY"
    REGIME_DATA_QUALITY_SUMMARY = "REGIME_DATA_QUALITY_SUMMARY"
    CROSS_SYMBOL_SUMMARY = "CROSS_SYMBOL_SUMMARY"
    LIMITATION_SUMMARY = "LIMITATION_SUMMARY"
    UNKNOWN = "UNKNOWN"

class BehaviorReportSectionKind(str, Enum):
    EXECUTIVE_SUMMARY = "EXECUTIVE_SUMMARY"
    DATA_SCOPE = "DATA_SCOPE"
    TRANSITION_MATRIX_SUMMARY = "TRANSITION_MATRIX_SUMMARY"
    PERSISTENCE_SUMMARY = "PERSISTENCE_SUMMARY"
    DURATION_CHURN_SUMMARY = "DURATION_CHURN_SUMMARY"
    STABILITY_SUMMARY = "STABILITY_SUMMARY"
    MARKET_BEHAVIOR_PROFILES = "MARKET_BEHAVIOR_PROFILES"
    CROSS_SYMBOL_BEHAVIOR = "CROSS_SYMBOL_BEHAVIOR"
    DIAGNOSTIC_INTERPRETATION = "DIAGNOSTIC_INTERPRETATION"
    LIMITATIONS = "LIMITATIONS"
    SAFETY_BOUNDARY = "SAFETY_BOUNDARY"
    APPENDIX = "APPENDIX"
    UNKNOWN = "UNKNOWN"

class BehaviorReportFormat(str, Enum):
    MARKDOWN = "MARKDOWN"
    JSON = "JSON"
    TEXT = "TEXT"
    UNKNOWN = "UNKNOWN"

class BehaviorReportQaStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class BehaviorReportLanguageRiskKind(str, Enum):
    INVESTMENT_ADVICE_LANGUAGE = "INVESTMENT_ADVICE_LANGUAGE"
    TRADE_SIGNAL_LANGUAGE = "TRADE_SIGNAL_LANGUAGE"
    ORDER_DECISION_LANGUAGE = "ORDER_DECISION_LANGUAGE"
    PORTFOLIO_ALLOCATION_LANGUAGE = "PORTFOLIO_ALLOCATION_LANGUAGE"
    GUARANTEE_LANGUAGE = "GUARANTEE_LANGUAGE"
    BROKER_EXECUTION_LANGUAGE = "BROKER_EXECUTION_LANGUAGE"
    DEPLOYMENT_LANGUAGE = "DEPLOYMENT_LANGUAGE"
    SENSITIVE_SECRET_LANGUAGE = "SENSITIVE_SECRET_LANGUAGE"
    UNKNOWN = "UNKNOWN"

class MarketBehaviorReadinessStatus(str, Enum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class MarketBehaviorReadinessRuleKind(str, Enum):
    TRANSITION_ANALYTICS_VALID = "TRANSITION_ANALYTICS_VALID"
    DIAGNOSTICS_ARTIFACTS_AVAILABLE = "DIAGNOSTICS_ARTIFACTS_AVAILABLE"
    BEHAVIOR_PROFILES_VALID = "BEHAVIOR_PROFILES_VALID"
    REGIME_SUMMARIES_VALID = "REGIME_SUMMARIES_VALID"
    REPORT_DOCUMENT_VALID = "REPORT_DOCUMENT_VALID"
    REPORT_QA_PASSED = "REPORT_QA_PASSED"
    NO_SIGNAL_OUTPUT = "NO_SIGNAL_OUTPUT"
    NO_ORDER_OUTPUT = "NO_ORDER_OUTPUT"
    NO_PORTFOLIO_OUTPUT = "NO_PORTFOLIO_OUTPUT"
    NO_EXECUTION_OUTPUT = "NO_EXECUTION_OUTPUT"
    NO_MODEL_TRAINING = "NO_MODEL_TRAINING"
    READY_FOR_PHASE131 = "READY_FOR_PHASE131"
    UNKNOWN = "UNKNOWN"

class MarketBehaviorQuality(str, Enum):
    HIGH = "HIGH"
    ACCEPTABLE = "ACCEPTABLE"
    WARNING = "WARNING"
    LOW = "LOW"
    INVALID = "INVALID"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class MarketBehaviorRiskFlag(str, Enum):
    REGIME_TRANSITION_REVIEW_MISSING = "REGIME_TRANSITION_REVIEW_MISSING"
    REGIME_TRANSITION_REVIEW_INVALID = "REGIME_TRANSITION_REVIEW_INVALID"
    PHASE129_NOT_READY = "PHASE129_NOT_READY"
    TRANSITION_MATRIX_MISSING = "TRANSITION_MATRIX_MISSING"
    PERSISTENCE_PROFILE_MISSING = "PERSISTENCE_PROFILE_MISSING"
    CHURN_DIAGNOSTIC_MISSING = "CHURN_DIAGNOSTICS_MISSING"
    STABILITY_DIAGNOSTIC_MISSING = "STABILITY_DIAGNOSTICS_MISSING"
    BEHAVIOR_PROFILE_INVALID = "BEHAVIOR_PROFILE_INVALID"
    REGIME_SUMMARY_INVALID = "REGIME_SUMMARY_INVALID"
    DIAGNOSTICS_INTERPRETATION_INVALID = "DIAGNOSTICS_INTERPRETATION_INVALID"
    BEHAVIOR_REPORT_INVALID = "BEHAVIOR_REPORT_INVALID"
    REPORT_QA_FAILED = "REPORT_QA_FAILED"
    UNSAFE_REPORT_LANGUAGE = "UNSAFE_REPORT_LANGUAGE"
    MODEL_TRAINING_ATTEMPTED = "MODEL_TRAINING_ATTEMPTED"
    MODEL_PREDICTION_RISK = "MODEL_PREDICTION_RISK"
    HEAVY_ML_DEPENDENCY_RISK = "HEAVY_ML_DEPENDENCY_RISK"
    FORBIDDEN_MARKET_BEHAVIOR_COLUMN = "FORBIDDEN_MARKET_BEHAVIOR_COLUMN"
    TRADE_SIGNAL_COLUMN_RISK = "TRADE_SIGNAL_COLUMN_RISK"
    ORDER_DECISION_COLUMN_RISK = "ORDER_DECISION_COLUMN_RISK"
    PORTFOLIO_WEIGHT_COLUMN_RISK = "PORTFOLIO_WEIGHT_COLUMN_RISK"
    BROKER_COLUMN_RISK = "BROKER_COLUMN_RISK"
    PAPER_MUTATION_COLUMN_RISK = "PAPER_MUTATION_COLUMN_RISK"
    DEPLOYMENT_RISK = "DEPLOYMENT_RISK"
    SECRET_LEAK_RISK = "SECRET_LEAK_RISK"
    INVESTMENT_ADVICE_LANGUAGE_RISK = "INVESTMENT_ADVICE_LANGUAGE_RISK"
    NETWORK_FETCH_ATTEMPTED = "NETWORK_FETCH_ATTEMPTED"
    NETWORK_DEFAULT_ENABLED_RISK = "NETWORK_DEFAULT_ENABLED_RISK"
    PAID_API_RISK = "PAID_API_RISK"
    SCRAPING_RISK = "SCRAPING_RISK"
    HTML_PARSE_RISK = "HTML_PARSE_RISK"
    BROKER_RISK = "BROKER_RISK"
    ORDER_RISK = "ORDER_RISK"
    PAPER_MUTATION_RISK = "PAPER_MUTATION_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    DASHBOARD_RISK = "DASHBOARD_RISK"
    UNKNOWN = "UNKNOWN"

class MarketBehaviorReportType(str, Enum):
    MARKET_BEHAVIOR_PROFILE_REPORT = "MARKET_BEHAVIOR_PROFILE_REPORT"
    REGIME_BEHAVIOR_SUMMARY_REPORT = "REGIME_BEHAVIOR_SUMMARY_REPORT"
    DIAGNOSTICS_REPORT_LAYER = "DIAGNOSTICS_REPORT_LAYER"
    REPORT_QA_REPORT = "REPORT_QA_REPORT"
    FULL_PHASE130_REVIEW = "FULL_PHASE130_REVIEW"

"""

if "MarketBehaviorStatus" not in content:
    content += "\n" + enums_to_add

# Update NotificationType
if "MARKET_BEHAVIOR_REPORT" not in content:
    content = re.sub(
        r'(class NotificationType\(str, Enum\):[^}]+?)\n\s*UNKNOWN = "UNKNOWN"',
        r'\1\n    MARKET_BEHAVIOR_REPORT = "MARKET_BEHAVIOR_REPORT"\n    BEHAVIOR_REPORT_QA_WARNING = "BEHAVIOR_REPORT_QA_WARNING"\n    MARKET_BEHAVIOR_PROFILE_WARNING = "MARKET_BEHAVIOR_PROFILE_WARNING"\n    UNKNOWN = "UNKNOWN"',
        content
    )

# Update AlertType
if "MARKET_BEHAVIOR_BLOCKED" not in content:
    content = re.sub(
        r'(class AlertType\(str, Enum\):[^}]+?)\n\s*UNKNOWN = "UNKNOWN"',
        r'\1\n    MARKET_BEHAVIOR_BLOCKED = "MARKET_BEHAVIOR_BLOCKED"\n    BEHAVIOR_REPORT_QA_BLOCKED = "BEHAVIOR_REPORT_QA_BLOCKED"\n    MARKET_BEHAVIOR_PROFILE_BLOCKED = "MARKET_BEHAVIOR_PROFILE_BLOCKED"\n    UNKNOWN = "UNKNOWN"',
        content
    )

with open("usa_signal_bot/core/enums.py", "w") as f:
    f.write(content)

# 2. Update exceptions.py
with open("usa_signal_bot/core/exceptions.py", "r") as f:
    content_ex = f.read()

exceptions_to_add = """
class MarketBehaviorReportingError(USASignalBotError): pass
class RegimeTransitionIngestionError(MarketBehaviorReportingError): pass
class DiagnosticsArtifactLoaderError(MarketBehaviorReportingError): pass
class MarketBehaviorProfileSpecError(MarketBehaviorReportingError): pass
class MarketBehaviorProfileBuilderError(MarketBehaviorReportingError): pass
class RegimeBehaviorSummaryBuilderError(MarketBehaviorReportingError): pass
class DiagnosticsInterpretationBuilderError(MarketBehaviorReportingError): pass
class CrossSymbolBehaviorProfileError(MarketBehaviorReportingError): pass
class BehaviorReportSectionError(MarketBehaviorReportingError): pass
class BehaviorReportDocumentError(MarketBehaviorReportingError): pass
class BehaviorReportRendererError(MarketBehaviorReportingError): pass
class BehaviorReportQaValidationError(MarketBehaviorReportingError): pass
class BehaviorReportReadinessGateError(MarketBehaviorReportingError): pass
class MarketBehaviorSafetyValidationError(MarketBehaviorReportingError): pass
class MarketBehaviorStoreError(MarketBehaviorReportingError): pass
class MarketBehaviorValidationError(MarketBehaviorReportingError): pass
"""
if "MarketBehaviorReportingError" not in content_ex:
    content_ex += "\n" + exceptions_to_add
    with open("usa_signal_bot/core/exceptions.py", "w") as f:
        f.write(content_ex)

print("Updated enums and exceptions.")
