import sys

def patch_enums():
    file_path = "usa_signal_bot/core/enums.py"
    with open(file_path, "r") as f:
        content = f.read()

    new_enums = """
class RegimeFinalClosureStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    RESEARCH_FREEZE_INGESTED = "RESEARCH_FREEZE_INGESTED"
    ARTIFACT_CHAIN_LOADED = "ARTIFACT_CHAIN_LOADED"
    ARTIFACT_CHAIN_VALIDATED = "ARTIFACT_CHAIN_VALIDATED"
    FINAL_CLOSURE_VALIDATED = "FINAL_CLOSURE_VALIDATED"
    FREEZE_SEAL_CREATED = "FREEZE_SEAL_CREATED"
    FINAL_SAFETY_AUDIT_PASSED = "FINAL_SAFETY_AUDIT_PASSED"
    ML_INPUT_CONTRACT_BUILT = "ML_INPUT_CONTRACT_BUILT"
    ML_KICKOFF_GATE_BUILT = "ML_KICKOFF_GATE_BUILT"
    ML_KICKOFF_GATE_PASSED = "ML_KICKOFF_GATE_PASSED"
    VALIDATED = "VALIDATED"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class RegimeFinalClosureDecision(str, Enum):
    VALIDATE_ARTIFACT_CHAIN = "VALIDATE_ARTIFACT_CHAIN"
    VALIDATE_FINAL_CLOSURE = "VALIDATE_FINAL_CLOSURE"
    CREATE_FREEZE_SEAL = "CREATE_FREEZE_SEAL"
    RUN_FINAL_SAFETY_AUDIT = "RUN_FINAL_SAFETY_AUDIT"
    BUILD_ML_INPUT_CONTRACT = "BUILD_ML_INPUT_CONTRACT"
    BUILD_ML_KICKOFF_GATE = "BUILD_ML_KICKOFF_GATE"
    REQUEST_RESEARCH_FREEZE_REFRESH = "REQUEST_RESEARCH_FREEZE_REFRESH"
    REQUEST_ARTIFACT_FIX = "REQUEST_ARTIFACT_FIX"
    REQUEST_SAFETY_FIX = "REQUEST_SAFETY_FIX"
    REQUEST_SCHEMA_FIX = "REQUEST_SCHEMA_FIX"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class RegimeArtifactChainKind(str, Enum):
    REGIME_FOUNDATION = "REGIME_FOUNDATION"
    REGIME_FEATURE_ENGINEERING = "REGIME_FEATURE_ENGINEERING"
    REGIME_LABELING = "REGIME_LABELING"
    REGIME_TRANSITION_ANALYTICS = "REGIME_TRANSITION_ANALYTICS"
    MARKET_BEHAVIOR_REPORTING = "MARKET_BEHAVIOR_REPORTING"
    REGIME_ALIGNMENT = "REGIME_ALIGNMENT"
    REGIME_CONTEXT_VALIDATION = "REGIME_CONTEXT_VALIDATION"
    REGIME_MONITORING = "REGIME_MONITORING"
    REGIME_RESEARCH_FREEZE = "REGIME_RESEARCH_FREEZE"
    FINAL_CLOSURE = "FINAL_CLOSURE"
    UNKNOWN = "UNKNOWN"

class RegimeArtifactChainValidationStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class RegimeFinalClosureRuleKind(str, Enum):
    RESEARCH_FREEZE_VALID = "RESEARCH_FREEZE_VALID"
    REQUIRED_ARTIFACT_CHAIN_COMPLETE = "REQUIRED_ARTIFACT_CHAIN_COMPLETE"
    REQUIRED_ARTIFACT_HASHES_VALID = "REQUIRED_ARTIFACT_HASHES_VALID"
    REQUIRED_ARTIFACTS_READ_ONLY = "REQUIRED_ARTIFACTS_READ_ONLY"
    SAFETY_BOUNDARY_VALID = "SAFETY_BOUNDARY_VALID"
    REPORT_QA_PASSED = "REPORT_QA_PASSED"
    FREEZE_PACKAGE_VALID = "FREEZE_PACKAGE_VALID"
    NO_SIGNAL_OUTPUT = "NO_SIGNAL_OUTPUT"
    NO_ORDER_OUTPUT = "NO_ORDER_OUTPUT"
    NO_PORTFOLIO_OUTPUT = "NO_PORTFOLIO_OUTPUT"
    NO_EXECUTION_OUTPUT = "NO_EXECUTION_OUTPUT"
    NO_MODEL_TRAINING = "NO_MODEL_TRAINING"
    NO_DEPLOYMENT = "NO_DEPLOYMENT"
    READY_FOR_PHASE136 = "READY_FOR_PHASE136"
    UNKNOWN = "UNKNOWN"

class RegimeFreezeSealStatus(str, Enum):
    SEALED = "SEALED"
    WARNING_SEALED = "WARNING_SEALED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    NOT_CREATED = "NOT_CREATED"
    UNKNOWN = "UNKNOWN"

class RegimeFreezeSealKind(str, Enum):
    REGIME_RESEARCH_FINAL_SEAL = "REGIME_RESEARCH_FINAL_SEAL"
    MARKET_BEHAVIOR_FINAL_SEAL = "MARKET_BEHAVIOR_FINAL_SEAL"
    SAFETY_BOUNDARY_SEAL = "SAFETY_BOUNDARY_SEAL"
    PHASE136_KICKOFF_SEAL = "PHASE136_KICKOFF_SEAL"
    COMBINED_FINAL_SEAL = "COMBINED_FINAL_SEAL"
    UNKNOWN = "UNKNOWN"

class MLKickoffReadinessStatus(str, Enum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class MLKickoffReadinessRuleKind(str, Enum):
    REGIME_FINAL_CLOSURE_VALID = "REGIME_FINAL_CLOSURE_VALID"
    FREEZE_SEAL_VALID = "FREEZE_SEAL_VALID"
    ML_INPUT_CONTRACT_VALID = "ML_INPUT_CONTRACT_VALID"
    NON_ACTIVATION_BOUNDARY_VALID = "NON_ACTIVATION_BOUNDARY_VALID"
    TRAINING_NOT_STARTED = "TRAINING_NOT_STARTED"
    PREDICTION_NOT_STARTED = "PREDICTION_NOT_STARTED"
    NO_SIGNAL_OUTPUT = "NO_SIGNAL_OUTPUT"
    NO_ORDER_OUTPUT = "NO_ORDER_OUTPUT"
    NO_PORTFOLIO_OUTPUT = "NO_PORTFOLIO_OUTPUT"
    NO_EXECUTION_OUTPUT = "NO_EXECUTION_OUTPUT"
    NO_BROKER = "NO_BROKER"
    NO_DEPLOYMENT = "NO_DEPLOYMENT"
    READY_FOR_PHASE136 = "READY_FOR_PHASE136"
    UNKNOWN = "UNKNOWN"

class MLInputContractArtifactKind(str, Enum):
    FROZEN_FEATURE_TABLE = "FROZEN_FEATURE_TABLE"
    FACTOR_TABLE = "FACTOR_TABLE"
    REGIME_FEATURE_TABLE = "REGIME_FEATURE_TABLE"
    REGIME_LABEL_TABLE = "REGIME_LABEL_TABLE"
    TRANSITION_DIAGNOSTICS = "TRANSITION_DIAGNOSTICS"
    MARKET_BEHAVIOR_PROFILE = "MARKET_BEHAVIOR_PROFILE"
    ALIGNMENT_COMPATIBILITY_RESULT = "ALIGNMENT_COMPATIBILITY_RESULT"
    CONTEXT_VALIDATION_RESULT = "CONTEXT_VALIDATION_RESULT"
    MONITORING_DRIFT_RESULT = "MONITORING_DRIFT_RESULT"
    RESEARCH_FREEZE_PACKAGE = "RESEARCH_FREEZE_PACKAGE"
    FINAL_CLOSURE_SEAL = "FINAL_CLOSURE_SEAL"
    UNKNOWN = "UNKNOWN"

class RegimeFinalClosureQuality(str, Enum):
    HIGH = "HIGH"
    ACCEPTABLE = "ACCEPTABLE"
    WARNING = "WARNING"
    LOW = "LOW"
    INVALID = "INVALID"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class RegimeFinalClosureRiskFlag(str, Enum):
    RESEARCH_FREEZE_REVIEW_MISSING = "RESEARCH_FREEZE_REVIEW_MISSING"
    RESEARCH_FREEZE_REVIEW_INVALID = "RESEARCH_FREEZE_REVIEW_INVALID"
    PHASE134_NOT_READY = "PHASE134_NOT_READY"
    REQUIRED_ARTIFACT_MISSING = "REQUIRED_ARTIFACT_MISSING"
    ARTIFACT_CHAIN_INCOMPLETE = "ARTIFACT_CHAIN_INCOMPLETE"
    ARTIFACT_HASH_INVALID = "ARTIFACT_HASH_INVALID"
    FREEZE_PACKAGE_INVALID = "FREEZE_PACKAGE_INVALID"
    FREEZE_SEAL_INVALID = "FREEZE_SEAL_INVALID"
    FINAL_SAFETY_AUDIT_FAILED = "FINAL_SAFETY_AUDIT_FAILED"
    ML_INPUT_CONTRACT_INVALID = "ML_INPUT_CONTRACT_INVALID"
    ML_KICKOFF_GATE_FAILED = "ML_KICKOFF_GATE_FAILED"
    MODEL_TRAINING_ATTEMPTED = "MODEL_TRAINING_ATTEMPTED"
    MODEL_PREDICTION_RISK = "MODEL_PREDICTION_RISK"
    HEAVY_ML_DEPENDENCY_RISK = "HEAVY_ML_DEPENDENCY_RISK"
    FORBIDDEN_FINAL_CLOSURE_COLUMN = "FORBIDDEN_FINAL_CLOSURE_COLUMN"
    TRADE_SIGNAL_COLUMN_RISK = "TRADE_SIGNAL_COLUMN_RISK"
    ORDER_DECISION_COLUMN_RISK = "ORDER_DECISION_COLUMN_RISK"
    PORTFOLIO_WEIGHT_COLUMN_RISK = "PORTFOLIO_WEIGHT_COLUMN_RISK"
    BROKER_COLUMN_RISK = "BROKER_COLUMN_RISK"
    PAPER_MUTATION_COLUMN_RISK = "PAPER_MUTATION_COLUMN_RISK"
    DEPLOYMENT_RISK = "DEPLOYMENT_RISK"
    SECRET_LEAK_RISK = "SECRET_LEAK_RISK"
    INVESTMENT_ADVICE_LANGUAGE_RISK = "INVESTMENT_ADVICE_LANGUAGE_RISK"
    NETWORK_FETCH_ATTEMPTED = "NETWORK_FETCH_ATTEMPTED"
    NETWORK_DEFAULT_ENABLED_RISK = "NETWORK_DEFAULT_ENABLED_RISK"
    PAID_API_RISK = "PAID_API_RISK"
    SCRAPING_RISK = "SCRAPING_RISK"
    HTML_PARSE_RISK = "HTML_PARSE_RISK"
    BROKER_RISK = "BROKER_RISK"
    ORDER_RISK = "ORDER_RISK"
    PAPER_MUTATION_RISK = "PAPER_MUTATION_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    DASHBOARD_RISK = "DASHBOARD_RISK"
    DAEMON_RISK = "DAEMON_RISK"
    SCHEDULER_RISK = "SCHEDULER_RISK"
    UNKNOWN = "UNKNOWN"

class RegimeFinalClosureReportType(str, Enum):
    ARTIFACT_CHAIN_VALIDATION_REPORT = "ARTIFACT_CHAIN_VALIDATION_REPORT"
    FINAL_SAFETY_AUDIT_REPORT = "FINAL_SAFETY_AUDIT_REPORT"
    FREEZE_SEAL_REPORT = "FREEZE_SEAL_REPORT"
    ML_KICKOFF_READINESS_REPORT = "ML_KICKOFF_READINESS_REPORT"
    FULL_PHASE135_REVIEW = "FULL_PHASE135_REVIEW"
"""
    if "RegimeFinalClosureStatus" not in content:
        content += new_enums

    if "REGIME_FINAL_CLOSURE_REPORT" not in content:
        content = content.replace(
            'class NotificationType(str, Enum):\n',
            'class NotificationType(str, Enum):\n    REGIME_FINAL_CLOSURE_REPORT = "REGIME_FINAL_CLOSURE_REPORT"\n    REGIME_FREEZE_SEAL_WARNING = "REGIME_FREEZE_SEAL_WARNING"\n    ML_KICKOFF_GATE_WARNING = "ML_KICKOFF_GATE_WARNING"\n'
        )
    if "REGIME_FINAL_CLOSURE_BLOCKED" not in content:
        content = content.replace(
            'class AlertType(str, Enum):\n',
            'class AlertType(str, Enum):\n    REGIME_FINAL_CLOSURE_BLOCKED = "REGIME_FINAL_CLOSURE_BLOCKED"\n    REGIME_FREEZE_SEAL_BLOCKED = "REGIME_FREEZE_SEAL_BLOCKED"\n    ML_KICKOFF_GATE_BLOCKED = "ML_KICKOFF_GATE_BLOCKED"\n'
        )

    with open(file_path, "w") as f:
        f.write(content)

if __name__ == "__main__":
    patch_enums()
