import re

with open('usa_signal_bot/core/enums.py', 'r') as f:
    content = f.read()

new_enums = """

class CalibrationDiagnosticsStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    MODEL_COMPARISON_INGESTED = "MODEL_COMPARISON_INGESTED"
    COMPARISON_ARTIFACTS_LOADED = "COMPARISON_ARTIFACTS_LOADED"
    CALIBRATION_INPUTS_RESOLVED = "CALIBRATION_INPUTS_RESOLVED"
    RELIABILITY_BINS_BUILT = "RELIABILITY_BINS_BUILT"
    CALIBRATION_METRICS_BUILT = "CALIBRATION_METRICS_BUILT"
    BRIER_DECOMPOSITION_BUILT = "BRIER_DECOMPOSITION_BUILT"
    SCORE_DISTRIBUTION_BUILT = "SCORE_DISTRIBUTION_BUILT"
    CLASS_BALANCE_BUILT = "CLASS_BALANCE_BUILT"
    POST_TRAINING_VALIDATION_BUILT = "POST_TRAINING_VALIDATION_BUILT"
    CALIBRATION_GOVERNANCE_BUILT = "CALIBRATION_GOVERNANCE_BUILT"
    MODEL_CARDS_UPDATED = "MODEL_CARDS_UPDATED"
    READINESS_GATE_BUILT = "READINESS_GATE_BUILT"
    READINESS_GATE_PASSED = "READINESS_GATE_PASSED"
    VALIDATED = "VALIDATED"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class CalibrationDiagnosticsDecision(str, Enum):
    LOAD_COMPARISON_ARTIFACTS = "LOAD_COMPARISON_ARTIFACTS"
    RESOLVE_CALIBRATION_INPUTS = "RESOLVE_CALIBRATION_INPUTS"
    BUILD_RELIABILITY_BINS = "BUILD_RELIABILITY_BINS"
    CALCULATE_CALIBRATION_METRICS = "CALCULATE_CALIBRATION_METRICS"
    BUILD_BRIER_DECOMPOSITION = "BUILD_BRIER_DECOMPOSITION"
    BUILD_SCORE_DISTRIBUTION = "BUILD_SCORE_DISTRIBUTION"
    BUILD_CLASS_BALANCE = "BUILD_CLASS_BALANCE"
    RUN_POST_TRAINING_VALIDATION = "RUN_POST_TRAINING_VALIDATION"
    BUILD_CALIBRATION_GOVERNANCE = "BUILD_CALIBRATION_GOVERNANCE"
    UPDATE_MODEL_CARDS = "UPDATE_MODEL_CARDS"
    BUILD_READINESS_GATE = "BUILD_READINESS_GATE"
    REQUEST_MODEL_COMPARISON_REFRESH = "REQUEST_MODEL_COMPARISON_REFRESH"
    REQUEST_PREDICTION_FIX = "REQUEST_PREDICTION_FIX"
    REQUEST_RELIABILITY_FIX = "REQUEST_RELIABILITY_FIX"
    REQUEST_GOVERNANCE_FIX = "REQUEST_GOVERNANCE_FIX"
    REQUEST_SAFETY_FIX = "REQUEST_SAFETY_FIX"
    REQUEST_SCHEMA_FIX = "REQUEST_SCHEMA_FIX"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class CalibrationInputKind(str, Enum):
    OFFLINE_PROBABILITY_OUTPUT = "OFFLINE_PROBABILITY_OUTPUT"
    OFFLINE_SCORE_OUTPUT = "OFFLINE_SCORE_OUTPUT"
    OFFLINE_CLASS_LABEL_OUTPUT = "OFFLINE_CLASS_LABEL_OUTPUT"
    OFFLINE_REGRESSION_OUTPUT = "OFFLINE_REGRESSION_OUTPUT"
    TRUE_CLASS_LABEL = "TRUE_CLASS_LABEL"
    TRUE_REGRESSION_TARGET = "TRUE_REGRESSION_TARGET"
    SPLIT_ASSIGNMENT = "SPLIT_ASSIGNMENT"
    MODEL_RANKING_REFERENCE = "MODEL_RANKING_REFERENCE"
    CANDIDATE_SHORTLIST_REFERENCE = "CANDIDATE_SHORTLIST_REFERENCE"
    UNKNOWN = "UNKNOWN"

class ProbabilityReliabilityKind(str, Enum):
    BINARY_CLASSIFICATION = "BINARY_CLASSIFICATION"
    MULTICLASS_CLASSIFICATION = "MULTICLASS_CLASSIFICATION"
    SCORE_BASED_RELIABILITY = "SCORE_BASED_RELIABILITY"
    REGRESSION_RESIDUAL_RELIABILITY = "REGRESSION_RESIDUAL_RELIABILITY"
    CLASSIFICATION_LABEL_RELIABILITY = "CLASSIFICATION_LABEL_RELIABILITY"
    UNKNOWN = "UNKNOWN"

class ReliabilityBinStrategy(str, Enum):
    EQUAL_WIDTH = "EQUAL_WIDTH"
    EQUAL_FREQUENCY = "EQUAL_FREQUENCY"
    FIXED_10_BIN = "FIXED_10_BIN"
    CUSTOM = "CUSTOM"
    UNKNOWN = "UNKNOWN"

class CalibrationMetricKind(str, Enum):
    EXPECTED_CALIBRATION_ERROR = "EXPECTED_CALIBRATION_ERROR"
    MAXIMUM_CALIBRATION_ERROR = "MAXIMUM_CALIBRATION_ERROR"
    AVERAGE_CONFIDENCE = "AVERAGE_CONFIDENCE"
    AVERAGE_ACCURACY = "AVERAGE_ACCURACY"
    BRIER_SCORE = "BRIER_SCORE"
    BRIER_RELIABILITY = "BRIER_RELIABILITY"
    BRIER_RESOLUTION = "BRIER_RESOLUTION"
    BRIER_UNCERTAINTY = "BRIER_UNCERTAINTY"
    LOG_LOSS_APPROXIMATION = "LOG_LOSS_APPROXIMATION"
    CLASS_BALANCE_RATIO = "CLASS_BALANCE_RATIO"
    SCORE_COVERAGE = "SCORE_COVERAGE"
    UNKNOWN = "UNKNOWN"

class CalibrationDiagnosticSeverity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    BLOCKING = "BLOCKING"
    UNKNOWN = "UNKNOWN"

class CalibrationDiagnosticStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class PostTrainingValidationRuleKind(str, Enum):
    MODEL_REGISTRY_CONSISTENT = "MODEL_REGISTRY_CONSISTENT"
    CANDIDATE_SHORTLIST_CONSISTENT = "CANDIDATE_SHORTLIST_CONSISTENT"
    OFFLINE_PREDICTIONS_AVAILABLE = "OFFLINE_PREDICTIONS_AVAILABLE"
    PROBABILITY_OUTPUTS_VALID = "PROBABILITY_OUTPUTS_VALID"
    SCORE_OUTPUTS_VALID = "SCORE_OUTPUTS_VALID"
    TRUE_LABELS_AVAILABLE = "TRUE_LABELS_AVAILABLE"
    SPLIT_ASSIGNMENT_CONSISTENT = "SPLIT_ASSIGNMENT_CONSISTENT"
    NO_FORBIDDEN_OUTPUT_FIELDS = "NO_FORBIDDEN_OUTPUT_FIELDS"
    NO_TRADE_METRIC_USED = "NO_TRADE_METRIC_USED"
    NO_SIGNAL_OUTPUT = "NO_SIGNAL_OUTPUT"
    NO_ORDER_OUTPUT = "NO_ORDER_OUTPUT"
    NO_PORTFOLIO_OUTPUT = "NO_PORTFOLIO_OUTPUT"
    NO_LIVE_INFERENCE = "NO_LIVE_INFERENCE"
    NO_CALIBRATION_FITTING = "NO_CALIBRATION_FITTING"
    NO_DEPLOYMENT = "NO_DEPLOYMENT"
    UNKNOWN = "UNKNOWN"

class CalibrationGovernanceRuleKind(str, Enum):
    CALIBRATION_DIAGNOSTICS_RESEARCH_ONLY = "CALIBRATION_DIAGNOSTICS_RESEARCH_ONLY"
    NO_CALIBRATED_MODEL_CREATED = "NO_CALIBRATED_MODEL_CREATED"
    NO_THRESHOLD_OPTIMIZATION = "NO_THRESHOLD_OPTIMIZATION"
    NO_TRADE_SIGNAL_OUTPUT = "NO_TRADE_SIGNAL_OUTPUT"
    NO_ORDER_DECISION_OUTPUT = "NO_ORDER_DECISION_OUTPUT"
    NO_PORTFOLIO_WEIGHT_OUTPUT = "NO_PORTFOLIO_WEIGHT_OUTPUT"
    NO_STRATEGY_ACTIVATION = "NO_STRATEGY_ACTIVATION"
    NO_BROKER_EXECUTION = "NO_BROKER_EXECUTION"
    NO_PAPER_MUTATION = "NO_PAPER_MUTATION"
    NO_DEPLOYMENT = "NO_DEPLOYMENT"
    PHASE142_READY = "PHASE142_READY"
    UNKNOWN = "UNKNOWN"

class CalibrationGovernanceStatus(str, Enum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class CalibrationReadinessStatus(str, Enum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class CalibrationReadinessRuleKind(str, Enum):
    MODEL_COMPARISON_VALID = "MODEL_COMPARISON_VALID"
    CANDIDATE_SHORTLIST_VALID = "CANDIDATE_SHORTLIST_VALID"
    CALIBRATION_INPUTS_VALID = "CALIBRATION_INPUTS_VALID"
    RELIABILITY_BINS_VALID = "RELIABILITY_BINS_VALID"
    CALIBRATION_METRICS_VALID = "CALIBRATION_METRICS_VALID"
    BRIER_DECOMPOSITION_VALID = "BRIER_DECOMPOSITION_VALID"
    SCORE_DISTRIBUTION_VALID = "SCORE_DISTRIBUTION_VALID"
    CLASS_BALANCE_VALID = "CLASS_BALANCE_VALID"
    POST_TRAINING_VALIDATION_VALID = "POST_TRAINING_VALIDATION_VALID"
    CALIBRATION_GOVERNANCE_VALID = "CALIBRATION_GOVERNANCE_VALID"
    MODEL_CARDS_UPDATED = "MODEL_CARDS_UPDATED"
    NO_SIGNAL_OUTPUT = "NO_SIGNAL_OUTPUT"
    NO_ORDER_OUTPUT = "NO_ORDER_OUTPUT"
    NO_PORTFOLIO_OUTPUT = "NO_PORTFOLIO_OUTPUT"
    NO_LIVE_INFERENCE = "NO_LIVE_INFERENCE"
    NO_CALIBRATION_FITTING = "NO_CALIBRATION_FITTING"
    NO_DEPLOYMENT = "NO_DEPLOYMENT"
    READY_FOR_PHASE142 = "READY_FOR_PHASE142"
    UNKNOWN = "UNKNOWN"

class CalibrationDiagnosticsQuality(str, Enum):
    HIGH = "HIGH"
    ACCEPTABLE = "ACCEPTABLE"
    WARNING = "WARNING"
    LOW = "LOW"
    INVALID = "INVALID"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class CalibrationDiagnosticsRiskFlag(str, Enum):
    MODEL_COMPARISON_REVIEW_MISSING = "MODEL_COMPARISON_REVIEW_MISSING"
    MODEL_COMPARISON_REVIEW_INVALID = "MODEL_COMPARISON_REVIEW_INVALID"
    PHASE140_NOT_READY = "PHASE140_NOT_READY"
    CANDIDATE_SHORTLIST_MISSING = "CANDIDATE_SHORTLIST_MISSING"
    CANDIDATE_SHORTLIST_INVALID = "CANDIDATE_SHORTLIST_INVALID"
    CALIBRATION_PREPARATION_MISSING = "CALIBRATION_PREPARATION_MISSING"
    SELECTION_GOVERNANCE_FAILED = "SELECTION_GOVERNANCE_FAILED"
    OFFLINE_PREDICTION_ARTIFACT_MISSING = "OFFLINE_PREDICTION_ARTIFACT_MISSING"
    PROBABILITY_OUTPUT_MISSING = "PROBABILITY_OUTPUT_MISSING"
    SCORE_OUTPUT_MISSING = "SCORE_OUTPUT_MISSING"
    TRUE_LABEL_MISSING = "TRUE_LABEL_MISSING"
    RELIABILITY_BINNING_INVALID = "RELIABILITY_BINNING_INVALID"
    CALIBRATION_METRIC_INVALID = "CALIBRATION_METRIC_INVALID"
    BRIER_DECOMPOSITION_INVALID = "BRIER_DECOMPOSITION_INVALID"
    SCORE_DISTRIBUTION_INVALID = "SCORE_DISTRIBUTION_INVALID"
    CLASS_BALANCE_INVALID = "CLASS_BALANCE_INVALID"
    POST_TRAINING_VALIDATION_FAILED = "POST_TRAINING_VALIDATION_FAILED"
    CALIBRATION_GOVERNANCE_FAILED = "CALIBRATION_GOVERNANCE_FAILED"
    CALIBRATION_FITTING_ATTEMPTED = "CALIBRATION_FITTING_ATTEMPTED"
    CALIBRATED_MODEL_CREATED = "CALIBRATED_MODEL_CREATED"
    THRESHOLD_OPTIMIZATION_ATTEMPTED = "THRESHOLD_OPTIMIZATION_ATTEMPTED"
    LIVE_INFERENCE_RISK = "LIVE_INFERENCE_RISK"
    HEAVY_ML_DEPENDENCY_RISK = "HEAVY_ML_DEPENDENCY_RISK"
    FORBIDDEN_CALIBRATION_DIAGNOSTICS_COLUMN = "FORBIDDEN_CALIBRATION_DIAGNOSTICS_COLUMN"
    TRADE_SIGNAL_COLUMN_RISK = "TRADE_SIGNAL_COLUMN_RISK"
    ORDER_DECISION_COLUMN_RISK = "ORDER_DECISION_COLUMN_RISK"
    PORTFOLIO_WEIGHT_COLUMN_RISK = "PORTFOLIO_WEIGHT_COLUMN_RISK"
    BROKER_COLUMN_RISK = "BROKER_COLUMN_RISK"
    PAPER_MUTATION_COLUMN_RISK = "PAPER_MUTATION_COLUMN_RISK"
    DEPLOYMENT_RISK = "DEPLOYMENT_RISK"
    SECRET_LEAK_RISK = "SECRET_LEAK_RISK"
    INVESTMENT_ADVICE_LANGUAGE_RISK = "INVESTMENT_ADVICE_LANGUAGE_RISK"
    NETWORK_FETCH_ATTEMPTED = "NETWORK_FETCH_ATTEMPTED"
    NETWORK_DEFAULT_ENABLED_RISK = "NETWORK_DEFAULT_ENABLED_RISK"
    PAID_API_RISK = "PAID_API_RISK"
    SCRAPING_RISK = "SCRAPING_RISK"
    HTML_PARSE_RISK = "HTML_PARSE_RISK"
    BROKER_RISK = "BROKER_RISK"
    ORDER_RISK = "ORDER_RISK"
    PAPER_MUTATION_RISK = "PAPER_MUTATION_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    DASHBOARD_RISK = "DASHBOARD_RISK"
    DAEMON_RISK = "DAEMON_RISK"
    SCHEDULER_RISK = "SCHEDULER_RISK"
    UNKNOWN = "UNKNOWN"

class CalibrationDiagnosticsReportType(str, Enum):
    PROBABILITY_RELIABILITY_REPORT = "PROBABILITY_RELIABILITY_REPORT"
    CALIBRATION_METRIC_REPORT = "CALIBRATION_METRIC_REPORT"
    POST_TRAINING_VALIDATION_REPORT = "POST_TRAINING_VALIDATION_REPORT"
    CALIBRATION_GOVERNANCE_REPORT = "CALIBRATION_GOVERNANCE_REPORT"
    FULL_PHASE141_REVIEW = "FULL_PHASE141_REVIEW"
"""

if "CalibrationDiagnosticsStatus" not in content:
    content += new_enums

content = re.sub(
    r'(class NotificationType\(str, Enum\):)',
    r'\1\n    CALIBRATION_DIAGNOSTICS_REPORT = "CALIBRATION_DIAGNOSTICS_REPORT"\n    PROBABILITY_RELIABILITY_WARNING = "PROBABILITY_RELIABILITY_WARNING"\n    POST_TRAINING_VALIDATION_WARNING = "POST_TRAINING_VALIDATION_WARNING"',
    content
)

content = re.sub(
    r'(class AlertType\(str, Enum\):)',
    r'\1\n    CALIBRATION_DIAGNOSTICS_BLOCKED = "CALIBRATION_DIAGNOSTICS_BLOCKED"\n    PROBABILITY_RELIABILITY_BLOCKED = "PROBABILITY_RELIABILITY_BLOCKED"\n    POST_TRAINING_VALIDATION_BLOCKED = "POST_TRAINING_VALIDATION_BLOCKED"',
    content
)

with open('usa_signal_bot/core/enums.py', 'w') as f:
    f.write(content)
