import re

file_path = "usa_signal_bot/core/enums.py"

with open(file_path, "r") as f:
    content = f.read()

new_enums = """
class PortfolioConstructionMode(str, Enum):
    EQUAL_WEIGHT = "EQUAL_WEIGHT"
    SCORE_WEIGHTED = "SCORE_WEIGHTED"
    RISK_WEIGHTED = "RISK_WEIGHTED"
    CONFIDENCE_WEIGHTED = "CONFIDENCE_WEIGHTED"
    SIZE_RESULT_WEIGHTED = "SIZE_RESULT_WEIGHTED"
    HYBRID = "HYBRID"
    DISABLED = "DISABLED"
    UNKNOWN = "UNKNOWN"

class PortfolioAllocationStatus(str, Enum):
    APPROVED = "APPROVED"
    REDUCED = "REDUCED"
    CAPPED = "CAPPED"
    REBALANCED = "REBALANCED"
    SUPPRESSED = "SUPPRESSED"
    BLOCKED = "BLOCKED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class ExposureType(str, Enum):
    GROSS = "GROSS"
    NET = "NET"
    LONG = "LONG"
    SHORT = "SHORT"
    SYMBOL = "SYMBOL"
    STRATEGY = "STRATEGY"
    SECTOR = "SECTOR"
    CLUSTER = "CLUSTER"
    REGIME = "REGIME"
    LIQUIDITY_BUCKET = "LIQUIDITY_BUCKET"
    COST_BUCKET = "COST_BUCKET"
    UNKNOWN = "UNKNOWN"

class SectorClusterSource(str, Enum):
    MANUAL_REGISTRY = "MANUAL_REGISTRY"
    LOCAL_CONFIG = "LOCAL_CONFIG"
    SYMBOL_PREFIX_HEURISTIC = "SYMBOL_PREFIX_HEURISTIC"
    ETF_PROXY_HEURISTIC = "ETF_PROXY_HEURISTIC"
    UNKNOWN = "UNKNOWN"

class ConcentrationRiskLevel(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class PortfolioGuardDecision(str, Enum):
    CLEAR = "CLEAR"
    WARNING = "WARNING"
    REDUCE = "REDUCE"
    CAP = "CAP"
    SUPPRESS = "SUPPRESS"
    BLOCK = "BLOCK"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class CorrelationProxyBucket(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class PortfolioConflictType(str, Enum):
    SYMBOL_OVERLAP = "SYMBOL_OVERLAP"
    SECTOR_OVEREXPOSURE = "SECTOR_OVEREXPOSURE"
    CLUSTER_OVEREXPOSURE = "CLUSTER_OVEREXPOSURE"
    STRATEGY_OVEREXPOSURE = "STRATEGY_OVEREXPOSURE"
    SIDE_CONFLICT = "SIDE_CONFLICT"
    REGIME_CONCENTRATION = "REGIME_CONCENTRATION"
    LIQUIDITY_CONCENTRATION = "LIQUIDITY_CONCENTRATION"
    COST_CONCENTRATION = "COST_CONCENTRATION"
    RISK_BUDGET_EXCEEDED = "RISK_BUDGET_EXCEEDED"
    UNKNOWN = "UNKNOWN"

class PortfolioConstructionReportType(str, Enum):
    EXPOSURE_SUMMARY = "EXPOSURE_SUMMARY"
    CONCENTRATION_REVIEW = "CONCENTRATION_REVIEW"
    ALLOCATION_PLAN = "ALLOCATION_PLAN"
    PORTFOLIO_BALANCE_REVIEW = "PORTFOLIO_BALANCE_REVIEW"
    FULL_PORTFOLIO_CONSTRUCTION_REVIEW = "FULL_PORTFOLIO_CONSTRUCTION_REVIEW"
"""

if "PortfolioConstructionMode" not in content:
    content += new_enums

    # Update NotificationType
    content = re.sub(
        r'(class NotificationType\(str, Enum\):[^}]*?)(UNKNOWN = "UNKNOWN")',
        r'\1PORTFOLIO_CONSTRUCTION_REPORT = "PORTFOLIO_CONSTRUCTION_REPORT"\n    EXPOSURE_LIMIT_WARNING = "EXPOSURE_LIMIT_WARNING"\n    CONCENTRATION_RISK_WARNING = "CONCENTRATION_RISK_WARNING"\n    \2',
        content
    )

    # Update AlertType
    content = re.sub(
        r'(class AlertType\(str, Enum\):[^}]*?)(UNKNOWN = "UNKNOWN")',
        r'\1PORTFOLIO_EXPOSURE_LIMIT_EXCEEDED = "PORTFOLIO_EXPOSURE_LIMIT_EXCEEDED"\n    PORTFOLIO_CONCENTRATION_HIGH = "PORTFOLIO_CONCENTRATION_HIGH"\n    PORTFOLIO_ALLOCATION_BLOCKED = "PORTFOLIO_ALLOCATION_BLOCKED"\n    \2',
        content
    )

    with open(file_path, "w") as f:
        f.write(content)
    print("Updated enums.py")
else:
    print("Enums already exist")
