import os
from pathlib import Path
import re

def update_enums():
    path = Path('usa_signal_bot/core/enums.py')
    content = path.read_text()

    enums_to_add = """
class ShadowLaunchReplayStatus(str, Enum):
    DRAFT = "DRAFT"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED_ALL_BLOCKED = "COMPLETED_ALL_BLOCKED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class ShadowLaunchReplayOutcome(str, Enum):
    ALL_SHADOW_ATTEMPTS_BLOCKED = "ALL_SHADOW_ATTEMPTS_BLOCKED"
    SHADOW_ATTEMPT_ALLOWED = "SHADOW_ATTEMPT_ALLOWED"
    BLOCKER_RULES_INCOMPLETE = "BLOCKER_RULES_INCOMPLETE"
    BLOCKER_EVENTS_MISSING = "BLOCKER_EVENTS_MISSING"
    REPLAY_FAILED = "REPLAY_FAILED"
    BLOCKED = "BLOCKED"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class ShadowLaunchReplayDecision(str, Enum):
    DENY_SHADOW_LAUNCH = "DENY_SHADOW_LAUNCH"
    DENY_PAPER_MODE_LAUNCH = "DENY_PAPER_MODE_LAUNCH"
    DENY_PAPER_ADMISSION = "DENY_PAPER_ADMISSION"
    DENY_PAPER_ORDER = "DENY_PAPER_ORDER"
    DENY_PAPER_STATE_COMMIT = "DENY_PAPER_STATE_COMMIT"
    DENY_BROKER_SEND = "DENY_BROKER_SEND"
    DENY_CONFIG_PATCH = "DENY_CONFIG_PATCH"
    DENY_TELEGRAM_REAL_SEND = "DENY_TELEGRAM_REAL_SEND"
    BLOCK = "BLOCK"
    UNKNOWN = "UNKNOWN"

class BoardEvidenceFreezeStatus(str, Enum):
    DRAFT = "DRAFT"
    FROZEN = "FROZEN"
    VALIDATED = "VALIDATED"
    PARTIAL = "PARTIAL"
    STALE = "STALE"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class BoardEvidenceFreezeDecision(str, Enum):
    FREEZE_BOARD_EVIDENCE = "FREEZE_BOARD_EVIDENCE"
    REQUEST_BOARD_DOSSIER_REFRESH = "REQUEST_BOARD_DOSSIER_REFRESH"
    REQUEST_ACCEPTANCE_SEAL_REFRESH = "REQUEST_ACCEPTANCE_SEAL_REFRESH"
    REQUEST_SHADOW_REPLAY_REFRESH = "REQUEST_SHADOW_REPLAY_REFRESH"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    REJECT = "REJECT"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class PaperModeDryAdmissionGateStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    VALIDATED_DRY_ADMISSION_SAFE = "VALIDATED_DRY_ADMISSION_SAFE"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    BLOCKED = "BLOCKED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class PaperModeDryAdmissionGateDecision(str, Enum):
    PASS_TO_DRY_ADMISSION_GATE_DOSSIER = "PASS_TO_DRY_ADMISSION_GATE_DOSSIER"
    REQUEST_SHADOW_REPLAY = "REQUEST_SHADOW_REPLAY"
    REQUEST_BOARD_EVIDENCE_FREEZE = "REQUEST_BOARD_EVIDENCE_FREEZE"
    REQUEST_BOARD_DOSSIER_REFRESH = "REQUEST_BOARD_DOSSIER_REFRESH"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    REJECT = "REJECT"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class DryAdmissionGateRuleStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class DryAdmissionGateAssertionStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class DryAdmissionGateRiskFlag(str, Enum):
    REAL_ORDER_RISK = "REAL_ORDER_RISK"
    PAPER_ORDER_RISK = "PAPER_ORDER_RISK"
    BROKER_ORDER_RISK = "BROKER_ORDER_RISK"
    PAPER_STATE_MUTATION_RISK = "PAPER_STATE_MUTATION_RISK"
    PAPER_POSITION_MUTATION_RISK = "PAPER_POSITION_MUTATION_RISK"
    PAPER_PORTFOLIO_MUTATION_RISK = "PAPER_PORTFOLIO_MUTATION_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    PRODUCTION_CONFIG_WRITE_RISK = "PRODUCTION_CONFIG_WRITE_RISK"
    ACTIVE_PAPER_ENABLE_RISK = "ACTIVE_PAPER_ENABLE_RISK"
    PAPER_ADMISSION_RISK = "PAPER_ADMISSION_RISK"
    SHADOW_LAUNCH_RISK = "SHADOW_LAUNCH_RISK"
    PAPER_MODE_LAUNCH_RISK = "PAPER_MODE_LAUNCH_RISK"
    ACTIVATION_ALLOWED_RISK = "ACTIVATION_ALLOWED_RISK"
    ADMISSION_ALLOWED_RISK = "ADMISSION_ALLOWED_RISK"
    TRANSITION_ALLOWED_RISK = "TRANSITION_ALLOWED_RISK"
    ORDER_CREATED_RISK = "ORDER_CREATED_RISK"
    MUTATION_DETECTED_RISK = "MUTATION_DETECTED_RISK"
    SHADOW_REPLAY_FAILED = "SHADOW_REPLAY_FAILED"
    SHADOW_ATTEMPT_NOT_BLOCKED = "SHADOW_ATTEMPT_NOT_BLOCKED"
    BOARD_EVIDENCE_FREEZE_FAILED = "BOARD_EVIDENCE_FREEZE_FAILED"
    BOARD_EVIDENCE_FREEZE_STALE = "BOARD_EVIDENCE_FREEZE_STALE"
    ACCEPTANCE_BOARD_SEAL_FAILED = "ACCEPTANCE_BOARD_SEAL_FAILED"
    DRY_ADMISSION_GATE_INVALID = "DRY_ADMISSION_GATE_INVALID"
    DRY_ADMISSION_RULE_FAILED = "DRY_ADMISSION_RULE_FAILED"
    DRY_ADMISSION_ASSERTION_FAILED = "DRY_ADMISSION_ASSERTION_FAILED"
    SECRET_RISK = "SECRET_RISK"
    UNKNOWN = "UNKNOWN"

class DryAdmissionGateReportType(str, Enum):
    SHADOW_LAUNCH_REPLAY_REPORT = "SHADOW_LAUNCH_REPLAY_REPORT"
    BOARD_EVIDENCE_FREEZE_REPORT = "BOARD_EVIDENCE_FREEZE_REPORT"
    FINAL_DRY_ADMISSION_GATE_REPORT = "FINAL_DRY_ADMISSION_GATE_REPORT"
    SAFETY_REVIEW = "SAFETY_REVIEW"
    FULL_DRY_ADMISSION_GATE_REVIEW = "FULL_DRY_ADMISSION_GATE_REVIEW"

"""

    if "ShadowLaunchReplayStatus" not in content:
        content += "\n" + enums_to_add

    # Update NotificationType
    nt_match = re.search(r'class NotificationType\(str, Enum\):(.*?)(\n\w|\Z)', content, re.DOTALL)
    if nt_match and "DRY_ADMISSION_GATE_REPORT" not in nt_match.group(1):
        insertion = "    DRY_ADMISSION_GATE_REPORT = \"DRY_ADMISSION_GATE_REPORT\"\n    SHADOW_LAUNCH_REPLAY_WARNING = \"SHADOW_LAUNCH_REPLAY_WARNING\"\n    BOARD_EVIDENCE_FREEZE_WARNING = \"BOARD_EVIDENCE_FREEZE_WARNING\"\n"
        content = content[:nt_match.end(1)] + insertion + content[nt_match.end(1):]

    # Update AlertType
    at_match = re.search(r'class AlertType\(str, Enum\):(.*?)(\n\w|\Z)', content, re.DOTALL)
    if at_match and "DRY_ADMISSION_GATE_BLOCKED" not in at_match.group(1):
        insertion = "    DRY_ADMISSION_GATE_BLOCKED = \"DRY_ADMISSION_GATE_BLOCKED\"\n    SHADOW_LAUNCH_REPLAY_BLOCKED = \"SHADOW_LAUNCH_REPLAY_BLOCKED\"\n    BOARD_EVIDENCE_FREEZE_BLOCKED = \"BOARD_EVIDENCE_FREEZE_BLOCKED\"\n"
        content = content[:at_match.end(1)] + insertion + content[at_match.end(1):]

    path.write_text(content)

update_enums()
