from usa_signal_bot.regime_classification.freeze_preparation.monitoring_validation_runner import run_monitoring_validation
from usa_signal_bot.regime_classification.freeze_preparation.phase134_models import RegimeMonitoringIngestionResult

def test_run_monitoring_validation():
    ing = RegimeMonitoringIngestionResult(
        ingestion_id="i1",
        created_at_utc="",
        source_path=None,
        source_review_id="rev1",
        source_context_id="ctx1",
        available=True,
        context_validation_ingested=True,
        artifacts_loaded=True,
        baseline_built=True,
        snapshot_built=True,
        drift_tracked=True,
        degradation_diagnostics_built=True,
        readiness_gate_built=True,
        readiness_gate_passed=True,
        ready_for_phase134=True,
        metadata_only=True,
        research_data_only=True,
        activation_allowed=False,
        strategy_activation_allowed=False,
        deployment_allowed=False,
        active_paper_enabled=False,
        broker_execution_enabled=False,
        order_creation_enabled=False,
        paper_state_mutation_enabled=False,
        telegram_real_send_enabled=False,
        scraping_enabled=False,
        html_parse_enabled=False,
        paid_api_enabled=False,
        dashboard_enabled=False,
        network_default_enabled=False,
        model_training_used=False,
        model_prediction_used=False,
        heavy_ml_dependency_used=False,
        produces_trade_signal=False,
        produces_order_decision=False,
        produces_portfolio_weights=False,
        investment_advice=False,
        network_used=False,
        paid_api_used=False,
        scraping_used=False,
        html_parsing_used=False,
        broker_used=False,
        order_created=False,
        paper_state_mutated=False,
        telegram_real_sent=False,
        dashboard_started=False,
        daemon_started=False,
        scheduler_enabled=False,
        valid_for_phase134=True,
        risk_flags=[],
        warnings=[],
        errors=[],
        metadata={}
    )
    res = run_monitoring_validation(ing, {"k":"v"}, {"k":"v"}, {"k":"v"}, [{"k":"v"}], [{"k":"v"}], {"ready":True})
    assert res.validation_passed is True
