import pytest
from usa_signal_bot.ml_research.ensemble_scaffolding.phase142_models import (
    CalibrationDiagnosticsIngestionResult,
    EnsembleCandidateReference,
    BlendCoefficientPlan,
    create_calibration_diagnostics_ingestion_id,
    validate_calibration_diagnostics_ingestion_result,
    validate_blend_coefficient_plan
)

def test_calibration_diagnostics_ingestion_result_defaults():
    res = CalibrationDiagnosticsIngestionResult(
        ingestion_id="id1",
        created_at_utc="2023-01-01T00:00:00Z",
        source_path=None,
        source_review_id=None,
        source_context_id=None,
        available=True,
        model_comparison_ingested=True,
        comparison_artifacts_loaded=True,
        calibration_inputs_resolved=True,
        reliability_bins_built=True,
        calibration_metrics_built=True,
        brier_decomposition_built=True,
        score_distribution_built=True,
        class_balance_built=True,
        post_training_validation_built=True,
        calibration_governance_built=True,
        model_cards_updated=True,
        readiness_gate_built=True,
        readiness_gate_passed=True,
        ready_for_phase142=True,
        metadata_only=True,
        research_data_only=True,
        offline_ml_research_only=True,
        activation_allowed=False,
        strategy_activation_allowed=False,
        deployment_allowed=False,
        active_paper_enabled=False,
        broker_execution_enabled=False,
        order_creation_enabled=False,
        paper_state_mutation_enabled=False,
        telegram_real_send_enabled=False,
        scraping_enabled=False,
        html_parse_enabled=False,
        paid_api_enabled=False,
        dashboard_enabled=False,
        network_default_enabled=False,
        daemon_started=False,
        scheduler_enabled=False,
        live_inference_enabled=False,
        online_inference_enabled=False,
                calibration_fitting_performed=False,
        calibrated_model_created=False,
        threshold_optimization_performed=False,
        heavy_ml_dependency_used=False,
        produces_trade_signal=False,
        produces_order_decision=False,
        produces_portfolio_weights=False,
        investment_advice=False,
        network_used=False,
        paid_api_used=False,
        scraping_used=False,
        html_parsing_used=False,
        broker_used=False,
        order_created=False,
        paper_state_mutated=False,
        telegram_real_sent=False,
        dashboard_started=False,
        valid_for_phase142=True,
        risk_flags=[],
        warnings=[],
        errors=[],
        metadata={}
    )
    errs = validate_calibration_diagnostics_ingestion_result(res)
    assert len(errs) == 0

def test_calibration_diagnostics_ingestion_result_fails_if_active():
    res = CalibrationDiagnosticsIngestionResult(
        ingestion_id="id1",
        created_at_utc="2023-01-01T00:00:00Z",
        source_path=None,
        source_review_id=None,
        source_context_id=None,
        available=True,
        model_comparison_ingested=True,
        comparison_artifacts_loaded=True,
        calibration_inputs_resolved=True,
        reliability_bins_built=True,
        calibration_metrics_built=True,
        brier_decomposition_built=True,
        score_distribution_built=True,
        class_balance_built=True,
        post_training_validation_built=True,
        calibration_governance_built=True,
        model_cards_updated=True,
        readiness_gate_built=True,
        readiness_gate_passed=True,
        ready_for_phase142=True,
        metadata_only=True,
        research_data_only=True,
        offline_ml_research_only=True,
        activation_allowed=True,  # BAD
        strategy_activation_allowed=False,
        deployment_allowed=False,
        active_paper_enabled=False,
        broker_execution_enabled=False,
        order_creation_enabled=False,
        paper_state_mutation_enabled=False,
        telegram_real_send_enabled=False,
        scraping_enabled=False,
        html_parse_enabled=False,
        paid_api_enabled=False,
        dashboard_enabled=False,
        network_default_enabled=False,
        daemon_started=False,
        scheduler_enabled=False,
        live_inference_enabled=False,
        online_inference_enabled=False,
                calibration_fitting_performed=False,
        calibrated_model_created=False,
        threshold_optimization_performed=False,
        heavy_ml_dependency_used=False,
        produces_trade_signal=False,
        produces_order_decision=False,
        produces_portfolio_weights=False,
        investment_advice=False,
        network_used=False,
        paid_api_used=False,
        scraping_used=False,
        html_parsing_used=False,
        broker_used=False,
        order_created=False,
        paper_state_mutated=False,
        telegram_real_sent=False,
        dashboard_started=False,
        valid_for_phase142=True,
        risk_flags=[],
        warnings=[],
        errors=[],
        metadata={}
    )
    errs = validate_calibration_diagnostics_ingestion_result(res)
    assert len(errs) > 0
    assert "activation_allowed must be false" in errs

def test_blend_coefficient_plan_fails_if_portfolio_weight():
    plan = BlendCoefficientPlan(
        plan_id="p1",
        created_at_utc="2023-01-01T00:00:00Z",
        policy_id="pol1",
        candidate_group_id="g1",
        status="PLANNED",
        coefficient_by_candidate_ref_id={},
        coefficient_sum=1.0,
        coefficient_valid=True,
        coefficient_label="test",
        not_portfolio_weight=False, # BAD
        not_allocation=True,
        not_target_weight=True,
        fitting_performed=False,
        research_data_only=True,
        produces_trade_signal=False,
        produces_order_decision=False,
        produces_portfolio_weights=False,
        warnings=[],
        errors=[],
        risk_flags=[],
        metadata={}
    )
    errs = validate_blend_coefficient_plan(plan)
    assert "not_portfolio_weight must be true" in errs
