import pytest
from usa_signal_bot.regime_classification.validation.phase132_models import (
    RegimeAlignmentIngestionResult,
    create_regime_alignment_ingestion_id,
    _now_utc
)

def test_regime_alignment_ingestion_result_valid():
    res = RegimeAlignmentIngestionResult(
        ingestion_id=create_regime_alignment_ingestion_id(),
        created_at_utc=_now_utc(),
        source_path=None,
        source_review_id="rev_1",
        source_context_id="ctx_1",
        available=True,
        market_behavior_ingested=True,
        frozen_factors_loaded=True,
        behavior_artifacts_loaded=True,
        alignment_specs_ready=True,
        overlays_built=True,
        compatibility_computed=True,
        diagnostics_built=True,
        readiness_gate_ready=True,
        ready_for_phase132=True,
        metadata_only=True,
        research_data_only=True,
        activation_allowed=False,
        strategy_activation_allowed=False,
        deployment_allowed=False,
        active_paper_enabled=False,
        broker_execution_enabled=False,
        order_creation_enabled=False,
        paper_state_mutation_enabled=False,
        telegram_real_send_enabled=False,
        scraping_enabled=False,
        html_parse_enabled=False,
        paid_api_enabled=False,
        dashboard_enabled=False,
        network_default_enabled=False,
        model_training_used=False,
        model_prediction_used=False,
        heavy_ml_dependency_used=False,
        produces_trade_signal=False,
        produces_order_decision=False,
        produces_portfolio_weights=False,
        investment_advice=False,
        network_used=False,
        paid_api_used=False,
        scraping_used=False,
        html_parsing_used=False,
        broker_used=False,
        order_created=False,
        paper_state_mutated=False,
        telegram_real_sent=False,
        dashboard_started=False,
        valid_for_phase132=True
    )
    assert res.valid_for_phase132 is True
