import pytest
from usa_signal_bot.regime_classification.foundation.phase126_models import (
    FinalClosureIngestionResult,
    create_final_closure_ingestion_id,
    validate_final_closure_ingestion_result
)
from usa_signal_bot.core.enums import RegimeFoundationRiskFlag

def test_final_closure_ingestion_result_valid():
    item = FinalClosureIngestionResult(
        ingestion_id=create_final_closure_ingestion_id(),
        created_at_utc="2023-01-01T00:00:00Z",
        source_path=None,
        source_review_id="test_review",
        source_context_id="test_context",
        available=True,
        final_artifacts_ready=True,
        final_checks_passed=True,
        freeze_seal_ready=True,
        engine_certificate_ready=True,
        phase126_kickoff_gate_ready=True,
        feature_factor_engine_final_closed=True,
        ready_for_phase126=True,
        metadata_only=True,
        research_data_only=True,
        activation_allowed=False,
        strategy_activation_allowed=False,
        deployment_allowed=False,
        active_paper_enabled=False,
        broker_execution_enabled=False,
        order_creation_enabled=False,
        paper_state_mutation_enabled=False,
        telegram_real_send_enabled=False,
        scraping_enabled=False,
        html_parse_enabled=False,
        paid_api_enabled=False,
        dashboard_enabled=False,
        network_default_enabled=False,
        produces_trade_signal=False,
        produces_order_decision=False,
        produces_portfolio_weights=False,
        investment_advice=False,
        network_used=False,
        paid_api_used=False,
        scraping_used=False,
        html_parsing_used=False,
        broker_used=False,
        order_created=False,
        paper_state_mutated=False,
        telegram_real_sent=False,
        dashboard_started=False,
        valid_for_phase126=True,
        risk_flags=[],
        warnings=[],
        errors=[],
        metadata={}
    )
    validate_final_closure_ingestion_result(item)

def test_final_closure_ingestion_result_invalid():
    item = FinalClosureIngestionResult(
        ingestion_id=create_final_closure_ingestion_id(),
        created_at_utc="2023-01-01T00:00:00Z",
        source_path=None,
        source_review_id="test_review",
        source_context_id="test_context",
        available=True,
        final_artifacts_ready=True,
        final_checks_passed=True,
        freeze_seal_ready=True,
        engine_certificate_ready=True,
        phase126_kickoff_gate_ready=True,
        feature_factor_engine_final_closed=True,
        ready_for_phase126=True,
        metadata_only=True,
        research_data_only=True,
        activation_allowed=True, # Invalid
        strategy_activation_allowed=False,
        deployment_allowed=False,
        active_paper_enabled=False,
        broker_execution_enabled=False,
        order_creation_enabled=False,
        paper_state_mutation_enabled=False,
        telegram_real_send_enabled=False,
        scraping_enabled=False,
        html_parse_enabled=False,
        paid_api_enabled=False,
        dashboard_enabled=False,
        network_default_enabled=False,
        produces_trade_signal=False,
        produces_order_decision=False,
        produces_portfolio_weights=False,
        investment_advice=False,
        network_used=False,
        paid_api_used=False,
        scraping_used=False,
        html_parsing_used=False,
        broker_used=False,
        order_created=False,
        paper_state_mutated=False,
        telegram_real_sent=False,
        dashboard_started=False,
        valid_for_phase126=False,
        risk_flags=[],
        warnings=[],
        errors=[],
        metadata={}
    )
    with pytest.raises(AssertionError):
        validate_final_closure_ingestion_result(item)
