from usa_signal_bot.portfolio_construction.portfolio_models import (
    SectorClusterRecord, ExposureSnapshot, ConcentrationAssessment,
    PortfolioAllocation, PortfolioCandidate, PortfolioConstructionPlan, PortfolioConstructionReview
)

def sector_cluster_record_to_text(item: SectorClusterRecord) -> str:
    return f"{item.symbol}: Sector={item.sector}, Cluster={item.cluster}"

def portfolio_candidate_to_text(item: PortfolioCandidate) -> str:
    return f"{item.symbol}: Score={item.score}, Conf={item.confidence}, Sector={item.sector}"

def exposure_snapshot_to_text(item: ExposureSnapshot) -> str:
    lines = [f"Exposure Snapshot ({item.snapshot_id})"]
    lines.append(f"  Gross: ${item.gross_exposure_usd:.2f}, Net: ${item.net_exposure_usd:.2f}")
    return "\n".join(lines)

def concentration_assessment_to_text(item: ConcentrationAssessment) -> str:
    return f"{item.name} ({item.exposure_type.value if hasattr(item.exposure_type, 'value') else str(item.exposure_type)}): {item.exposure_pct_equity}% vs {item.limit_pct_equity}% -> {item.decision.value if hasattr(item.decision, 'value') else str(item.decision)}"

def portfolio_allocation_to_text(item: PortfolioAllocation) -> str:
    return f"{item.symbol}: {item.weight_pct_equity}% (${item.final_notional_usd}) -> {item.status.value if hasattr(item.status, 'value') else str(item.status)}"

def portfolio_construction_plan_to_text(item: PortfolioConstructionPlan, limit: int = 100) -> str:
    lines = [f"Portfolio Construction Plan ({item.plan_id})", f"Mode: {item.mode.value if hasattr(item.mode, 'value') else str(item.mode)}"]
    lines.append(f"Allocations ({item.approved_count} approved, {item.reduced_count} reduced, {item.suppressed_count} suppressed):")
    for a in item.allocations[:limit]:
        lines.append("  " + portfolio_allocation_to_text(a))
    return "\n".join(lines)

def portfolio_construction_review_to_text(item: PortfolioConstructionReview, limit: int = 100) -> str:
    lines = [f"Portfolio Construction Review ({item.review_id})"]
    if item.plan:
        lines.append(portfolio_construction_plan_to_text(item.plan, limit))
    if item.exposure_snapshot:
        lines.append(exposure_snapshot_to_text(item.exposure_snapshot))
    lines.append(portfolio_construction_limitations_text())
    return "\n".join(lines)

def construction_store_summary_to_text(summary: dict[str, any]) -> str:
    lines = ["Construction Store Summary"]
    for k, v in summary.items():
        lines.append(f"  {k}: {v}")
    return "\n".join(lines)

def portfolio_construction_limitations_text() -> str:
    return (
        "\n=== PORTFOLIO CONSTRUCTION LIMITATIONS ===\n"
        "1. This is a local metadata layer and NOT an official broker portfolio.\n"
        "2. Sector/cluster mappings are local heuristics/proxies, not official classifications.\n"
        "3. Correlation proxies are rough heuristics, not true statistical correlations.\n"
        "4. This plan is NOT investment advice and makes no claims of future profitability.\n"
        "5. 'APPROVED' or 'PASS' status is NOT an authorization for live trading.\n"
        "6. No real or demo broker orders are generated by this system."
    )
