import datetime
import uuid
from typing import Optional, Tuple

from usa_signal_bot.core.enums import (
    AlertSeverity,
    AlertRouteTarget,
    NotificationPriority,
    NotificationChannel,
    AlertSuppressionReason,
    NotificationType
)
from usa_signal_bot.notifications.alert_models import AlertDecision, AlertPolicy
from usa_signal_bot.notifications.notification_models import NotificationMessage

def alert_severity_rank(severity: AlertSeverity) -> int:
    ranks = {
        AlertSeverity.INFO: 10,
        AlertSeverity.NOTICE: 20,
        AlertSeverity.WARNING: 30,
        AlertSeverity.HIGH: 40,
        AlertSeverity.CRITICAL: 50
    }
    return ranks.get(severity, 0)

def notification_priority_from_alert_severity(severity: AlertSeverity) -> NotificationPriority:
    if severity == AlertSeverity.CRITICAL:
        return NotificationPriority.CRITICAL
    elif severity == AlertSeverity.HIGH:
        return NotificationPriority.HIGH
    elif severity in (AlertSeverity.WARNING, AlertSeverity.NOTICE):
        return NotificationPriority.NORMAL
    else:
        return NotificationPriority.LOW

def notification_channel_from_route_target(target: AlertRouteTarget) -> NotificationChannel:
    if target == AlertRouteTarget.TELEGRAM:
        return NotificationChannel.TELEGRAM
    elif target == AlertRouteTarget.FILE:
        return NotificationChannel.FILE
    elif target == AlertRouteTarget.LOG_ONLY:
        return NotificationChannel.LOG_ONLY
    elif target == AlertRouteTarget.DRY_RUN:
        return NotificationChannel.DRY_RUN
    return NotificationChannel.DRY_RUN

def should_route_by_severity(severity: AlertSeverity, min_severity: AlertSeverity) -> bool:
    return alert_severity_rank(severity) >= alert_severity_rank(min_severity)

def route_alert_decision(policy: AlertPolicy, decision: AlertDecision) -> Tuple[bool, Optional[AlertSuppressionReason], NotificationChannel]:
    if policy.route_target == AlertRouteTarget.NONE:
        return False, AlertSuppressionReason.POLICY_DISABLED, NotificationChannel.DRY_RUN

    if not should_route_by_severity(decision.severity, policy.min_severity_to_route):
        return False, AlertSuppressionReason.SEVERITY_FILTERED, NotificationChannel.DRY_RUN

    channel = notification_channel_from_route_target(policy.route_target)
    return True, None, channel

def build_notification_from_alert_decision(policy: AlertPolicy, decision: AlertDecision) -> NotificationMessage:
    channel = notification_channel_from_route_target(decision.route_target)
    priority = notification_priority_from_alert_severity(decision.severity)

    # Do not include investment advice
    body = f"{decision.summary}\n\nThis is an automated alert generated by the policy layer. Not investment advice. No orders executed."

    return NotificationMessage(
        message_id=f"msg_{uuid.uuid4().hex[:8]}",
        notification_type=policy.notification_type,
        channel=channel,
        priority=priority,
        title=decision.title,
        body=body,
        created_at_utc=datetime.datetime.now(datetime.timezone.utc).isoformat()
    )

def route_target_to_text(target: AlertRouteTarget) -> str:
    return target.value if hasattr(target, "value") else target
