"""Corporate action reporting."""
from typing import Any
from usa_signal_bot.corporate_actions.corporate_action_models import (
    CorporateActionEvent,
    AdjustedPriceValidationResult,
    CorporateActionGuardResult,
    CorporateActionReviewResult
)

def corporate_action_event_to_text(event: CorporateActionEvent) -> str:
    lines = [
        f"Event: {event.symbol} -> {event.action_type.value if hasattr(event.action_type, 'value') else str(event.action_type)} on {event.ex_date}",
        f"  Source: {event.source.value if hasattr(event.source, 'value') else str(event.source)}",
        f"  Confidence: {event.confidence}"
    ]
    if event.value is not None:
        lines.append(f"  Value: {event.value}")
    if event.ratio_numerator is not None and event.ratio_denominator is not None:
        lines.append(f"  Ratio: {event.ratio_numerator}:{event.ratio_denominator}")
    for n in event.notes:
        lines.append(f"  Note: {n}")
    return "\n".join(lines)

def adjusted_price_validation_result_to_text(result: AdjustedPriceValidationResult) -> str:
    from usa_signal_bot.corporate_actions.adjusted_price_validator import adjusted_price_validation_to_text
    return adjusted_price_validation_to_text(result)

def corporate_action_guard_result_to_text(result: CorporateActionGuardResult) -> str:
    lines = [
        f"=== Corporate Action Guard: {result.symbol} ===",
        f"Status: {result.status.value if hasattr(result.status, 'value') else str(result.status)}",
        f"Severity: {result.severity.value if hasattr(result.severity, 'value') else str(result.severity)}",
        f"Events found: {len(result.events)}",
        f"Anomalies found: {len(result.gap_anomalies)}",
        f"Possible Splits: {len(result.detected_splits)}",
        f"Possible Dividends: {len(result.detected_dividends)}"
    ]
    if result.adjusted_validation:
        lines.append(f"Adjusted Price Status: {result.adjusted_validation.status.value if hasattr(result.adjusted_validation.status, 'value') else str(result.adjusted_validation.status)}")

    if result.recommended_guards:
        lines.append("Recommended Guards:")
        for rg in result.recommended_guards:
            lines.append(f"  - {rg}")

    return "\n".join(lines)

def corporate_action_review_result_to_text(result: CorporateActionReviewResult, limit: int = 50) -> str:
    lines = [
        f"=== Corporate Action Review: {result.review_id} ===",
        f"Report Type: {result.report_type.value if hasattr(result.report_type, 'value') else str(result.report_type)}",
        f"Created: {result.created_at_utc}",
        f"Symbols Checked: {len(result.symbols)}"
    ]
    if result.errors:
        lines.append("Errors:")
        for e in result.errors:
            lines.append(f"  - {e}")

    if result.guard_results:
        lines.append("\nGuard Status Highlights:")
        for gr in result.guard_results[:limit]:
            st = gr.status.value if hasattr(gr.status, "value") else str(gr.status)
            lines.append(f"  {gr.symbol}: {st} (Severity: {gr.severity.value if hasattr(gr.severity, 'value') else str(gr.severity)})")
        if len(result.guard_results) > limit:
            lines.append(f"  ... and {len(result.guard_results) - limit} more.")

    lines.append("\n" + corporate_action_limitations_text())
    return "\n".join(lines)

def corporate_action_store_summary_to_text(summary: dict[str, Any]) -> str:
    lines = [
        "=== Corporate Action Store Summary ===",
        f"Reviews count: {summary.get('reviews_count', 0)}",
        f"Latest review: {summary.get('latest_review', 'None')}",
        f"Guards count: {summary.get('guards_count', 0)}",
        f"Adjusted validations count: {summary.get('adjusted_validations_count', 0)}"
    ]
    return "\n".join(lines)

def corporate_action_limitations_text() -> str:
    return (
        "CORPORATE ACTION LIMITATIONS & DISCLAIMERS:\n"
        "- Detection heuristics for splits and dividends are estimates based on price gaps.\n"
        "- They DO NOT guarantee absolute correctness.\n"
        "- Guard outputs (BLOCK_SIGNAL, WATCH, WARNING) are for local testing and research.\n"
        "- They DO NOT constitute investment advice.\n"
        "- No real trading orders or instructions are generated by these checks."
    )
