from typing import Any
import json
from datetime import datetime, timezone
from usa_signal_bot.core.enums import NoOrderDossierReportType
from usa_signal_bot.paper_no_order_dossier.no_order_dossier_models import (
    NoOrderDossierFullReview,
    create_no_order_dossier_full_review_id,
    NoOrderPaperSessionDossier,
    BridgeReplayAuditSeal,
    PaperAdmissionBlockerEvent,
    NoOrderDossierEvidenceItem,
    NoOrderDossierAuditEntry,
    no_order_dossier_full_review_to_dict
)
from usa_signal_bot.paper_no_order_dossier.no_order_session_dossier import build_no_order_paper_session_dossier
from usa_signal_bot.paper_no_order_dossier.bridge_replay_audit_seal import build_bridge_replay_audit_seal
from usa_signal_bot.paper_no_order_dossier.dossier_evidence import collect_no_order_dossier_evidence
from usa_signal_bot.paper_no_order_dossier.admission_attempt_simulator import simulate_paper_admission_attempts
from usa_signal_bot.paper_no_order_dossier.admission_blocker_rules import default_paper_admission_blocker_rules
from usa_signal_bot.paper_no_order_dossier.no_order_dossier_audit import (
    audit_entry_from_no_order_dossier,
    audit_entry_from_bridge_replay_audit_seal,
    audit_entry_from_admission_blocker_events
)
from usa_signal_bot.paper_no_order_dossier.admission_safety_validator import validate_paper_admission_safety

def no_order_dossier_limitations_text() -> str:
    return """
LIMITATIONS AND DISCLAIMERS:
- The No-Order Dossier is a local metadata package only.
- It is NOT an active paper trading approval or deployment.
- The Bridge Replay Audit Seal is metadata-only and does not enable trading.
- The Final Paper Admission Blocker denies all admission attempts to ensure safety.
- This system DOES NOT create, route, or execute real or demo broker orders.
- This system DOES NOT mutate real paper state or configurations.
- This system DOES NOT send real Telegram notifications.
- None of the outputs generated by this system constitute investment advice.
"""

def build_no_order_dossier_review_from_parts(
    dossier: NoOrderPaperSessionDossier,
    seal: BridgeReplayAuditSeal | None = None,
    blocker_events: list[PaperAdmissionBlockerEvent] | None = None
) -> NoOrderDossierFullReview:

    seal = seal or dossier.bridge_replay_audit_seal
    blocker_events = blocker_events or dossier.blocker_events

    audit_entries = []
    if dossier:
        audit_entries.append(audit_entry_from_no_order_dossier(dossier))
    if seal:
        audit_entries.append(audit_entry_from_bridge_replay_audit_seal(seal))
    if blocker_events:
        audit_entries.append(audit_entry_from_admission_blocker_events(blocker_events))

    reasons = validate_paper_admission_safety(dossier, seal, blocker_events)

    return NoOrderDossierFullReview(
        review_id=create_no_order_dossier_full_review_id(),
        created_at_utc=datetime.now(timezone.utc).isoformat(),
        report_type=NoOrderDossierReportType.FULL_NO_ORDER_DOSSIER_REVIEW,
        dossiers=[dossier] if dossier else [],
        evidence_items=dossier.evidence_items if dossier else [],
        replay_audit_seals=[seal] if seal else [],
        blocker_rules=default_paper_admission_blocker_rules(),
        blocker_events=blocker_events or [],
        audit_entries=audit_entries,
        output_paths={},
        warnings=[],
        errors=reasons
    )

def build_no_order_dossier_full_review(bridge_payload: dict[str, Any]) -> NoOrderDossierFullReview:
    evidence = collect_no_order_dossier_evidence(bridge_payload)
    dossier = build_no_order_paper_session_dossier(bridge_payload)
    seal = build_bridge_replay_audit_seal(bridge_payload, evidence)
    blocker_events = simulate_paper_admission_attempts()

    dossier.bridge_replay_audit_seal = seal
    dossier.blocker_events = blocker_events
    dossier.evidence_items = evidence

    return build_no_order_dossier_review_from_parts(dossier, seal, blocker_events)

def no_order_dossier_full_review_summary(review: NoOrderDossierFullReview) -> dict[str, Any]:
    dossier = review.dossiers[0] if review.dossiers else None
    return {
        "review_id": review.review_id,
        "dossier_status": dossier.status if dossier else None,
        "seal_count": len(review.replay_audit_seals),
        "blocker_event_count": len(review.blocker_events),
        "safe": len(review.errors) == 0,
        "errors": review.errors
    }

def no_order_dossier_full_review_to_text(review: NoOrderDossierFullReview, limit: int = 100) -> str:
    summary = no_order_dossier_full_review_summary(review)
    return json.dumps(summary, indent=2) + "\n" + no_order_dossier_limitations_text()
