from enum import Enum

class AssetType(str, Enum):
    STOCK = "STOCK"
    ETF = "ETF"

class TimeFrame(str, Enum):
    ONE_MINUTE = "ONE_MINUTE"
    FIVE_MINUTES = "FIVE_MINUTES"
    FIFTEEN_MINUTES = "FIFTEEN_MINUTES"
    THIRTY_MINUTES = "THIRTY_MINUTES"
    ONE_HOUR = "ONE_HOUR"
    ONE_DAY = "ONE_DAY"
    ONE_WEEK = "ONE_WEEK"

class SignalSide(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"

class SignalStrength(str, Enum):
    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"
    VERY_STRONG = "VERY_STRONG"

class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"

class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"

class OrderStatus(str, Enum):
    CREATED = "CREATED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"

class PositionSide(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"

class TradeStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"

class RegimeType(str, Enum):
    UNKNOWN = "UNKNOWN"
    RISK_ON = "RISK_ON"
    RISK_OFF = "RISK_OFF"
    TRENDING_UP = "TRENDING_UP"
    TRENDING_DOWN = "TRENDING_DOWN"
    RANGE_BOUND = "RANGE_BOUND"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LOW_VOLATILITY = "LOW_VOLATILITY"

class DataQualityStatus(str, Enum):
    OK = "OK"
    WARNING = "WARNING"
    ERROR = "ERROR"

class BacktestStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class ModelRunStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class ReportFormat(str, Enum):
    TXT = "TXT"
    JSON = "JSON"
    CSV = "CSV"
    HTML_DISABLED = "HTML_DISABLED"

class DataProviderName(str, Enum):
    MOCK = "MOCK"
    YFINANCE_RESERVED = "YFINANCE_RESERVED"

class DataFrequency(str, Enum):
    DAILY = "DAILY"
    INTRADAY = "INTRADAY"
    WEEKLY = "WEEKLY"

class ProviderAvailability(str, Enum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    RESERVED = "RESERVED"
    DISABLED = "DISABLED"

class DataAnomalyType(str, Enum):
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    INVALID_PRICE = "INVALID_PRICE"
    HIGH_LOW_INCONSISTENCY = "HIGH_LOW_INCONSISTENCY"
    NEGATIVE_VOLUME = "NEGATIVE_VOLUME"
    ZERO_VOLUME = "ZERO_VOLUME"
    DUPLICATE_BAR = "DUPLICATE_BAR"
    NON_MONOTONIC_TIMESTAMP = "NON_MONOTONIC_TIMESTAMP"
    MISSING_SYMBOL = "MISSING_SYMBOL"
    EMPTY_DATASET = "EMPTY_DATASET"
    STALE_CACHE = "STALE_CACHE"
    SUSPICIOUS_GAP = "SUSPICIOUS_GAP"
    OUTLIER_RETURN = "OUTLIER_RETURN"
    UNKNOWN = "UNKNOWN"

class DataRepairActionType(str, Enum):
    DROP_INVALID_BAR = "DROP_INVALID_BAR"
    DROP_DUPLICATE_BAR = "DROP_DUPLICATE_BAR"
    SORT_BY_TIMESTAMP = "SORT_BY_TIMESTAMP"
    FILL_MISSING_VOLUME_WITH_ZERO = "FILL_MISSING_VOLUME_WITH_ZERO"
    KEEP_WITH_WARNING = "KEEP_WITH_WARNING"
    MARK_SYMBOL_MISSING = "MARK_SYMBOL_MISSING"
    NO_ACTION = "NO_ACTION"

class CacheDecision(str, Enum):
    USE_CACHE = "USE_CACHE"
    REFRESH_CACHE = "REFRESH_CACHE"
    CACHE_MISSING = "CACHE_MISSING"
    CACHE_STALE = "CACHE_STALE"
    CACHE_INVALID = "CACHE_INVALID"
    BYPASS_CACHE = "BYPASS_CACHE"

class ValidationSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class DataReadinessStatus(str, Enum):
    READY = "READY"
    PARTIAL = "PARTIAL"
    NOT_READY = "NOT_READY"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"

class DataCoverageStatus(str, Enum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    EMPTY = "EMPTY"
    STALE = "STALE"
    INVALID = "INVALID"

class TimeframeRole(str, Enum):
    PRIMARY = "PRIMARY"
    CONFIRMATION = "CONFIRMATION"
    CONTEXT = "CONTEXT"
    INTRADAY = "INTRADAY"
    DAILY = "DAILY"

class PipelineRunStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"


class UniverseSourceType(str, Enum):
    MANUAL_SEED = "MANUAL_SEED"
    USER_CSV = "USER_CSV"
    LOCAL_IMPORT = "LOCAL_IMPORT"
    PRESET = "PRESET"
    SNAPSHOT = "SNAPSHOT"
    GENERATED = "GENERATED"
    RESERVED_EXTERNAL = "RESERVED_EXTERNAL"

class UniverseLayer(str, Enum):
    CORE = "CORE"
    WATCHLIST = "WATCHLIST"
    LARGE_CAP = "LARGE_CAP"
    MEGA_CAP = "MEGA_CAP"
    SECTOR_ETF = "SECTOR_ETF"
    INDEX_ETF = "INDEX_ETF"
    CUSTOM = "CUSTOM"
    RESEARCH = "RESEARCH"
    CANDIDATE = "CANDIDATE"
    EXCLUDED = "EXCLUDED"

class UniverseConflictResolution(str, Enum):
    FIRST_WINS = "FIRST_WINS"
    LAST_WINS = "LAST_WINS"
    PREFER_ACTIVE = "PREFER_ACTIVE"
    PREFER_COMPLETE_METADATA = "PREFER_COMPLETE_METADATA"
    ERROR_ON_CONFLICT = "ERROR_ON_CONFLICT"

class UniverseSnapshotStatus(str, Enum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    FAILED = "FAILED"


class ActiveUniverseSource(str, Enum):
    ACTIVE_SNAPSHOT = "ACTIVE_SNAPSHOT"
    LATEST_SNAPSHOT = "LATEST_SNAPSHOT"
    DEFAULT_WATCHLIST = "DEFAULT_WATCHLIST"
    PRESET_FALLBACK = "PRESET_FALLBACK"
    EXPLICIT_FILE = "EXPLICIT_FILE"

class UniverseDataRunStatus(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class UniverseReadinessGateStatus(str, Enum):
    PASSED = "PASSED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    NOT_EVALUATED = "NOT_EVALUATED"

class SymbolReadinessStatus(str, Enum):
    ELIGIBLE = "ELIGIBLE"
    PARTIAL = "PARTIAL"
    INELIGIBLE = "INELIGIBLE"
    MISSING_DATA = "MISSING_DATA"
    FAILED_VALIDATION = "FAILED_VALIDATION"

class UniverseRunStep(str, Enum):
    RESOLVE_UNIVERSE = "RESOLVE_UNIVERSE"
    BUILD_REFRESH_PLAN = "BUILD_REFRESH_PLAN"
    DOWNLOAD_DATA = "DOWNLOAD_DATA"
    VALIDATE_DATA = "VALIDATE_DATA"
    REPAIR_DATA = "REPAIR_DATA"
    COVERAGE_REPORT = "COVERAGE_REPORT"
    READINESS_REPORT = "READINESS_REPORT"
    READINESS_GATE = "READINESS_GATE"
    WRITE_OUTPUTS = "WRITE_OUTPUTS"

class IndicatorCategory(str, Enum):
    PRICE = "PRICE"
    VOLUME = "VOLUME"
    TREND = "TREND"
    MOMENTUM = "MOMENTUM"
    VOLATILITY = "VOLATILITY"
    BREADTH = "BREADTH"
    REGIME = "REGIME"
    CUSTOM = "CUSTOM"

class IndicatorOutputType(str, Enum):
    SERIES = "SERIES"
    SCALAR = "SCALAR"
    MULTI_SERIES = "MULTI_SERIES"

class FeatureComputationStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"

class FeatureValidationStatus(str, Enum):
    VALID = "VALID"
    WARNING = "WARNING"
    INVALID = "INVALID"
    EMPTY = "EMPTY"

class FeatureStorageFormat(str, Enum):
    JSONL = "JSONL"
    CSV = "CSV"

class TrendFeatureType(str, Enum):
    MOVING_AVERAGE = "MOVING_AVERAGE"
    MACD = "MACD"
    PRICE_DISTANCE = "PRICE_DISTANCE"
    SLOPE = "SLOPE"
    ALIGNMENT = "ALIGNMENT"
    TREND_STRENGTH = "TREND_STRENGTH"

class MovingAverageType(str, Enum):
    SMA = "SMA"
    EMA = "EMA"
    WMA = "WMA"
    DEMA = "DEMA"
    TEMA = "TEMA"

class TrendDirection(str, Enum):
    UP = "UP"
    DOWN = "DOWN"
    FLAT = "FLAT"
    UNKNOWN = "UNKNOWN"

class MomentumFeatureType(str, Enum):
    RSI = "RSI"
    STOCHASTIC = "STOCHASTIC"
    ROC = "ROC"
    MOMENTUM = "MOMENTUM"
    WILLIAMS_R = "WILLIAMS_R"
    CCI = "CCI"
    MOMENTUM_SLOPE = "MOMENTUM_SLOPE"
    MOMENTUM_ACCELERATION = "MOMENTUM_ACCELERATION"
    NORMALIZED_MOMENTUM = "NORMALIZED_MOMENTUM"

class MomentumZone(str, Enum):
    EXTREME_HIGH = "EXTREME_HIGH"
    HIGH = "HIGH"
    NEUTRAL = "NEUTRAL"
    LOW = "LOW"
    EXTREME_LOW = "EXTREME_LOW"
    UNKNOWN = "UNKNOWN"


class VolatilityFeatureType(str, Enum):
    TRUE_RANGE = "TRUE_RANGE"
    ATR = "ATR"
    NORMALIZED_ATR = "NORMALIZED_ATR"
    BOLLINGER_BANDS = "BOLLINGER_BANDS"
    BOLLINGER_BANDWIDTH = "BOLLINGER_BANDWIDTH"
    BOLLINGER_PERCENT_B = "BOLLINGER_PERCENT_B"
    KELTNER_CHANNEL = "KELTNER_CHANNEL"
    DONCHIAN_CHANNEL = "DONCHIAN_CHANNEL"
    ROLLING_VOLATILITY = "ROLLING_VOLATILITY"
    PRICE_RANGE = "PRICE_RANGE"
    VOLATILITY_COMPRESSION = "VOLATILITY_COMPRESSION"
    VOLATILITY_EXPANSION = "VOLATILITY_EXPANSION"

class VolatilityRegimeHint(str, Enum):
    VERY_LOW = "VERY_LOW"
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
    UNKNOWN = "UNKNOWN"

class BandPosition(str, Enum):
    ABOVE_UPPER = "ABOVE_UPPER"
    BETWEEN_UPPER_MID = "BETWEEN_UPPER_MID"
    BETWEEN_MID_LOWER = "BETWEEN_MID_LOWER"
    BELOW_LOWER = "BELOW_LOWER"
    UNKNOWN = "UNKNOWN"

class PriceActionFeatureType(str, Enum):
    CANDLE_BODY = "CANDLE_BODY"
    CANDLE_WICK = "CANDLE_WICK"
    CLOSE_LOCATION = "CLOSE_LOCATION"
    GAP = "GAP"
    BREAKOUT_DISTANCE = "BREAKOUT_DISTANCE"
    BREAKDOWN_DISTANCE = "BREAKDOWN_DISTANCE"
    INSIDE_OUTSIDE_BAR = "INSIDE_OUTSIDE_BAR"
    SWING_POINT = "SWING_POINT"
    MARKET_STRUCTURE = "MARKET_STRUCTURE"
    RANGE_EXPANSION = "RANGE_EXPANSION"
    RANGE_CONTRACTION = "RANGE_CONTRACTION"

class CandleDirection(str, Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    DOJI = "DOJI"
    UNKNOWN = "UNKNOWN"

class BarPatternType(str, Enum):
    INSIDE_BAR = "INSIDE_BAR"
    OUTSIDE_BAR = "OUTSIDE_BAR"
    NEUTRAL = "NEUTRAL"
    UNKNOWN = "UNKNOWN"

class SwingPointType(str, Enum):
    SWING_HIGH = "SWING_HIGH"
    SWING_LOW = "SWING_LOW"
    NONE = "NONE"
    UNKNOWN = "UNKNOWN"

class MarketStructureState(str, Enum):
    HIGHER_HIGH = "HIGHER_HIGH"
    HIGHER_LOW = "HIGHER_LOW"
    LOWER_HIGH = "LOWER_HIGH"
    LOWER_LOW = "LOWER_LOW"
    RANGE = "RANGE"
    UNKNOWN = "UNKNOWN"

class DivergenceType(str, Enum):
    REGULAR_BULLISH = "REGULAR_BULLISH"
    REGULAR_BEARISH = "REGULAR_BEARISH"
    HIDDEN_BULLISH = "HIDDEN_BULLISH"
    HIDDEN_BEARISH = "HIDDEN_BEARISH"
    NONE = "NONE"
    UNKNOWN = "UNKNOWN"

class DivergenceSource(str, Enum):
    RSI = "RSI"
    MACD_HIST = "MACD_HIST"
    ROC = "ROC"
    MOMENTUM = "MOMENTUM"
    MFI = "MFI"
    OBV = "OBV"
    CUSTOM = "CUSTOM"

class PivotType(str, Enum):
    PRICE_HIGH = "PRICE_HIGH"
    PRICE_LOW = "PRICE_LOW"
    OSC_HIGH = "OSC_HIGH"
    OSC_LOW = "OSC_LOW"
    NONE = "NONE"

class DivergenceConfirmationMode(str, Enum):
    CONFIRMED_PIVOT = "CONFIRMED_PIVOT"
    LEFT_ONLY_PIVOT = "LEFT_ONLY_PIVOT"
    ROLLING_EXTREME = "ROLLING_EXTREME"
    UNKNOWN = "UNKNOWN"

class DivergenceStrength(str, Enum):
    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"
    VERY_STRONG = "VERY_STRONG"
    UNKNOWN = "UNKNOWN"
