from enum import Enum

class AssetType(str, Enum):
    STOCK = "STOCK"
    ETF = "ETF"

class TimeFrame(str, Enum):
    ONE_MINUTE = "ONE_MINUTE"
    FIVE_MINUTES = "FIVE_MINUTES"
    FIFTEEN_MINUTES = "FIFTEEN_MINUTES"
    THIRTY_MINUTES = "THIRTY_MINUTES"
    ONE_HOUR = "ONE_HOUR"
    ONE_DAY = "ONE_DAY"
    ONE_WEEK = "ONE_WEEK"

class SignalSide(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"

class SignalStrength(str, Enum):
    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"
    VERY_STRONG = "VERY_STRONG"

class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"

class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"

class OrderStatus(str, Enum):
    CREATED = "CREATED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"

class PositionSide(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"

class TradeStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"

class RegimeType(str, Enum):
    UNKNOWN = "UNKNOWN"
    RISK_ON = "RISK_ON"
    RISK_OFF = "RISK_OFF"
    TRENDING_UP = "TRENDING_UP"
    TRENDING_DOWN = "TRENDING_DOWN"
    RANGE_BOUND = "RANGE_BOUND"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LOW_VOLATILITY = "LOW_VOLATILITY"

class DataQualityStatus(str, Enum):
    OK = "OK"
    WARNING = "WARNING"
    ERROR = "ERROR"

class BacktestStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class ModelRunStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class ReportFormat(str, Enum):
    TXT = "TXT"
    JSON = "JSON"
    CSV = "CSV"
    HTML_DISABLED = "HTML_DISABLED"

class DataProviderName(str, Enum):
    YFINANCE = "YFINANCE"
    LOCAL_CACHE = "LOCAL_CACHE"
    LOCAL_FIXTURE = "LOCAL_FIXTURE"
    MANUAL_FILE = "MANUAL_FILE"
    SYNTHETIC_TEST = "SYNTHETIC_TEST"
    UNKNOWN = "UNKNOWN"
    MOCK = "MOCK"
    YFINANCE_RESERVED = "YFINANCE_RESERVED"

class DataFrequency(str, Enum):
    DAILY = "DAILY"
    INTRADAY = "INTRADAY"
    WEEKLY = "WEEKLY"

class ProviderAvailability(str, Enum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    RESERVED = "RESERVED"
    DISABLED = "DISABLED"

class DataAnomalyType(str, Enum):
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    INVALID_PRICE = "INVALID_PRICE"
    HIGH_LOW_INCONSISTENCY = "HIGH_LOW_INCONSISTENCY"
    NEGATIVE_VOLUME = "NEGATIVE_VOLUME"
    ZERO_VOLUME = "ZERO_VOLUME"
    DUPLICATE_BAR = "DUPLICATE_BAR"
    NON_MONOTONIC_TIMESTAMP = "NON_MONOTONIC_TIMESTAMP"
    MISSING_SYMBOL = "MISSING_SYMBOL"
    EMPTY_DATASET = "EMPTY_DATASET"
    STALE_CACHE = "STALE_CACHE"
    SUSPICIOUS_GAP = "SUSPICIOUS_GAP"
    OUTLIER_RETURN = "OUTLIER_RETURN"
    UNKNOWN = "UNKNOWN"

class DataRepairActionType(str, Enum):
    DROP_INVALID_BAR = "DROP_INVALID_BAR"
    DROP_DUPLICATE_BAR = "DROP_DUPLICATE_BAR"
    SORT_BY_TIMESTAMP = "SORT_BY_TIMESTAMP"
    FILL_MISSING_VOLUME_WITH_ZERO = "FILL_MISSING_VOLUME_WITH_ZERO"
    KEEP_WITH_WARNING = "KEEP_WITH_WARNING"
    MARK_SYMBOL_MISSING = "MARK_SYMBOL_MISSING"
    NO_ACTION = "NO_ACTION"

class CacheDecision(str, Enum):
    USE_CACHE = "USE_CACHE"
    REFRESH_CACHE = "REFRESH_CACHE"
    CACHE_MISSING = "CACHE_MISSING"
    CACHE_STALE = "CACHE_STALE"
    CACHE_INVALID = "CACHE_INVALID"
    BYPASS_CACHE = "BYPASS_CACHE"

class ValidationSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class DataReadinessStatus(str, Enum):
    READY = "READY"
    PARTIAL = "PARTIAL"
    NOT_READY = "NOT_READY"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"

class DataCoverageStatus(str, Enum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    EMPTY = "EMPTY"
    STALE = "STALE"
    INVALID = "INVALID"

class TimeframeRole(str, Enum):
    PRIMARY = "PRIMARY"
    CONFIRMATION = "CONFIRMATION"
    CONTEXT = "CONTEXT"
    INTRADAY = "INTRADAY"
    DAILY = "DAILY"

class PipelineRunStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"


class UniverseSourceType(str, Enum):
    MANUAL_SEED = "MANUAL_SEED"
    USER_CSV = "USER_CSV"
    LOCAL_IMPORT = "LOCAL_IMPORT"
    PRESET = "PRESET"
    SNAPSHOT = "SNAPSHOT"
    GENERATED = "GENERATED"
    RESERVED_EXTERNAL = "RESERVED_EXTERNAL"

class UniverseLayer(str, Enum):
    CORE = "CORE"
    WATCHLIST = "WATCHLIST"
    LARGE_CAP = "LARGE_CAP"
    MEGA_CAP = "MEGA_CAP"
    SECTOR_ETF = "SECTOR_ETF"
    INDEX_ETF = "INDEX_ETF"
    CUSTOM = "CUSTOM"
    RESEARCH = "RESEARCH"
    CANDIDATE = "CANDIDATE"
    EXCLUDED = "EXCLUDED"

class UniverseConflictResolution(str, Enum):
    FIRST_WINS = "FIRST_WINS"
    LAST_WINS = "LAST_WINS"
    PREFER_ACTIVE = "PREFER_ACTIVE"
    PREFER_COMPLETE_METADATA = "PREFER_COMPLETE_METADATA"
    ERROR_ON_CONFLICT = "ERROR_ON_CONFLICT"

class UniverseSnapshotStatus(str, Enum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    FAILED = "FAILED"


class ActiveUniverseSource(str, Enum):
    ACTIVE_SNAPSHOT = "ACTIVE_SNAPSHOT"
    LATEST_SNAPSHOT = "LATEST_SNAPSHOT"
    DEFAULT_WATCHLIST = "DEFAULT_WATCHLIST"
    PRESET_FALLBACK = "PRESET_FALLBACK"
    EXPLICIT_FILE = "EXPLICIT_FILE"

class UniverseDataRunStatus(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class UniverseReadinessGateStatus(str, Enum):
    PASSED = "PASSED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    NOT_EVALUATED = "NOT_EVALUATED"

class SymbolReadinessStatus(str, Enum):
    ELIGIBLE = "ELIGIBLE"
    PARTIAL = "PARTIAL"
    INELIGIBLE = "INELIGIBLE"
    MISSING_DATA = "MISSING_DATA"
    FAILED_VALIDATION = "FAILED_VALIDATION"

class UniverseRunStep(str, Enum):
    RESOLVE_UNIVERSE = "RESOLVE_UNIVERSE"
    BUILD_REFRESH_PLAN = "BUILD_REFRESH_PLAN"
    DOWNLOAD_DATA = "DOWNLOAD_DATA"
    VALIDATE_DATA = "VALIDATE_DATA"
    REPAIR_DATA = "REPAIR_DATA"
    COVERAGE_REPORT = "COVERAGE_REPORT"
    READINESS_REPORT = "READINESS_REPORT"
    READINESS_GATE = "READINESS_GATE"
    WRITE_OUTPUTS = "WRITE_OUTPUTS"

class IndicatorCategory(str, Enum):
    PRICE = "PRICE"
    VOLUME = "VOLUME"
    TREND = "TREND"
    MOMENTUM = "MOMENTUM"
    VOLATILITY = "VOLATILITY"
    BREADTH = "BREADTH"
    REGIME = "REGIME"
    CUSTOM = "CUSTOM"

class IndicatorOutputType(str, Enum):
    SERIES = "SERIES"
    SCALAR = "SCALAR"
    MULTI_SERIES = "MULTI_SERIES"

class FeatureComputationStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"

class FeatureValidationStatus(str, Enum):
    VALID = "VALID"
    WARNING = "WARNING"
    INVALID = "INVALID"
    EMPTY = "EMPTY"

class FeatureStorageFormat(str, Enum):
    JSONL = "JSONL"
    CSV = "CSV"

class TrendFeatureType(str, Enum):
    MOVING_AVERAGE = "MOVING_AVERAGE"
    MACD = "MACD"
    PRICE_DISTANCE = "PRICE_DISTANCE"
    SLOPE = "SLOPE"
    ALIGNMENT = "ALIGNMENT"
    TREND_STRENGTH = "TREND_STRENGTH"

class MovingAverageType(str, Enum):
    SMA = "SMA"
    EMA = "EMA"
    WMA = "WMA"
    DEMA = "DEMA"
    TEMA = "TEMA"

class TrendDirection(str, Enum):
    UP = "UP"
    DOWN = "DOWN"
    FLAT = "FLAT"
    UNKNOWN = "UNKNOWN"

class MomentumFeatureType(str, Enum):
    RSI = "RSI"
    STOCHASTIC = "STOCHASTIC"
    ROC = "ROC"
    MOMENTUM = "MOMENTUM"
    WILLIAMS_R = "WILLIAMS_R"
    CCI = "CCI"
    MOMENTUM_SLOPE = "MOMENTUM_SLOPE"
    MOMENTUM_ACCELERATION = "MOMENTUM_ACCELERATION"
    NORMALIZED_MOMENTUM = "NORMALIZED_MOMENTUM"

class MomentumZone(str, Enum):
    EXTREME_HIGH = "EXTREME_HIGH"
    HIGH = "HIGH"
    NEUTRAL = "NEUTRAL"
    LOW = "LOW"
    EXTREME_LOW = "EXTREME_LOW"
    UNKNOWN = "UNKNOWN"


class VolatilityFeatureType(str, Enum):
    TRUE_RANGE = "TRUE_RANGE"
    ATR = "ATR"
    NORMALIZED_ATR = "NORMALIZED_ATR"
    BOLLINGER_BANDS = "BOLLINGER_BANDS"
    BOLLINGER_BANDWIDTH = "BOLLINGER_BANDWIDTH"
    BOLLINGER_PERCENT_B = "BOLLINGER_PERCENT_B"
    KELTNER_CHANNEL = "KELTNER_CHANNEL"
    DONCHIAN_CHANNEL = "DONCHIAN_CHANNEL"
    ROLLING_VOLATILITY = "ROLLING_VOLATILITY"
    PRICE_RANGE = "PRICE_RANGE"
    VOLATILITY_COMPRESSION = "VOLATILITY_COMPRESSION"
    VOLATILITY_EXPANSION = "VOLATILITY_EXPANSION"

class VolatilityRegimeHint(str, Enum):
    VERY_LOW = "VERY_LOW"
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
    UNKNOWN = "UNKNOWN"

class BandPosition(str, Enum):
    ABOVE_UPPER = "ABOVE_UPPER"
    BETWEEN_UPPER_MID = "BETWEEN_UPPER_MID"
    BETWEEN_MID_LOWER = "BETWEEN_MID_LOWER"
    BELOW_LOWER = "BELOW_LOWER"
    UNKNOWN = "UNKNOWN"

class PriceActionFeatureType(str, Enum):
    CANDLE_BODY = "CANDLE_BODY"
    CANDLE_WICK = "CANDLE_WICK"
    CLOSE_LOCATION = "CLOSE_LOCATION"
    GAP = "GAP"
    BREAKOUT_DISTANCE = "BREAKOUT_DISTANCE"
    BREAKDOWN_DISTANCE = "BREAKDOWN_DISTANCE"
    INSIDE_OUTSIDE_BAR = "INSIDE_OUTSIDE_BAR"
    SWING_POINT = "SWING_POINT"
    MARKET_STRUCTURE = "MARKET_STRUCTURE"
    RANGE_EXPANSION = "RANGE_EXPANSION"
    RANGE_CONTRACTION = "RANGE_CONTRACTION"

class CandleDirection(str, Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    DOJI = "DOJI"
    UNKNOWN = "UNKNOWN"

class BarPatternType(str, Enum):
    INSIDE_BAR = "INSIDE_BAR"
    OUTSIDE_BAR = "OUTSIDE_BAR"
    NEUTRAL = "NEUTRAL"
    UNKNOWN = "UNKNOWN"

class SwingPointType(str, Enum):
    SWING_HIGH = "SWING_HIGH"
    SWING_LOW = "SWING_LOW"
    NONE = "NONE"
    UNKNOWN = "UNKNOWN"

class MarketStructureState(str, Enum):
    HIGHER_HIGH = "HIGHER_HIGH"
    HIGHER_LOW = "HIGHER_LOW"
    LOWER_HIGH = "LOWER_HIGH"
    LOWER_LOW = "LOWER_LOW"
    RANGE = "RANGE"
    UNKNOWN = "UNKNOWN"

class DivergenceType(str, Enum):
    REGULAR_BULLISH = "REGULAR_BULLISH"
    REGULAR_BEARISH = "REGULAR_BEARISH"
    HIDDEN_BULLISH = "HIDDEN_BULLISH"
    HIDDEN_BEARISH = "HIDDEN_BEARISH"
    NONE = "NONE"
    UNKNOWN = "UNKNOWN"

class DivergenceSource(str, Enum):
    RSI = "RSI"
    MACD_HIST = "MACD_HIST"
    ROC = "ROC"
    MOMENTUM = "MOMENTUM"
    MFI = "MFI"
    OBV = "OBV"
    CUSTOM = "CUSTOM"

class PivotType(str, Enum):
    PRICE_HIGH = "PRICE_HIGH"
    PRICE_LOW = "PRICE_LOW"
    OSC_HIGH = "OSC_HIGH"
    OSC_LOW = "OSC_LOW"
    NONE = "NONE"

class DivergenceConfirmationMode(str, Enum):
    CONFIRMED_PIVOT = "CONFIRMED_PIVOT"
    LEFT_ONLY_PIVOT = "LEFT_ONLY_PIVOT"
    ROLLING_EXTREME = "ROLLING_EXTREME"
    UNKNOWN = "UNKNOWN"

class DivergenceStrength(str, Enum):
    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"
    VERY_STRONG = "VERY_STRONG"
    UNKNOWN = "UNKNOWN"

class FeatureGroupType(str, Enum):
    BASIC = "BASIC"
    TREND = "TREND"
    MOMENTUM = "MOMENTUM"
    VOLATILITY = "VOLATILITY"
    VOLUME = "VOLUME"
    PRICE_ACTION = "PRICE_ACTION"
    DIVERGENCE = "DIVERGENCE"
    COMPOSITE = "COMPOSITE"
    CUSTOM = "CUSTOM"

class CompositeFeatureSetName(str, Enum):
    MINIMAL = "MINIMAL"
    CORE = "CORE"
    TECHNICAL = "TECHNICAL"
    FULL = "FULL"
    RESEARCH = "RESEARCH"

class FeaturePipelineStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"

class FeatureCheckpointStatus(str, Enum):
    PASSED = "PASSED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    NOT_EVALUATED = "NOT_EVALUATED"

class FeatureOutputPartition(str, Enum):
    BY_SYMBOL = "BY_SYMBOL"
    BY_TIMEFRAME = "BY_TIMEFRAME"
    BY_GROUP = "BY_GROUP"
    COMBINED = "COMBINED"

class StrategyCategory(str, Enum):
    TREND_FOLLOWING = "TREND_FOLLOWING"
    MEAN_REVERSION = "MEAN_REVERSION"
    MOMENTUM = "MOMENTUM"
    VOLATILITY = "VOLATILITY"
    VOLUME = "VOLUME"
    PRICE_ACTION = "PRICE_ACTION"
    DIVERGENCE = "DIVERGENCE"
    COMPOSITE = "COMPOSITE"
    CUSTOM = "CUSTOM"

class StrategyStatus(str, Enum):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    EXPERIMENTAL = "EXPERIMENTAL"
    DEPRECATED = "DEPRECATED"

class StrategyRunStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"

class SignalAction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"
    WATCH = "WATCH"
    AVOID = "AVOID"

class SignalConfidenceBucket(str, Enum):
    VERY_LOW = "VERY_LOW"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
    UNKNOWN = "UNKNOWN"

class SignalRiskFlag(str, Enum):
    NONE = "NONE"
    LOW_LIQUIDITY = "LOW_LIQUIDITY"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    DATA_QUALITY_WARNING = "DATA_QUALITY_WARNING"
    INSUFFICIENT_FEATURES = "INSUFFICIENT_FEATURES"
    CONFLICTING_FEATURES = "CONFLICTING_FEATURES"
    STRATEGY_ERROR = "STRATEGY_ERROR"
    UNKNOWN = "UNKNOWN"

class SignalLifecycleStatus(str, Enum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    ARCHIVED = "ARCHIVED"


class SignalScoreComponent(str, Enum):
    STRATEGY_BASE = "STRATEGY_BASE"
    FEATURE_ALIGNMENT = "FEATURE_ALIGNMENT"
    CONFIDENCE = "CONFIDENCE"
    REASON_QUALITY = "REASON_QUALITY"
    DATA_QUALITY = "DATA_QUALITY"
    RISK_PENALTY = "RISK_PENALTY"
    CONFLUENCE = "CONFLUENCE"
    RECENCY = "RECENCY"
    UNKNOWN = "UNKNOWN"

class SignalQualityStatus(str, Enum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    WARNING = "WARNING"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    UNKNOWN = "UNKNOWN"

class SignalRejectionReason(str, Enum):
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    LOW_SCORE = "LOW_SCORE"
    MISSING_REASONS = "MISSING_REASONS"
    MISSING_FEATURE_SNAPSHOT = "MISSING_FEATURE_SNAPSHOT"
    DUPLICATE_SIGNAL = "DUPLICATE_SIGNAL"
    CONFLICTING_SIGNAL = "CONFLICTING_SIGNAL"
    HIGH_RISK_FLAGS = "HIGH_RISK_FLAGS"
    DATA_QUALITY_WARNING = "DATA_QUALITY_WARNING"
    OVERCONFIDENT_WITHOUT_BACKTEST = "OVERCONFIDENT_WITHOUT_BACKTEST"
    EXPIRED_SIGNAL = "EXPIRED_SIGNAL"
    INVALID_SIGNAL = "INVALID_SIGNAL"
    UNKNOWN = "UNKNOWN"

class ConfluenceDirection(str, Enum):
    LONG_BIAS = "LONG_BIAS"
    SHORT_BIAS = "SHORT_BIAS"
    FLAT_BIAS = "FLAT_BIAS"
    WATCH_BIAS = "WATCH_BIAS"
    CONFLICTED = "CONFLICTED"
    MIXED = "MIXED"
    NONE = "NONE"

class ConfluenceStrength(str, Enum):
    NONE = "NONE"
    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"
    VERY_STRONG = "VERY_STRONG"

class SignalAggregationMode(str, Enum):
    BY_SYMBOL_TIMEFRAME = "BY_SYMBOL_TIMEFRAME"
    BY_SYMBOL = "BY_SYMBOL"
    BY_STRATEGY = "BY_STRATEGY"
    GLOBAL = "GLOBAL"

class SignalRankingStatus(str, Enum):
    NOT_RANKED = "NOT_RANKED"
    RANKED = "RANKED"
    FILTERED = "FILTERED"
    SELECTED = "SELECTED"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"

class CandidateSelectionStatus(str, Enum):
    SELECTED = "SELECTED"
    REJECTED = "REJECTED"
    WATCHLISTED = "WATCHLISTED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    UNKNOWN = "UNKNOWN"

class CandidateRejectionReason(str, Enum):
    LOW_RANK_SCORE = "LOW_RANK_SCORE"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    LOW_CONFLUENCE = "LOW_CONFLUENCE"
    DUPLICATE_SYMBOL = "DUPLICATE_SYMBOL"
    CONFLICTING_SIGNAL = "CONFLICTING_SIGNAL"
    TOO_MANY_PER_SYMBOL = "TOO_MANY_PER_SYMBOL"
    TOO_MANY_PER_STRATEGY = "TOO_MANY_PER_STRATEGY"
    HIGH_RISK_FLAGS = "HIGH_RISK_FLAGS"
    MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"

class RankingComponent(str, Enum):
    SIGNAL_SCORE = "SIGNAL_SCORE"
    CONFIDENCE = "CONFIDENCE"
    CONFLUENCE = "CONFLUENCE"
    QUALITY = "QUALITY"
    RECENCY = "RECENCY"
    STRATEGY_DIVERSITY = "STRATEGY_DIVERSITY"
    RISK_PENALTY = "RISK_PENALTY"
    ACTION_PRIORITY = "ACTION_PRIORITY"
    UNKNOWN = "UNKNOWN"

class StrategyPortfolioMode(str, Enum):
    SINGLE_BEST_PER_SYMBOL = "SINGLE_BEST_PER_SYMBOL"
    MULTI_STRATEGY_CONFLUENCE = "MULTI_STRATEGY_CONFLUENCE"
    DIVERSIFIED_STRATEGIES = "DIVERSIFIED_STRATEGIES"
    RESEARCH_POOL = "RESEARCH_POOL"

class SignalCollapseMode(str, Enum):
    KEEP_ALL = "KEEP_ALL"
    BEST_PER_SYMBOL_TIMEFRAME = "BEST_PER_SYMBOL_TIMEFRAME"
    BEST_PER_SYMBOL = "BEST_PER_SYMBOL"
    MERGE_BY_SYMBOL_TIMEFRAME = "MERGE_BY_SYMBOL_TIMEFRAME"


class BacktestEventType(str, Enum):
    MARKET_BAR = "MARKET_BAR"
    SIGNAL = "SIGNAL"
    ORDER_INTENT = "ORDER_INTENT"
    FILL = "FILL"
    POSITION_UPDATE = "POSITION_UPDATE"
    PORTFOLIO_SNAPSHOT = "PORTFOLIO_SNAPSHOT"
    EQUITY_UPDATE = "EQUITY_UPDATE"
    WARNING = "WARNING"
    ERROR = "ERROR"

class BacktestRunStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"

class BacktestOrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"

class BacktestOrderType(str, Enum):
    MARKET = "MARKET"
    NEXT_OPEN = "NEXT_OPEN"
    NEXT_CLOSE = "NEXT_CLOSE"

class BacktestFillStatus(str, Enum):
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    REJECTED = "REJECTED"
    SKIPPED = "SKIPPED"

class BacktestPositionSide(str, Enum):
    LONG = "LONG"
    FLAT = "FLAT"
    SHORT = "SHORT"

class BacktestSignalMode(str, Enum):
    WATCH_AS_LONG_CANDIDATE = "WATCH_AS_LONG_CANDIDATE"
    LONG_ONLY = "LONG_ONLY"
    WATCH_ONLY_NO_TRADES = "WATCH_ONLY_NO_TRADES"
    SIGNAL_ACTION_BASED = "SIGNAL_ACTION_BASED"

class BacktestExitMode(str, Enum):
    HOLD_N_BARS = "HOLD_N_BARS"
    OPPOSITE_SIGNAL = "OPPOSITE_SIGNAL"
    END_OF_DATA = "END_OF_DATA"
    STOP_LOSS_TAKE_PROFIT_RESERVED = "STOP_LOSS_TAKE_PROFIT_RESERVED"

class BacktestMetricStatus(str, Enum):
    OK = "OK"
    WARNING = "WARNING"
    INVALID = "INVALID"
    EMPTY = "EMPTY"

class TransactionCostModelType(str, Enum):
    NONE = "NONE"
    FLAT_FEE = "FLAT_FEE"
    BPS = "BPS"
    PER_SHARE = "PER_SHARE"
    COMBINED = "COMBINED"

class SlippageModelType(str, Enum):
    NONE = "NONE"
    FIXED_BPS = "FIXED_BPS"
    VOLUME_PARTICIPATION = "VOLUME_PARTICIPATION"
    SPREAD_PROXY = "SPREAD_PROXY"
    VOLATILITY_ADJUSTED = "VOLATILITY_ADJUSTED"

class LiquidityBucket(str, Enum):
    VERY_LIQUID = "VERY_LIQUID"
    LIQUID = "LIQUID"
    NORMAL = "NORMAL"
    ILLIQUID = "ILLIQUID"
    VERY_ILLIQUID = "VERY_ILLIQUID"
    UNKNOWN = "UNKNOWN"

class TradeStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    PARTIAL = "PARTIAL"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"

class TradeDirection(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    FLAT = "FLAT"

class TradeExitReason(str, Enum):
    HOLD_PERIOD_EXIT = "HOLD_PERIOD_EXIT"
    OPPOSITE_SIGNAL = "OPPOSITE_SIGNAL"
    END_OF_DATA = "END_OF_DATA"
    STOP_LOSS_RESERVED = "STOP_LOSS_RESERVED"
    TAKE_PROFIT_RESERVED = "TAKE_PROFIT_RESERVED"
    MANUAL_RESERVED = "MANUAL_RESERVED"
    UNKNOWN = "UNKNOWN"

class AdvancedMetricStatus(str, Enum):
    OK = "OK"
    WARNING = "WARNING"
    INVALID = "INVALID"
    EMPTY = "EMPTY"

class DrawdownState(str, Enum):
    NEW_HIGH = "NEW_HIGH"
    DRAWDOWN = "DRAWDOWN"
    RECOVERY = "RECOVERY"
    UNKNOWN = "UNKNOWN"

class BenchmarkType(str, Enum):
    ETF = "ETF"
    INDEX_PROXY = "INDEX_PROXY"
    CASH = "CASH"
    CUSTOM_SYMBOL = "CUSTOM_SYMBOL"
    STRATEGY_BASELINE = "STRATEGY_BASELINE"

class BenchmarkName(str, Enum):
    SPY = "SPY"
    QQQ = "QQQ"
    IWM = "IWM"
    DIA = "DIA"
    VTI = "VTI"
    CASH = "CASH"

class BenchmarkComparisonStatus(str, Enum):
    OK = "OK"
    WARNING = "WARNING"
    FAILED = "FAILED"
    EMPTY = "EMPTY"

class BaselineMode(str, Enum):
    BUY_AND_HOLD = "BUY_AND_HOLD"
    CASH_ONLY = "CASH_ONLY"
    EQUAL_WEIGHT_BASKET = "EQUAL_WEIGHT_BASKET"
    SINGLE_SYMBOL = "SINGLE_SYMBOL"

class AttributionDimension(str, Enum):
    STRATEGY = "STRATEGY"
    SYMBOL = "SYMBOL"
    TIMEFRAME = "TIMEFRAME"
    ACTION = "ACTION"
    MONTH = "MONTH"
    YEAR = "YEAR"
    HOLDING_PERIOD = "HOLDING_PERIOD"
    UNKNOWN = "UNKNOWN"

class AttributionStatus(str, Enum):
    OK = "OK"
    WARNING = "WARNING"
    EMPTY = "EMPTY"
    INVALID = "INVALID"

class RelativePerformanceBucket(str, Enum):
    OUTPERFORMED = "OUTPERFORMED"
    UNDERPERFORMED = "UNDERPERFORMED"
    MATCHED = "MATCHED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"
from enum import Enum

class WalkForwardMode(str, Enum):
    ROLLING = "ROLLING"
    ANCHORED = "ANCHORED"
    EXPANDING = "EXPANDING"
    CUSTOM = "CUSTOM"

class WalkForwardWindowStatus(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"

class WalkForwardSegmentType(str, Enum):
    IN_SAMPLE = "IN_SAMPLE"
    OUT_OF_SAMPLE = "OUT_OF_SAMPLE"
    FULL_WINDOW = "FULL_WINDOW"

class WalkForwardRunStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"

class WalkForwardMetricStatus(str, Enum):
    OK = "OK"
    WARNING = "WARNING"
    INVALID = "INVALID"
    EMPTY = "EMPTY"

class WalkForwardStabilityBucket(str, Enum):
    STABLE = "STABLE"
    MODERATE = "MODERATE"
    UNSTABLE = "UNSTABLE"
    SEVERELY_UNSTABLE = "SEVERELY_UNSTABLE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class OutOfSampleResultBucket(str, Enum):
    STRONG = "STRONG"
    ACCEPTABLE = "ACCEPTABLE"
    WEAK = "WEAK"
    FAILED = "FAILED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class ParameterGridType(str, Enum):
    SINGLE_PARAMETER = "SINGLE_PARAMETER"
    TWO_PARAMETER = "TWO_PARAMETER"
    MULTI_PARAMETER = "MULTI_PARAMETER"
    LOCAL_NEIGHBORHOOD = "LOCAL_NEIGHBORHOOD"
    CUSTOM = "CUSTOM"

class ParameterValueType(str, Enum):
    INT = "INT"
    FLOAT = "FLOAT"
    BOOL = "BOOL"
    STR = "STR"
    CATEGORICAL = "CATEGORICAL"

class SensitivityRunStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    EMPTY = "EMPTY"

class SensitivityCellStatus(str, Enum):
    NOT_RUN = "NOT_RUN"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    INVALID = "INVALID"

class StabilityBucket(str, Enum):
    VERY_STABLE = "VERY_STABLE"
    STABLE = "STABLE"
    MODERATE = "MODERATE"
    FRAGILE = "FRAGILE"
    VERY_FRAGILE = "VERY_FRAGILE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class ParameterZoneType(str, Enum):
    ROBUST_REGION = "ROBUST_REGION"
    FRAGILE_REGION = "FRAGILE_REGION"
    NEUTRAL_REGION = "NEUTRAL_REGION"
    OUTLIER_REGION = "OUTLIER_REGION"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"

class OverfitRiskHint(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class SensitivityMetricName(str, Enum):
    RETURN_PCT = "RETURN_PCT"
    MAX_DRAWDOWN_PCT = "MAX_DRAWDOWN_PCT"
    WIN_RATE = "WIN_RATE"
    PROFIT_FACTOR = "PROFIT_FACTOR"
    SHARPE_LIKE = "SHARPE_LIKE"
    ROBUSTNESS_SCORE = "ROBUSTNESS_SCORE"
    OOS_RETURN_PCT = "OOS_RETURN_PCT"
    STABILITY_SCORE = "STABILITY_SCORE"


class RiskDecisionStatus(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REDUCED = "REDUCED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    SKIPPED = "SKIPPED"
    ERROR = "ERROR"
    UNKNOWN = "UNKNOWN"

class RiskRejectionReason(str, Enum):
    INSUFFICIENT_CASH = "INSUFFICIENT_CASH"
    MAX_POSITION_SIZE_EXCEEDED = "MAX_POSITION_SIZE_EXCEEDED"
    MAX_SYMBOL_EXPOSURE_EXCEEDED = "MAX_SYMBOL_EXPOSURE_EXCEEDED"
    MAX_STRATEGY_EXPOSURE_EXCEEDED = "MAX_STRATEGY_EXPOSURE_EXCEEDED"
    MAX_PORTFOLIO_EXPOSURE_EXCEEDED = "MAX_PORTFOLIO_EXPOSURE_EXCEEDED"
    MAX_OPEN_POSITIONS_EXCEEDED = "MAX_OPEN_POSITIONS_EXCEEDED"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LOW_LIQUIDITY = "LOW_LIQUIDITY"
    HIGH_RISK_FLAGS = "HIGH_RISK_FLAGS"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    LOW_RANK_SCORE = "LOW_RANK_SCORE"
    SHORT_NOT_ALLOWED = "SHORT_NOT_ALLOWED"
    MISSING_PRICE = "MISSING_PRICE"
    MISSING_VOLATILITY_DATA = "MISSING_VOLATILITY_DATA"
    INVALID_CANDIDATE = "INVALID_CANDIDATE"
    UNKNOWN = "UNKNOWN"

class PositionSizingMethod(str, Enum):
    FIXED_NOTIONAL = "FIXED_NOTIONAL"
    FIXED_FRACTIONAL = "FIXED_FRACTIONAL"
    VOLATILITY_ADJUSTED = "VOLATILITY_ADJUSTED"
    ATR_RISK = "ATR_RISK"
    EQUAL_WEIGHT = "EQUAL_WEIGHT"
    ZERO_SIZE = "ZERO_SIZE"

class ExposureLimitType(str, Enum):
    PORTFOLIO = "PORTFOLIO"
    SYMBOL = "SYMBOL"
    STRATEGY = "STRATEGY"
    TIMEFRAME = "TIMEFRAME"
    SECTOR_RESERVED = "SECTOR_RESERVED"
    ASSET_CLASS_RESERVED = "ASSET_CLASS_RESERVED"

class RiskSeverity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class RiskCheckStatus(str, Enum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    WARNING = "WARNING"
    SKIPPED = "SKIPPED"
    ERROR = "ERROR"

class RiskRunStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    EMPTY = "EMPTY"

class PortfolioConstructionStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    EMPTY = "EMPTY"

class PortfolioCandidateStatus(str, Enum):
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CAPPED = "CAPPED"
    REDUCED = "REDUCED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    UNKNOWN = "UNKNOWN"

class AllocationMethod(str, Enum):
    EQUAL_WEIGHT = "EQUAL_WEIGHT"
    RANK_WEIGHTED = "RANK_WEIGHTED"
    RISK_SCORE_WEIGHTED = "RISK_SCORE_WEIGHTED"
    VOLATILITY_ADJUSTED = "VOLATILITY_ADJUSTED"
    NOTIONAL_FROM_RISK_DECISION = "NOTIONAL_FROM_RISK_DECISION"
    HYBRID_BASELINE = "HYBRID_BASELINE"
    ZERO_ALLOCATION = "ZERO_ALLOCATION"

class AllocationStatus(str, Enum):
    ALLOCATED = "ALLOCATED"
    CAPPED = "CAPPED"
    REDUCED = "REDUCED"
    REJECTED = "REJECTED"
    ZERO = "ZERO"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    ERROR = "ERROR"

class RiskBudgetType(str, Enum):
    PORTFOLIO = "PORTFOLIO"
    SYMBOL = "SYMBOL"
    STRATEGY = "STRATEGY"
    TIMEFRAME = "TIMEFRAME"
    VOLATILITY_BUCKET = "VOLATILITY_BUCKET"
    SECTOR_RESERVED = "SECTOR_RESERVED"
    ASSET_CLASS_RESERVED = "ASSET_CLASS_RESERVED"

class RiskBudgetStatus(str, Enum):
    WITHIN_BUDGET = "WITHIN_BUDGET"
    BREACHED = "BREACHED"
    WARNING = "WARNING"
    NOT_EVALUATED = "NOT_EVALUATED"
    UNKNOWN = "UNKNOWN"

class ConcentrationGuardType(str, Enum):
    MAX_SYMBOL_WEIGHT = "MAX_SYMBOL_WEIGHT"
    MAX_STRATEGY_WEIGHT = "MAX_STRATEGY_WEIGHT"
    MAX_TIMEFRAME_WEIGHT = "MAX_TIMEFRAME_WEIGHT"
    MAX_SINGLE_CANDIDATE_WEIGHT = "MAX_SINGLE_CANDIDATE_WEIGHT"
    MAX_CORRELATED_GROUP_RESERVED = "MAX_CORRELATED_GROUP_RESERVED"
    SECTOR_RESERVED = "SECTOR_RESERVED"

class PortfolioReviewStatus(str, Enum):
    ACCEPTABLE = "ACCEPTABLE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REJECTED = "REJECTED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"


class BasketReplaySource(str, Enum):
    PORTFOLIO_BASKET = "portfolio_basket"
    ALLOCATION_RESULTS = "allocation_results"
    RISK_DECISIONS = "risk_decisions"
    SELECTED_CANDIDATES = "selected_candidates"
    SIGNALS = "signals"
    CUSTOM = "custom"

class BasketSimulationStatus(str, Enum):
    NOT_STARTED = "not_started"
    RUNNING = "running"
    COMPLETED = "completed"
    PARTIAL_SUCCESS = "partial_success"
    FAILED = "failed"
    EMPTY = "empty"

class BasketEntryMode(str, Enum):
    ENTER_ALL_AT_START = "enter_all_at_start"
    ENTER_ON_SIGNAL_TIME = "enter_on_signal_time"
    ENTER_ON_ALLOCATION_TIME = "enter_on_allocation_time"
    STAGGERED_RESERVED = "staggered_reserved"

class BasketExitMode(str, Enum):
    HOLD_N_BARS = "hold_n_bars"
    END_OF_DATA = "end_of_data"
    ALLOCATION_EXIT_RESERVED = "allocation_exit_reserved"
    REBALANCE_RESERVED = "rebalance_reserved"
    STOP_LOSS_TAKE_PROFIT_RESERVED = "stop_loss_take_profit_reserved"

class AllocationReplayMode(str, Enum):
    TARGET_QUANTITY = "target_quantity"
    TARGET_NOTIONAL = "target_notional"
    TARGET_WEIGHT = "target_weight"
    RISK_DECISION_SIZE = "risk_decision_size"
    SIGNAL_DEFAULT_SIZE = "signal_default_size"

class AllocationDriftStatus(str, Enum):
    WITHIN_TOLERANCE = "within_tolerance"
    DRIFT_WARNING = "drift_warning"
    DRIFT_BREACH = "drift_breach"
    NOT_EVALUATED = "not_evaluated"
    UNKNOWN = "unknown"

class BasketReviewStatus(str, Enum):
    ACCEPTABLE = "acceptable"
    NEEDS_REVIEW = "needs_review"
    FAILED = "failed"
    INSUFFICIENT_DATA = "insufficient_data"
    UNKNOWN = "unknown"

class BasketMetricStatus(str, Enum):
    OK = "ok"
    WARNING = "warning"
    INVALID = "invalid"
    EMPTY = "empty"

class RuntimeMode(str, Enum):
    MANUAL_ONCE = "manual_once"
    DRY_RUN = "dry_run"
    SCHEDULE_PLAN_ONLY = "schedule_plan_only"
    LOCAL_SCAN_LOOP = "local_scan_loop"
    SAFE_TEST = "safe_test"

class RuntimeRunStatus(str, Enum):
    NOT_STARTED = "not_started"
    RUNNING = "running"
    COMPLETED = "completed"
    PARTIAL_SUCCESS = "partial_success"
    FAILED = "failed"
    SKIPPED = "skipped"
    STOPPED = "stopped"
    LOCKED = "locked"
    EMPTY = "empty"

class PipelineStepName(str, Enum):
    PREFLIGHT = "preflight"
    UNIVERSE_RESOLVE = "universe_resolve"
    DATA_REFRESH = "data_refresh"
    DATA_READINESS = "data_readiness"
    FEATURE_PIPELINE = "feature_pipeline"
    STRATEGY_RUN = "strategy_run"
    SIGNAL_SCORING = "signal_scoring"
    SIGNAL_RANKING = "signal_ranking"
    CANDIDATE_SELECTION = "candidate_selection"
    RISK_EVALUATION = "risk_evaluation"

    PORTFOLIO_CONSTRUCTION = "portfolio_construction"
    PAPER_TRADING = "paper_trading"
    PAPER_ANALYTICS = "paper_analytics"
    SCAN_REPORT = "scan_report"

    CLEANUP = "cleanup"
    NOTIFICATION = "notification"

class PipelineStepStatus(str, Enum):
    NOT_STARTED = "not_started"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"
    PARTIAL_SUCCESS = "partial_success"
    STOPPED = "stopped"

class RuntimeEventType(str, Enum):
    RUN_STARTED = "run_started"
    RUN_COMPLETED = "run_completed"
    RUN_FAILED = "run_failed"
    RUN_STOPPED = "run_stopped"
    STEP_STARTED = "step_started"
    STEP_COMPLETED = "step_completed"
    STEP_FAILED = "step_failed"
    STEP_SKIPPED = "step_skipped"
    LOCK_ACQUIRED = "lock_acquired"
    LOCK_RELEASED = "lock_released"
    SAFE_STOP_REQUESTED = "safe_stop_requested"
    WARNING = "warning"
    ERROR = "error"

class ScanScope(str, Enum):
    EXPLICIT_SYMBOLS = "explicit_symbols"
    LATEST_ELIGIBLE_UNIVERSE = "latest_eligible_universe"
    ACTIVE_UNIVERSE = "active_universe"
    SMALL_TEST_SET = "small_test_set"

class ScanOutputLevel(str, Enum):
    MINIMAL = "minimal"
    NORMAL = "normal"
    VERBOSE = "verbose"
    DEBUG = "debug"

class RetryPolicy(str, Enum):
    NONE = "none"
    STEP_ONCE = "step_once"
    STEP_TWICE = "step_twice"
    SAFE_LIMITED = "safe_limited"

class NotificationChannel(str, Enum):
    LOG_ONLY = "LOG_ONLY"
    TELEGRAM = "TELEGRAM"
    FILE = "FILE"
    DRY_RUN = "DRY_RUN"

class NotificationType(str, Enum):
    REGIME_MAP_REPORT = "REGIME_MAP_REPORT"
    REGIME_TRANSITION_WARNING = "REGIME_TRANSITION_WARNING"
    REGIME_ALIGNMENT_WARNING = "REGIME_ALIGNMENT_WARNING"
    COST_ROBUSTNESS_REPORT = "COST_ROBUSTNESS_REPORT"
    COST_FRAGILITY_WARNING = "COST_FRAGILITY_WARNING"
    EXECUTION_SENSITIVITY_WARNING = "EXECUTION_SENSITIVITY_WARNING"
    CALENDAR_SESSION_REPORT = "CALENDAR_SESSION_REPORT"
    CORPORATE_ACTION_WARNING = "CORPORATE_ACTION_WARNING"
    ADJUSTED_PRICE_WARNING = "ADJUSTED_PRICE_WARNING"
    PROVIDER_HEALTH_REPORT = "PROVIDER_HEALTH_REPORT"
    PROVIDER_QUALITY_WARNING = "PROVIDER_QUALITY_WARNING"
    PROVIDER_FALLBACK_REPORT = "PROVIDER_FALLBACK_REPORT"
    SCHEDULER_REPORT = "SCHEDULER_REPORT"
    LOCK_WARNING = "LOCK_WARNING"
    CONCURRENCY_BLOCKED = "CONCURRENCY_BLOCKED"
    INCIDENT_REPORT = "INCIDENT_REPORT"
    RECOVERY_PLAN_REPORT = "RECOVERY_PLAN_REPORT"
    ROLLBACK_DRY_RUN_REPORT = "ROLLBACK_DRY_RUN_REPORT"
    SCAN_SUMMARY = "SCAN_SUMMARY"
    SIGNAL_CANDIDATE = "SIGNAL_CANDIDATE"
    SELECTED_CANDIDATES = "SELECTED_CANDIDATES"
    RISK_DECISIONS = "RISK_DECISIONS"
    PORTFOLIO_BASKET = "PORTFOLIO_BASKET"
    BACKTEST_SUMMARY = "BACKTEST_SUMMARY"
    RUNTIME_WARNING = "RUNTIME_WARNING"
    RUNTIME_ERROR = "RUNTIME_ERROR"
    HEALTH_SUMMARY = "HEALTH_SUMMARY"
    CUSTOM = "CUSTOM"
    PAPER_PERFORMANCE_REPORT = "PAPER_PERFORMANCE_REPORT"
    PAPER_RISK_REPORT = "PAPER_RISK_REPORT"
    PAPER_DRAWDOWN_WARNING = "PAPER_DRAWDOWN_WARNING"
    COMPARISON_REPORT = "COMPARISON_REPORT"
    EXECUTION_GAP_WARNING = "EXECUTION_GAP_WARNING"
    SIGNAL_DRIFT_WARNING = "SIGNAL_DRIFT_WARNING"
    ILLIQUID_SYMBOL_WARNING = "ILLIQUID_SYMBOL_WARNING"
    TRADABILITY_BLOCKED = "TRADABILITY_BLOCKED"
    EXECUTION_REALISM_FAILED = "EXECUTION_REALISM_FAILED"
    REGIME_COST_REPORT = "REGIME_COST_REPORT"
    ADAPTIVE_EXECUTION_WARNING = "ADAPTIVE_EXECUTION_WARNING"
    REGIME_COST_BLOCK_WARNING = "REGIME_COST_BLOCK_WARNING"

    RESOURCE_PROFILE_REPORT = "RESOURCE_PROFILE_REPORT"
    BUDGET_CALIBRATION_REPORT = "BUDGET_CALIBRATION_REPORT"
    THROTTLING_WARNING = "THROTTLING_WARNING"
    UNIVERSE_LIFECYCLE_REPORT = "UNIVERSE_LIFECYCLE_REPORT"
    SURVIVORSHIP_BIAS_WARNING = "SURVIVORSHIP_BIAS_WARNING"
    DELISTING_AWARENESS_WARNING = "DELISTING_AWARENESS_WARNING"
    LIQUIDITY_WARNING = "LIQUIDITY_WARNING"
    TRADABILITY_GUARD_REPORT = "TRADABILITY_GUARD_REPORT"
    EXECUTION_REALISM_WARNING = "EXECUTION_REALISM_WARNING"


    OPERATIONAL_HEALTH_REPORT = "OPERATIONAL_HEALTH_REPORT"
    OBSERVABILITY_WARNING = "OBSERVABILITY_WARNING"
    LOG_ROTATION_REPORT = "LOG_ROTATION_REPORT"
    PERFORMANCE_BASELINE_REPORT = "PERFORMANCE_BASELINE_REPORT"
    SLA_THRESHOLD_WARNING = "SLA_THRESHOLD_WARNING"
    RUNTIME_REGRESSION_ALERT = "RUNTIME_REGRESSION_ALERT"

class NotificationPriority(str, Enum):
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class NotificationStatus(str, Enum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    SKIPPED = "SKIPPED"
    SENT = "SENT"
    FAILED = "FAILED"
    DRY_RUN = "DRY_RUN"
    SUPPRESSED = "SUPPRESSED"
    RATE_LIMITED = "RATE_LIMITED"

class NotificationDispatchStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    EMPTY = "EMPTY"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"

class TelegramParseMode(str, Enum):
    NONE = "NONE"
    MARKDOWN = "MARKDOWN"
    HTML = "HTML"

class NotificationSuppressionReason(str, Enum):
    DUPLICATE = "DUPLICATE"
    RATE_LIMITED = "RATE_LIMITED"
    CHANNEL_DISABLED = "CHANNEL_DISABLED"
    MISSING_TOKEN = "MISSING_TOKEN"
    MISSING_CHAT_ID = "MISSING_CHAT_ID"
    EMPTY_MESSAGE = "EMPTY_MESSAGE"
    TOO_LONG = "TOO_LONG"
    DRY_RUN = "DRY_RUN"
    DISABLED_BY_CONFIG = "DISABLED_BY_CONFIG"
    UNKNOWN = "UNKNOWN"

class AlertType(str, Enum):
    REGIME_TRANSITION_RISK_HIGH = "REGIME_TRANSITION_RISK_HIGH"
    REGIME_ALIGNMENT_CONFLICT = "REGIME_ALIGNMENT_CONFLICT"
    REGIME_MAP_DEGRADED = "REGIME_MAP_DEGRADED"
    COST_ROBUSTNESS_FAILED = "COST_ROBUSTNESS_FAILED"
    COST_FRAGILITY_DETECTED = "COST_FRAGILITY_DETECTED"
    EXECUTION_SENSITIVITY_HIGH = "EXECUTION_SENSITIVITY_HIGH"
    SESSION_VALIDATION_FAILED = "SESSION_VALIDATION_FAILED"
    CORPORATE_ACTION_GUARD_TRIGGERED = "CORPORATE_ACTION_GUARD_TRIGGERED"
    ADJUSTED_PRICE_INCONSISTENCY = "ADJUSTED_PRICE_INCONSISTENCY"
    PROVIDER_DEGRADED = "PROVIDER_DEGRADED"
    PROVIDER_FALLBACK_USED = "PROVIDER_FALLBACK_USED"
    PROVIDER_VALIDATION_FAILED = "PROVIDER_VALIDATION_FAILED"
    STALE_LOCK_DETECTED = "STALE_LOCK_DETECTED"
    CONCURRENCY_BLOCKED = "CONCURRENCY_BLOCKED"
    SCHEDULER_JOB_FAILED = "SCHEDULER_JOB_FAILED"
    INCIDENT_CRITICAL = "INCIDENT_CRITICAL"
    RECOVERY_BLOCKED = "RECOVERY_BLOCKED"
    ROLLBACK_BLOCKED = "ROLLBACK_BLOCKED"
    SCAN_COMPLETED = "SCAN_COMPLETED"
    SCAN_FAILED = "SCAN_FAILED"
    HIGH_QUALITY_CANDIDATE = "HIGH_QUALITY_CANDIDATE"
    SELECTED_CANDIDATE_BATCH = "SELECTED_CANDIDATE_BATCH"
    RISK_APPROVED_BATCH = "RISK_APPROVED_BATCH"
    RISK_REJECTED_WARNING = "RISK_REJECTED_WARNING"
    PORTFOLIO_BASKET_REVIEW = "PORTFOLIO_BASKET_REVIEW"
    PORTFOLIO_CONCENTRATION_WARNING = "PORTFOLIO_CONCENTRATION_WARNING"
    RUNTIME_WARNING = "RUNTIME_WARNING"
    RUNTIME_ERROR = "RUNTIME_ERROR"
    HEALTH_WARNING = "HEALTH_WARNING"
    HEALTH_ERROR = "HEALTH_ERROR"
    CUSTOM = "CUSTOM"
    PAPER_DRAWDOWN_WARNING = "PAPER_DRAWDOWN_WARNING"
    PAPER_RISK_LIMIT_BREACH = "PAPER_RISK_LIMIT_BREACH"
    PAPER_PERFORMANCE_DETERIORATION = "PAPER_PERFORMANCE_DETERIORATION"
    EXECUTION_GAP_WARNING = "EXECUTION_GAP_WARNING"
    SIGNAL_DRIFT_WARNING = "SIGNAL_DRIFT_WARNING"
    ILLIQUID_SYMBOL_WARNING = "ILLIQUID_SYMBOL_WARNING"
    TRADABILITY_BLOCKED = "TRADABILITY_BLOCKED"
    EXECUTION_REALISM_FAILED = "EXECUTION_REALISM_FAILED"
    REGIME_COST_REPORT = "REGIME_COST_REPORT"
    ADAPTIVE_EXECUTION_WARNING = "ADAPTIVE_EXECUTION_WARNING"
    REGIME_COST_BLOCK_WARNING = "REGIME_COST_BLOCK_WARNING"

    PAPER_BACKTEST_DIVERGENCE = "PAPER_BACKTEST_DIVERGENCE"
    RESOURCE_BUDGET_WARNING = "RESOURCE_BUDGET_WARNING"
    THROTTLING_BLOCKED = "THROTTLING_BLOCKED"
    REGIME_COST_HIGH_RISK = "REGIME_COST_HIGH_RISK"
    ADAPTIVE_EXECUTION_BLOCKED = "ADAPTIVE_EXECUTION_BLOCKED"
    REGIME_COST_MODEL_DEGRADED = "REGIME_COST_MODEL_DEGRADED"
    CALIBRATION_REVIEW_REQUIRED = "CALIBRATION_REVIEW_REQUIRED"
    SURVIVORSHIP_BIAS_RISK = "SURVIVORSHIP_BIAS_RISK"
    SYMBOL_DELISTING_RISK = "SYMBOL_DELISTING_RISK"
    SYMBOL_LIFECYCLE_REVIEW_REQUIRED = "SYMBOL_LIFECYCLE_REVIEW_REQUIRED"

    OPERATIONAL_HEALTH_WARNING = "OPERATIONAL_HEALTH_WARNING"
    DISK_USAGE_WARNING = "DISK_USAGE_WARNING"
    OBSERVABILITY_SAFETY_BLOCK = "OBSERVABILITY_SAFETY_BLOCK"
    SLA_THRESHOLD_BREACH = "SLA_THRESHOLD_BREACH"
    RUNTIME_REGRESSION_DETECTED = "RUNTIME_REGRESSION_DETECTED"
    PERFORMANCE_BASELINE_STALE = "PERFORMANCE_BASELINE_STALE"

class AlertSeverity(str, Enum):
    INFO = "INFO"
    NOTICE = "NOTICE"
    WARNING = "WARNING"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class AlertDecisionStatus(str, Enum):
    CREATED = "CREATED"
    SUPPRESSED = "SUPPRESSED"
    ROUTED = "ROUTED"
    QUEUED = "QUEUED"
    DISPATCHED = "DISPATCHED"
    FAILED = "FAILED"
    DRY_RUN = "DRY_RUN"
    SKIPPED = "SKIPPED"

class AlertSuppressionReason(str, Enum):
    BELOW_THRESHOLD = "BELOW_THRESHOLD"
    SEVERITY_FILTERED = "SEVERITY_FILTERED"
    DUPLICATE = "DUPLICATE"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    CHANNEL_DISABLED = "CHANNEL_DISABLED"
    NOTIFICATION_DISABLED = "NOTIFICATION_DISABLED"
    EMPTY_PAYLOAD = "EMPTY_PAYLOAD"
    POLICY_DISABLED = "POLICY_DISABLED"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    UNKNOWN = "UNKNOWN"

class AlertConditionOperator(str, Enum):
    GT = "GT"
    GTE = "GTE"
    LT = "LT"
    LTE = "LTE"
    EQ = "EQ"
    NEQ = "NEQ"
    BETWEEN = "BETWEEN"
    IN = "IN"
    EXISTS = "EXISTS"
    IS_TRUE = "IS_TRUE"
    IS_FALSE = "IS_FALSE"

class AlertRouteTarget(str, Enum):
    DRY_RUN = "DRY_RUN"
    LOG_ONLY = "LOG_ONLY"
    FILE = "FILE"
    TELEGRAM = "TELEGRAM"
    NONE = "NONE"

class AlertPolicyScope(str, Enum):
    SCAN = "SCAN"
    CANDIDATE = "CANDIDATE"
    RISK = "RISK"
    PORTFOLIO = "PORTFOLIO"
    RUNTIME = "RUNTIME"
    HEALTH = "HEALTH"
    GLOBAL = "GLOBAL"
    COMPARISON = "COMPARISON"

class PaperAccountStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    CLOSED = "CLOSED"
    ERROR = "ERROR"
    UNKNOWN = "UNKNOWN"

class PaperOrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"

class PaperOrderType(str, Enum):
    MARKET = "MARKET"
    NEXT_OPEN = "NEXT_OPEN"
    NEXT_CLOSE = "NEXT_CLOSE"
    LIMIT_RESERVED = "LIMIT_RESERVED"
    STOP_RESERVED = "STOP_RESERVED"

class PaperOrderStatus(str, Enum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    ACCEPTED = "ACCEPTED"
    QUEUED = "QUEUED"
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    SKIPPED = "SKIPPED"
    ERROR = "ERROR"

class PaperFillStatus(str, Enum):
    FILLED = "FILLED"
    PARTIAL = "PARTIAL"
    REJECTED = "REJECTED"
    SKIPPED = "SKIPPED"
    ERROR = "ERROR"

class PaperPositionSide(str, Enum):
    LONG = "LONG"
    FLAT = "FLAT"
    SHORT_RESERVED = "SHORT_RESERVED"

class PaperCashLedgerEntryType(str, Enum):
    STARTING_CASH = "STARTING_CASH"
    BUY_DEBIT = "BUY_DEBIT"
    SELL_CREDIT = "SELL_CREDIT"
    FEE_DEBIT = "FEE_DEBIT"
    ADJUSTMENT = "ADJUSTMENT"
    REALIZED_PNL = "REALIZED_PNL"
    RESERVED = "RESERVED"

class PaperTradeStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    PARTIAL = "PARTIAL"
    CANCELLED = "CANCELLED"
    ERROR = "ERROR"

class PaperEngineStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    EMPTY = "EMPTY"

class PaperOrderSource(str, Enum):
    RISK_DECISION = "RISK_DECISION"
    PORTFOLIO_ALLOCATION = "PORTFOLIO_ALLOCATION"
    SELECTED_CANDIDATE = "SELECTED_CANDIDATE"
    SIGNAL = "SIGNAL"
    MANUAL_RESEARCH = "MANUAL_RESEARCH"
    CUSTOM = "CUSTOM"

class PaperExecutionMode(str, Enum):
    LOCAL_SIMULATED = "LOCAL_SIMULATED"
    DRY_RUN = "DRY_RUN"
    VALIDATE_ONLY = "VALIDATE_ONLY"

class PaperRejectReason(str, Enum):
    INSUFFICIENT_CASH = "INSUFFICIENT_CASH"
    INVALID_PRICE = "INVALID_PRICE"
    INVALID_QUANTITY = "INVALID_QUANTITY"
    SHORT_NOT_ALLOWED = "SHORT_NOT_ALLOWED"
    DUPLICATE_POSITION = "DUPLICATE_POSITION"
    MAX_POSITIONS_EXCEEDED = "MAX_POSITIONS_EXCEEDED"
    MARKET_DATA_MISSING = "MARKET_DATA_MISSING"
    RISK_REJECTED = "RISK_REJECTED"
    ALLOCATION_REJECTED = "ALLOCATION_REJECTED"
    ORDER_EXPIRED = "ORDER_EXPIRED"
    ACCOUNT_PAUSED = "ACCOUNT_PAUSED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    UNKNOWN = "UNKNOWN"


class PaperAnalyticsStatus(str, Enum):
    CREATED = "CREATED"
    COMPLETED = "COMPLETED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    EMPTY = "EMPTY"

class PaperMetricStatus(str, Enum):
    OK = "OK"
    WARNING = "WARNING"
    INVALID = "INVALID"
    EMPTY = "EMPTY"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"

class PaperRiskLevel(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"

class PaperDrawdownStatus(str, Enum):
    NORMAL = "NORMAL"
    WARNING = "WARNING"
    BREACH = "BREACH"
    CRITICAL = "CRITICAL"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class PaperRiskLimitStatus(str, Enum):
    WITHIN_LIMIT = "WITHIN_LIMIT"
    WARNING = "WARNING"
    BREACHED = "BREACHED"
    CRITICAL = "CRITICAL"
    NOT_EVALUATED = "NOT_EVALUATED"

class PaperPerformanceBucket(str, Enum):
    STRONG = "STRONG"
    ACCEPTABLE = "ACCEPTABLE"
    WEAK = "WEAK"
    POOR = "POOR"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class PaperTrendDirection(str, Enum):
    IMPROVING = "IMPROVING"
    STABLE = "STABLE"
    DETERIORATING = "DETERIORATING"
    MIXED = "MIXED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class PaperAnalyticsReportType(str, Enum):
    PERFORMANCE = "PERFORMANCE"
    RISK = "RISK"
    DRAWDOWN = "DRAWDOWN"
    EXPOSURE = "EXPOSURE"
    TRADE_ANALYTICS = "TRADE_ANALYTICS"
    ROLLING_METRICS = "ROLLING_METRICS"
    FULL_SUMMARY = "FULL_SUMMARY"


class ComparisonStatus(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    EMPTY = "EMPTY"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"

class ComparisonSourceType(str, Enum):
    PAPER_RUN = "PAPER_RUN"
    BACKTEST_RUN = "BACKTEST_RUN"
    BASKET_BACKTEST_RUN = "BASKET_BACKTEST_RUN"
    WALK_FORWARD_RUN = "WALK_FORWARD_RUN"
    SCAN_RUN = "SCAN_RUN"
    SIGNAL_FILE = "SIGNAL_FILE"
    CANDIDATE_FILE = "CANDIDATE_FILE"
    CUSTOM = "CUSTOM"

class MatchStatus(str, Enum):
    MATCHED = "MATCHED"
    PARTIAL_MATCH = "PARTIAL_MATCH"
    PAPER_ONLY = "PAPER_ONLY"
    BACKTEST_ONLY = "BACKTEST_ONLY"
    UNMATCHED = "UNMATCHED"
    AMBIGUOUS = "AMBIGUOUS"
    SKIPPED = "SKIPPED"

class ComparisonMetricStatus(str, Enum):
    OK = "OK"
    WARNING = "WARNING"
    INVALID = "INVALID"
    EMPTY = "EMPTY"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"

class ExecutionRealismBucket(str, Enum):
    HIGH_REALISM = "HIGH_REALISM"
    ACCEPTABLE_REALISM = "ACCEPTABLE_REALISM"
    MODERATE_GAP = "MODERATE_GAP"
    LARGE_GAP = "LARGE_GAP"
    SEVERE_GAP = "SEVERE_GAP"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class SignalDriftStatus(str, Enum):
    NO_DRIFT = "NO_DRIFT"
    LOW_DRIFT = "LOW_DRIFT"
    MODERATE_DRIFT = "MODERATE_DRIFT"
    HIGH_DRIFT = "HIGH_DRIFT"
    SEVERE_DRIFT = "SEVERE_DRIFT"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class GapSeverity(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"

class GapDirection(str, Enum):
    PAPER_BETTER = "PAPER_BETTER"
    BACKTEST_BETTER = "BACKTEST_BETTER"
    NEUTRAL = "NEUTRAL"
    MIXED = "MIXED"
    UNKNOWN = "UNKNOWN"

class ComparisonReportType(str, Enum):
    PAPER_VS_BACKTEST = "PAPER_VS_BACKTEST"
    SIGNAL_DRIFT = "SIGNAL_DRIFT"
    EXECUTION_REALISM = "EXECUTION_REALISM"
    FULL_COMPARISON = "FULL_COMPARISON"
    CUSTOM = "CUSTOM"

class QualityDimension(str, Enum):
    DATA = "data"
    FEATURE = "feature"
    SIGNAL = "signal"
    STRATEGY = "strategy"
    BACKTEST = "backtest"
    ROBUSTNESS = "robustness"
    RISK = "risk"
    PORTFOLIO = "portfolio"
    PAPER = "paper"
    COMPARISON = "comparison"
    RUNTIME = "runtime"
    NOTIFICATION = "notification"
    DOCUMENTATION = "documentation"
    TESTING = "testing"
    SAFETY = "safety"
    OVERALL = "overall"

class QualityStatus(str, Enum):
    PASS = "pass"
    WARN = "warn"
    FAIL = "fail"
    SKIPPED = "skipped"
    INSUFFICIENT_DATA = "insufficient_data"
    UNKNOWN = "unknown"

class QualitySeverity(str, Enum):
    INFO = "info"
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"
    CRITICAL = "critical"

class ReadinessGateStatus(str, Enum):
    PASSED = "passed"
    WARNING = "warning"
    FAILED = "failed"
    BLOCKED = "blocked"
    SKIPPED = "skipped"
    INSUFFICIENT_DATA = "insufficient_data"
    UNKNOWN = "unknown"

class AcceptanceDecision(str, Enum):
    ACCEPTED_FOR_LOCAL_RESEARCH = "accepted_for_local_research"
    ACCEPTED_WITH_WARNINGS = "accepted_with_warnings"
    NOT_ACCEPTED = "not_accepted"
    BLOCKED = "blocked"
    INSUFFICIENT_DATA = "insufficient_data"
    UNKNOWN = "unknown"

class AcceptanceScope(str, Enum):
    LOCAL_RESEARCH = "local_research"
    LOCAL_PAPER_SIMULATION = "local_paper_simulation"
    BACKTEST_RESEARCH = "backtest_research"
    RUNTIME_SCAN = "runtime_scan"
    NOTIFICATION_DRY_RUN = "notification_dry_run"
    FULL_LOCAL_STACK = "full_local_stack"

class GateRuleOperator(str, Enum):
    GT = "gt"
    GTE = "gte"
    LT = "lt"
    LTE = "lte"
    EQ = "eq"
    NEQ = "neq"
    BETWEEN = "between"
    EXISTS = "exists"
    IS_TRUE = "is_true"
    IS_FALSE = "is_false"

class ArtifactFreshnessStatus(str, Enum):
    FRESH = "fresh"
    STALE = "stale"
    MISSING = "missing"
    NOT_EVALUATED = "not_evaluated"
    UNKNOWN = "unknown"

class QualityReportType(str, Enum):
    SCORECARD = "scorecard"
    READINESS_GATE = "readiness_gate"
    ACCEPTANCE = "acceptance"
    FULL_QUALITY_REVIEW = "full_quality_review"


class RegressionRunStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    EMPTY = "EMPTY"

class RegressionStepName(str, Enum):
    GENERATE_GOLDEN_FIXTURES = "GENERATE_GOLDEN_FIXTURES"
    LOAD_GOLDEN_DATASET = "LOAD_GOLDEN_DATASET"
    DATA_CACHE_REHEARSAL = "DATA_CACHE_REHEARSAL"
    FEATURE_REHEARSAL = "FEATURE_REHEARSAL"
    STRATEGY_REHEARSAL = "STRATEGY_REHEARSAL"
    RANKING_REHEARSAL = "RANKING_REHEARSAL"
    RISK_REHEARSAL = "RISK_REHEARSAL"
    PORTFOLIO_REHEARSAL = "PORTFOLIO_REHEARSAL"
    BASKET_BACKTEST_REHEARSAL = "BASKET_BACKTEST_REHEARSAL"
    PAPER_DRY_RUN_REHEARSAL = "PAPER_DRY_RUN_REHEARSAL"
    PAPER_ANALYTICS_REHEARSAL = "PAPER_ANALYTICS_REHEARSAL"
    COMPARISON_REHEARSAL = "COMPARISON_REHEARSAL"
    QUALITY_GATE_REHEARSAL = "QUALITY_GATE_REHEARSAL"
    NOTIFICATION_DRY_RUN_REHEARSAL = "NOTIFICATION_DRY_RUN_REHEARSAL"
    SNAPSHOT_COMPARISON = "SNAPSHOT_COMPARISON"
    RELEASE_REHEARSAL_REPORT = "RELEASE_REHEARSAL_REPORT"

class RegressionStepStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    RUNNING = "RUNNING"
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    BLOCKED = "BLOCKED"

class GoldenDatasetStatus(str, Enum):
    CREATED = "CREATED"
    VALID = "VALID"
    INVALID = "INVALID"
    MISSING = "MISSING"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"

class SnapshotComparisonStatus(str, Enum):
    MATCH = "MATCH"
    DRIFT = "DRIFT"
    MISSING_BASELINE = "MISSING_BASELINE"
    MISSING_CURRENT = "MISSING_CURRENT"
    INVALID = "INVALID"
    SKIPPED = "SKIPPED"

class RegressionDriftSeverity(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"

class ReleaseCandidateStatus(str, Enum):
    PASSED = "PASSED"
    PASSED_WITH_WARNINGS = "PASSED_WITH_WARNINGS"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class ReleaseRehearsalScope(str, Enum):
    SMOKE_ONLY = "SMOKE_ONLY"
    GOLDEN_SAMPLE = "GOLDEN_SAMPLE"
    FULL_LOCAL_STACK = "FULL_LOCAL_STACK"
    QUALITY_GATE_ONLY = "QUALITY_GATE_ONLY"
    CUSTOM = "CUSTOM"

class RegressionArtifactType(str, Enum):
    DATASET = "DATASET"
    STEP_RESULT = "STEP_RESULT"
    SNAPSHOT = "SNAPSHOT"
    REPORT = "REPORT"
    MANIFEST = "MANIFEST"
    LOG = "LOG"
    QUALITY_RESULT = "QUALITY_RESULT"
    CUSTOM = "CUSTOM"

class ReleaseStatus(str, Enum):
    CREATED = "CREATED"
    BUILDING = "BUILDING"
    BUILT = "BUILT"
    VALIDATED = "VALIDATED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"
    UNKNOWN = "UNKNOWN"

class ReleaseArtifactType(str, Enum):
    SOURCE_CODE = "SOURCE_CODE"
    CONFIG = "CONFIG"
    DOCS = "DOCS"
    TESTS = "TESTS"
    REQUIREMENTS = "REQUIREMENTS"
    REGRESSION_REPORT = "REGRESSION_REPORT"
    QUALITY_REPORT = "QUALITY_REPORT"
    RUNBOOK = "RUNBOOK"
    MAINTENANCE_PLAN = "MAINTENANCE_PLAN"
    BACKUP = "BACKUP"
    MANIFEST = "MANIFEST"
    CHANGELOG = "CHANGELOG"
    CUSTOM = "CUSTOM"

class ReleaseValidationStatus(str, Enum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"
    UNKNOWN = "UNKNOWN"

class RunbookSection(str, Enum):
    OVERVIEW = "OVERVIEW"
    INSTALLATION = "INSTALLATION"
    CONFIGURATION = "CONFIGURATION"
    DAILY_OPERATION = "DAILY_OPERATION"
    WEEKLY_MAINTENANCE = "WEEKLY_MAINTENANCE"
    BACKUP_RESTORE = "BACKUP_RESTORE"
    REGRESSION = "REGRESSION"
    QUALITY_GATE = "QUALITY_GATE"
    PAPER_TRADING = "PAPER_TRADING"
    NOTIFICATIONS = "NOTIFICATIONS"
    TROUBLESHOOTING = "TROUBLESHOOTING"
    SAFETY_LIMITATIONS = "SAFETY_LIMITATIONS"
    COMMAND_REFERENCE = "COMMAND_REFERENCE"

class MaintenanceFrequency(str, Enum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    ON_DEMAND = "ON_DEMAND"
    PRE_RELEASE = "PRE_RELEASE"
    POST_RELEASE = "POST_RELEASE"

class MaintenanceTaskStatus(str, Enum):
    PENDING = "PENDING"
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    NOT_APPLICABLE = "NOT_APPLICABLE"

class BackupStatus(str, Enum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    FAILED = "FAILED"
    RESTORE_DRY_RUN_PASSED = "RESTORE_DRY_RUN_PASSED"
    RESTORE_DRY_RUN_FAILED = "RESTORE_DRY_RUN_FAILED"
    SKIPPED = "SKIPPED"
    UNKNOWN = "UNKNOWN"

class BackupScope(str, Enum):
    CONFIG_ONLY = "CONFIG_ONLY"
    REPORTS_ONLY = "REPORTS_ONLY"
    DATA_CACHE_LIGHT = "DATA_CACHE_LIGHT"
    FULL_LOCAL_STATE = "FULL_LOCAL_STATE"
    RELEASE_ARTIFACTS = "RELEASE_ARTIFACTS"

class ConfigProfileType(str, Enum):
    RESEARCH = "RESEARCH"
    PAPER_DRY_RUN = "PAPER_DRY_RUN"
    REGRESSION_ONLY = "REGRESSION_ONLY"
    NOTIFICATION_DRY_RUN = "NOTIFICATION_DRY_RUN"
    FULL_LOCAL_SAFE = "FULL_LOCAL_SAFE"
    CUSTOM = "CUSTOM"

class UpgradePrecheckStatus(str, Enum):
    PASSED = "PASSED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class ObservabilityEventType(str, Enum):
    COMMAND_STARTED = "COMMAND_STARTED"
    COMMAND_COMPLETED = "COMMAND_COMPLETED"
    COMMAND_FAILED = "COMMAND_FAILED"
    RUN_STARTED = "RUN_STARTED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"
    STEP_STARTED = "STEP_STARTED"
    STEP_COMPLETED = "STEP_COMPLETED"
    STEP_FAILED = "STEP_FAILED"
    WARNING = "WARNING"
    ERROR = "ERROR"
    SAFETY_WARNING = "SAFETY_WARNING"
    SAFETY_BLOCK = "SAFETY_BLOCK"
    METRIC_SNAPSHOT = "METRIC_SNAPSHOT"
    LOG_ROTATION = "LOG_ROTATION"
    RETENTION_WARNING = "RETENTION_WARNING"
    CUSTOM = "CUSTOM"

class ObservabilitySeverity(str, Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class ObservabilityChannel(str, Enum):
    JSONL_LOG = "JSONL_LOG"
    TEXT_LOG = "TEXT_LOG"
    FILE_REPORT = "FILE_REPORT"
    DRY_RUN = "DRY_RUN"
    NONE = "NONE"

class MetricType(str, Enum):
    COUNTER = "COUNTER"
    GAUGE = "GAUGE"
    TIMER = "TIMER"
    SUMMARY = "SUMMARY"
    STATUS = "STATUS"
    CUSTOM = "CUSTOM"

class OperationalMetricStatus(str, Enum):
    OK = "OK"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    MISSING = "MISSING"
    UNKNOWN = "UNKNOWN"

class LogRotationStatus(str, Enum):
    NOT_NEEDED = "NOT_NEEDED"
    ROTATED = "ROTATED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    WARNING = "WARNING"

class OperationalHealthStatus(str, Enum):
    HEALTHY = "HEALTHY"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"

class DiskUsageStatus(str, Enum):
    OK = "OK"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"

class SafetyMonitorStatus(str, Enum):
    SAFE = "SAFE"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class ObservabilityReportType(str, Enum):
    LOG_SUMMARY = "LOG_SUMMARY"
    METRICS_SNAPSHOT = "METRICS_SNAPSHOT"
    ERROR_TRENDS = "ERROR_TRENDS"
    DISK_USAGE = "DISK_USAGE"
    SAFETY_STATUS = "SAFETY_STATUS"
    OPERATIONAL_HEALTH = "OPERATIONAL_HEALTH"
    FULL_OBSERVABILITY = "FULL_OBSERVABILITY"

class RetentionArtifactType(str, Enum):
    DATA_CACHE = "DATA_CACHE"
    RUNTIME_SCAN = "RUNTIME_SCAN"
    BACKTEST_RUN = "BACKTEST_RUN"
    BASKET_RUN = "BASKET_RUN"
    PAPER_RUN = "PAPER_RUN"
    PAPER_ANALYTICS = "PAPER_ANALYTICS"
    COMPARISON_RUN = "COMPARISON_RUN"
    QUALITY_RUN = "QUALITY_RUN"
    REGRESSION_RUN = "REGRESSION_RUN"
    RELEASE_BUILD = "RELEASE_BUILD"
    BACKUP = "BACKUP"
    OBSERVABILITY_LOG = "OBSERVABILITY_LOG"
    OBSERVABILITY_REPORT = "OBSERVABILITY_REPORT"
    NOTIFICATION_RUN = "NOTIFICATION_RUN"
    TEMP_FILE = "TEMP_FILE"
    UNKNOWN = "UNKNOWN"

class RetentionPolicyAction(str, Enum):
    KEEP = "KEEP"
    DELETE = "DELETE"
    ARCHIVE_RESERVED = "ARCHIVE_RESERVED"
    COMPRESS_RESERVED = "COMPRESS_RESERVED"
    REVIEW = "REVIEW"
    SKIP = "SKIP"

class RetentionPolicyStatus(str, Enum):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    WARNING = "WARNING"
    ERROR = "ERROR"
    UNKNOWN = "UNKNOWN"

class CleanupCandidateStatus(str, Enum):
    CANDIDATE = "CANDIDATE"
    PROTECTED = "PROTECTED"
    SKIPPED = "SKIPPED"
    DELETED = "DELETED"
    FAILED = "FAILED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"

class CleanupRunStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    PLANNED = "PLANNED"
    DRY_RUN_COMPLETED = "DRY_RUN_COMPLETED"
    COMPLETED = "COMPLETED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    EMPTY = "EMPTY"

class DiskQuotaStatus(str, Enum):
    OK = "OK"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    EXCEEDED = "EXCEEDED"
    UNKNOWN = "UNKNOWN"

class CleanupSafetyStatus(str, Enum):
    SAFE = "SAFE"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class RetentionReportType(str, Enum):
    POLICY_SUMMARY = "POLICY_SUMMARY"
    CLEANUP_PLAN = "CLEANUP_PLAN"
    CLEANUP_RESULT = "CLEANUP_RESULT"
    DISK_QUOTA = "DISK_QUOTA"
    FULL_RETENTION_REVIEW = "FULL_RETENTION_REVIEW"


class IncidentSeverity(str, Enum):
    INFO = "INFO"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    BLOCKER = "BLOCKER"
    UNKNOWN = "UNKNOWN"

class IncidentStatus(str, Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    INVESTIGATING = "INVESTIGATING"
    MITIGATED = "MITIGATED"
    RECOVERED = "RECOVERED"
    CLOSED = "CLOSED"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class IncidentSource(str, Enum):
    RUNTIME = "RUNTIME"
    SCAN = "SCAN"
    DATA = "DATA"
    FEATURE = "FEATURE"
    STRATEGY = "STRATEGY"
    BACKTEST = "BACKTEST"
    RISK = "RISK"
    PORTFOLIO = "PORTFOLIO"
    PAPER = "PAPER"
    COMPARISON = "COMPARISON"
    QUALITY = "QUALITY"
    REGRESSION = "REGRESSION"
    RELEASE = "RELEASE"
    RETENTION = "RETENTION"
    OBSERVABILITY = "OBSERVABILITY"
    NOTIFICATION = "NOTIFICATION"
    CONFIG = "CONFIG"
    STORAGE = "STORAGE"
    UNKNOWN = "UNKNOWN"

class IncidentCategory(str, Enum):
    CONFIG_ERROR = "CONFIG_ERROR"
    DATA_MISSING = "DATA_MISSING"
    DATA_STALE = "DATA_STALE"
    RUNTIME_FAILURE = "RUNTIME_FAILURE"
    PIPELINE_STEP_FAILURE = "PIPELINE_STEP_FAILURE"
    PAPER_FAILURE = "PAPER_FAILURE"
    BACKTEST_FAILURE = "BACKTEST_FAILURE"
    QUALITY_GATE_FAILURE = "QUALITY_GATE_FAILURE"
    REGRESSION_FAILURE = "REGRESSION_FAILURE"
    RELEASE_FAILURE = "RELEASE_FAILURE"
    RETENTION_FAILURE = "RETENTION_FAILURE"
    DISK_QUOTA = "DISK_QUOTA"
    SAFETY_VIOLATION = "SAFETY_VIOLATION"
    SECRET_LEAK_RISK = "SECRET_LEAK_RISK"
    VALIDATION_FAILURE = "VALIDATION_FAILURE"
    STORAGE_FAILURE = "STORAGE_FAILURE"
    UNKNOWN = "UNKNOWN"

class RecoveryActionType(str, Enum):
    REVIEW_LOGS = "REVIEW_LOGS"
    VALIDATE_CONFIG = "VALIDATE_CONFIG"
    RUN_HEALTH_CHECK = "RUN_HEALTH_CHECK"
    RUN_SMOKE_TEST = "RUN_SMOKE_TEST"
    RUN_REGRESSION_SMOKE = "RUN_REGRESSION_SMOKE"
    REBUILD_GOLDEN_FIXTURES = "REBUILD_GOLDEN_FIXTURES"
    RECREATE_CACHE = "RECREATE_CACHE"
    CLEANUP_DRY_RUN = "CLEANUP_DRY_RUN"
    BACKUP_CREATE = "BACKUP_CREATE"
    BACKUP_VALIDATE = "BACKUP_VALIDATE"
    RESTORE_DRY_RUN = "RESTORE_DRY_RUN"
    ROLLBACK_DRY_RUN = "ROLLBACK_DRY_RUN"
    ROLLBACK_EXECUTE_RESERVED = "ROLLBACK_EXECUTE_RESERVED"
    REGENERATE_REPORTS = "REGENERATE_REPORTS"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    CUSTOM = "CUSTOM"

class RecoveryActionStatus(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    SKIPPED = "SKIPPED"
    COMPLETED = "COMPLETED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"

class RecoveryPlanStatus(str, Enum):
    CREATED = "CREATED"
    READY = "READY"
    DRY_RUN_COMPLETED = "DRY_RUN_COMPLETED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"
    UNKNOWN = "UNKNOWN"

class RollbackSourceType(str, Enum):
    RELEASE_BUNDLE = "RELEASE_BUNDLE"
    BACKUP_ARCHIVE = "BACKUP_ARCHIVE"
    CONFIG_PROFILE = "CONFIG_PROFILE"
    REGRESSION_BASELINE = "REGRESSION_BASELINE"
    QUALITY_ACCEPTANCE = "QUALITY_ACCEPTANCE"
    MANUAL_PATH = "MANUAL_PATH"
    UNKNOWN = "UNKNOWN"

class RollbackPlanStatus(str, Enum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    DRY_RUN_COMPLETED = "DRY_RUN_COMPLETED"
    READY = "READY"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"
    UNKNOWN = "UNKNOWN"

class RollbackStepStatus(str, Enum):
    PENDING = "PENDING"
    VALIDATED = "VALIDATED"
    DRY_RUN_OK = "DRY_RUN_OK"
    EXECUTED = "EXECUTED"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"

class RollbackSafetyStatus(str, Enum):
    SAFE = "SAFE"
    WARNING = "WARNING"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class IncidentReportType(str, Enum):
    INCIDENT_SUMMARY = "INCIDENT_SUMMARY"
    RECOVERY_PLAN = "RECOVERY_PLAN"
    ROLLBACK_PLAN = "ROLLBACK_PLAN"
    ROLLBACK_DRY_RUN = "ROLLBACK_DRY_RUN"
    FULL_INCIDENT_REVIEW = "FULL_INCIDENT_REVIEW"

class RunLockStatus(str, Enum):
    ACQUIRED = "ACQUIRED"
    HELD = "HELD"
    RELEASED = "RELEASED"
    STALE = "STALE"
    EXPIRED = "EXPIRED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    MISSING = "MISSING"
    UNKNOWN = "UNKNOWN"

class RunLockScope(str, Enum):
    GLOBAL = "GLOBAL"
    SCAN = "SCAN"
    BACKTEST = "BACKTEST"
    PAPER = "PAPER"
    COMPARISON = "COMPARISON"
    QUALITY = "QUALITY"
    REGRESSION = "REGRESSION"
    RELEASE = "RELEASE"
    RETENTION = "RETENTION"
    OBSERVABILITY = "OBSERVABILITY"
    INCIDENT = "INCIDENT"
    MAINTENANCE = "MAINTENANCE"
    NOTIFICATION = "NOTIFICATION"
    CUSTOM = "CUSTOM"

class LockAcquisitionMode(str, Enum):
    FAIL_FAST = "FAIL_FAST"
    WAIT = "WAIT"
    STEAL_IF_STALE = "STEAL_IF_STALE"
    DRY_RUN = "DRY_RUN"

class ConcurrencyDecision(str, Enum):
    ALLOW = "ALLOW"
    BLOCK = "BLOCK"
    WAIT = "WAIT"
    SKIP = "SKIP"
    REVIEW = "REVIEW"
    UNKNOWN = "UNKNOWN"

class ConcurrencyPolicyStatus(str, Enum):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"
    WARNING = "WARNING"
    ERROR = "ERROR"
    UNKNOWN = "UNKNOWN"

class SchedulerJobType(str, Enum):
    SCAN_RUN_ONCE = "SCAN_RUN_ONCE"
    PAPER_RUNTIME = "PAPER_RUNTIME"
    BACKTEST_RUN = "BACKTEST_RUN"
    REGRESSION_SMOKE = "REGRESSION_SMOKE"
    RELEASE_REHEARSAL = "RELEASE_REHEARSAL"
    QUALITY_ACCEPTANCE = "QUALITY_ACCEPTANCE"
    RETENTION_REVIEW = "RETENTION_REVIEW"
    CLEANUP_DRY_RUN = "CLEANUP_DRY_RUN"
    OBSERVABILITY_HEALTH = "OBSERVABILITY_HEALTH"
    INCIDENT_REVIEW = "INCIDENT_REVIEW"
    MAINTENANCE_CHECK = "MAINTENANCE_CHECK"
    CUSTOM = "CUSTOM"

class SchedulerJobStatus(str, Enum):
    CREATED = "CREATED"
    PLANNED = "PLANNED"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    UNKNOWN = "UNKNOWN"

class SchedulerPlanStatus(str, Enum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    DRY_RUN_COMPLETED = "DRY_RUN_COMPLETED"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    EMPTY = "EMPTY"
    UNKNOWN = "UNKNOWN"

class IdempotencyStatus(str, Enum):
    NEW = "NEW"
    DUPLICATE = "DUPLICATE"
    COMPLETED_BEFORE = "COMPLETED_BEFORE"
    IN_PROGRESS = "IN_PROGRESS"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"

class AtomicWriteStatus(str, Enum):
    READY = "READY"
    WRITTEN = "WRITTEN"
    REPLACED = "REPLACED"
    FAILED = "FAILED"
    ROLLED_BACK = "ROLLED_BACK"
    SKIPPED = "SKIPPED"
    UNKNOWN = "UNKNOWN"

class SchedulerReportType(str, Enum):
    LOCK_SUMMARY = "LOCK_SUMMARY"
    CONCURRENCY_REVIEW = "CONCURRENCY_REVIEW"
    SCHEDULER_PLAN = "SCHEDULER_PLAN"
    SCHEDULER_RUN = "SCHEDULER_RUN"
    STALE_LOCK_REVIEW = "STALE_LOCK_REVIEW"
    FULL_SCHEDULER_REVIEW = "FULL_SCHEDULER_REVIEW"


class ResourceProfileStatus(str, Enum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    WARNING = "WARNING"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class ResourceProfileScope(str, Enum):
    COMMAND = "COMMAND"
    TASK = "TASK"
    SCAN = "SCAN"
    PAPER = "PAPER"
    BACKTEST = "BACKTEST"
    BASKET_BACKTEST = "BASKET_BACKTEST"
    REGRESSION = "REGRESSION"
    QUALITY = "QUALITY"
    RETENTION = "RETENTION"
    OBSERVABILITY = "OBSERVABILITY"
    INCIDENT = "INCIDENT"
    RELEASE = "RELEASE"
    MAINTENANCE = "MAINTENANCE"
    CUSTOM = "CUSTOM"

class ResourceMetricName(str, Enum):
    WALL_TIME_SECONDS = "WALL_TIME_SECONDS"
    PROCESS_TIME_SECONDS = "PROCESS_TIME_SECONDS"
    MEMORY_CURRENT_BYTES = "MEMORY_CURRENT_BYTES"
    MEMORY_PEAK_BYTES = "MEMORY_PEAK_BYTES"
    ARTIFACT_SIZE_BYTES = "ARTIFACT_SIZE_BYTES"
    ARTIFACT_FILE_COUNT = "ARTIFACT_FILE_COUNT"
    OUTPUT_GROWTH_BYTES = "OUTPUT_GROWTH_BYTES"
    OUTPUT_GROWTH_FILES = "OUTPUT_GROWTH_FILES"
    ESTIMATED_CPU_PRESSURE = "ESTIMATED_CPU_PRESSURE"
    ESTIMATED_GPU_PRESSURE = "ESTIMATED_GPU_PRESSURE"
    ESTIMATED_NETWORK_MB = "ESTIMATED_NETWORK_MB"
    ESTIMATED_DISK_MB = "ESTIMATED_DISK_MB"
    UNKNOWN = "UNKNOWN"

class CalibrationStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    CALIBRATED = "CALIBRATED"
    PARTIAL = "PARTIAL"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"

class CalibrationDecision(str, Enum):
    KEEP_CURRENT = "KEEP_CURRENT"
    LOWER_BUDGET = "LOWER_BUDGET"
    RAISE_BUDGET = "RAISE_BUDGET"
    SPLIT_TASK = "SPLIT_TASK"
    THROTTLE_TASK = "THROTTLE_TASK"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    UNKNOWN = "UNKNOWN"

class ThrottlingAction(str, Enum):
    ALLOW = "ALLOW"
    WARN = "WARN"
    DELAY = "DELAY"
    SPLIT = "SPLIT"
    REDUCE_SCOPE = "REDUCE_SCOPE"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    SKIP = "SKIP"
    BLOCK = "BLOCK"
    REVIEW = "REVIEW"

class ThrottlingReason(str, Enum):
    CPU_BUDGET = "CPU_BUDGET"
    GPU_BUDGET = "GPU_BUDGET"
    RAM_BUDGET = "RAM_BUDGET"
    DISK_BUDGET = "DISK_BUDGET"
    NETWORK_BUDGET = "NETWORK_BUDGET"
    TIME_BUDGET = "TIME_BUDGET"
    HISTORICAL_SLOW_RUN = "HISTORICAL_SLOW_RUN"
    HIGH_OUTPUT_GROWTH = "HIGH_OUTPUT_GROWTH"
    SAFETY_LOCK_CONFLICT = "SAFETY_LOCK_CONFLICT"
    INSUFFICIENT_PROFILE_DATA = "INSUFFICIENT_PROFILE_DATA"
    UNKNOWN = "UNKNOWN"

class ThrottlingSeverity(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"

class ProfilingReportType(str, Enum):
    RESOURCE_PROFILE = "RESOURCE_PROFILE"
    CALIBRATION_REPORT = "CALIBRATION_REPORT"
    THROTTLING_PLAN = "THROTTLING_PLAN"
    FULL_PROFILING_REVIEW = "FULL_PROFILING_REVIEW"

class PerformanceBaselineScope(str, Enum):
    SCAN = "SCAN"
    PAPER = "PAPER"
    BACKTEST = "BACKTEST"
    BASKET_BACKTEST = "BASKET_BACKTEST"
    REGRESSION = "REGRESSION"
    QUALITY = "QUALITY"
    RETENTION = "RETENTION"
    OBSERVABILITY = "OBSERVABILITY"
    INCIDENT = "INCIDENT"
    RELEASE = "RELEASE"
    TASKQUEUE = "TASKQUEUE"
    SCHEDULER = "SCHEDULER"
    PROFILING = "PROFILING"
    MAINTENANCE = "MAINTENANCE"
    FULL_LOCAL_STACK = "FULL_LOCAL_STACK"
    CUSTOM = "CUSTOM"

class PerformanceMetricName(str, Enum):
    WALL_TIME_SECONDS = "WALL_TIME_SECONDS"
    PROCESS_TIME_SECONDS = "PROCESS_TIME_SECONDS"
    MEMORY_PEAK_MB = "MEMORY_PEAK_MB"
    MEMORY_CURRENT_MB = "MEMORY_CURRENT_MB"
    OUTPUT_SIZE_MB = "OUTPUT_SIZE_MB"
    OUTPUT_FILE_COUNT = "OUTPUT_FILE_COUNT"
    OUTPUT_GROWTH_MB = "OUTPUT_GROWTH_MB"
    WARNING_COUNT = "WARNING_COUNT"
    ERROR_COUNT = "ERROR_COUNT"
    FAILED_STEP_COUNT = "FAILED_STEP_COUNT"
    BLOCKED_STEP_COUNT = "BLOCKED_STEP_COUNT"
    SUCCESS_RATE = "SUCCESS_RATE"
    STATUS_SCORE = "STATUS_SCORE"
    CUSTOM = "CUSTOM"

class BaselineStatus(str, Enum):
    CREATED = "CREATED"
    ACTIVE = "ACTIVE"
    STALE = "STALE"
    SUPERSEDED = "SUPERSEDED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    INVALID = "INVALID"
    UNKNOWN = "UNKNOWN"

class BaselineComparisonStatus(str, Enum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class SLAThresholdType(str, Enum):
    MAX = "MAX"
    MIN = "MIN"
    RANGE = "RANGE"
    DELTA_PCT = "DELTA_PCT"
    DELTA_ABSOLUTE = "DELTA_ABSOLUTE"
    STATUS_ALLOWED = "STATUS_ALLOWED"
    CUSTOM = "CUSTOM"

class SLASeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"
    BLOCKER = "BLOCKER"

class RuntimeRegressionStatus(str, Enum):
    NO_REGRESSION = "NO_REGRESSION"
    MINOR_REGRESSION = "MINOR_REGRESSION"
    MODERATE_REGRESSION = "MODERATE_REGRESSION"
    MAJOR_REGRESSION = "MAJOR_REGRESSION"
    CRITICAL_REGRESSION = "CRITICAL_REGRESSION"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class BaselineDriftDirection(str, Enum):
    BETTER = "BETTER"
    WORSE = "WORSE"
    MIXED = "MIXED"
    FLAT = "FLAT"
    UNKNOWN = "UNKNOWN"

class PerformanceAlertStatus(str, Enum):
    CREATED = "CREATED"
    SUPPRESSED = "SUPPRESSED"
    READY = "READY"
    SENT_DRY_RUN = "SENT_DRY_RUN"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"
    UNKNOWN = "UNKNOWN"

class PerformanceReportType(str, Enum):
    BASELINE_SUMMARY = "BASELINE_SUMMARY"
    THRESHOLD_EVALUATION = "THRESHOLD_EVALUATION"
    REGRESSION_CHECK = "REGRESSION_CHECK"
    ACCEPTANCE_GATE = "ACCEPTANCE_GATE"
    FULL_PERFORMANCE_REVIEW = "FULL_PERFORMANCE_REVIEW"


class DataProviderType(str, Enum):
    ONLINE_FREE_LIBRARY = "ONLINE_FREE_LIBRARY"
    LOCAL_CACHE = "LOCAL_CACHE"
    LOCAL_FILE = "LOCAL_FILE"
    SYNTHETIC = "SYNTHETIC"
    UNKNOWN = "UNKNOWN"

class ProviderCapability(str, Enum):
    OHLCV_DAILY = "OHLCV_DAILY"
    OHLCV_INTRADAY = "OHLCV_INTRADAY"
    ADJUSTED_CLOSE = "ADJUSTED_CLOSE"
    DIVIDENDS = "DIVIDENDS"
    SPLITS = "SPLITS"
    SYMBOL_METADATA = "SYMBOL_METADATA"
    BULK_DOWNLOAD = "BULK_DOWNLOAD"
    SINGLE_SYMBOL = "SINGLE_SYMBOL"
    CACHE_READ = "CACHE_READ"
    CACHE_WRITE = "CACHE_WRITE"
    OFFLINE_FIXTURE = "OFFLINE_FIXTURE"
    UNKNOWN = "UNKNOWN"

class ProviderRequestType(str, Enum):
    OHLCV = "OHLCV"
    METADATA = "METADATA"
    DIVIDENDS = "DIVIDENDS"
    SPLITS = "SPLITS"
    HEALTH_CHECK = "HEALTH_CHECK"
    CAPABILITY_CHECK = "CAPABILITY_CHECK"
    UNKNOWN = "UNKNOWN"

class ProviderResponseStatus(str, Enum):
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    EMPTY = "EMPTY"
    STALE = "STALE"
    INVALID = "INVALID"
    RATE_LIMITED = "RATE_LIMITED"
    TIMEOUT = "TIMEOUT"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class ProviderQualityStatus(str, Enum):
    EXCELLENT = "EXCELLENT"
    GOOD = "GOOD"
    ACCEPTABLE = "ACCEPTABLE"
    DEGRADED = "DEGRADED"
    POOR = "POOR"
    FAILED = "FAILED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class ProviderRoutingDecision(str, Enum):
    USE_PRIMARY = "USE_PRIMARY"
    USE_CACHE = "USE_CACHE"
    USE_FALLBACK = "USE_FALLBACK"
    USE_FIXTURE = "USE_FIXTURE"
    SKIP = "SKIP"
    BLOCK = "BLOCK"
    REVIEW = "REVIEW"
    UNKNOWN = "UNKNOWN"

class ProviderErrorType(str, Enum):
    NETWORK_ERROR = "NETWORK_ERROR"
    TIMEOUT = "TIMEOUT"
    RATE_LIMIT = "RATE_LIMIT"
    EMPTY_RESPONSE = "EMPTY_RESPONSE"
    INVALID_SCHEMA = "INVALID_SCHEMA"
    INVALID_OHLCV = "INVALID_OHLCV"
    STALE_DATA = "STALE_DATA"
    MISSING_SYMBOL = "MISSING_SYMBOL"
    UNSUPPORTED_CAPABILITY = "UNSUPPORTED_CAPABILITY"
    CONFIG_ERROR = "CONFIG_ERROR"
    UNKNOWN = "UNKNOWN"

class ProviderReportType(str, Enum):
    PROVIDER_HEALTH = "PROVIDER_HEALTH"
    PROVIDER_QUALITY = "PROVIDER_QUALITY"
    ROUTING_DECISION = "ROUTING_DECISION"
    RESPONSE_VALIDATION = "RESPONSE_VALIDATION"
    FULL_PROVIDER_REVIEW = "FULL_PROVIDER_REVIEW"

class MarketCalendarName(str, Enum):
    US_EQUITIES = "US_EQUITIES"
    US_ETF = "US_ETF"
    CUSTOM = "CUSTOM"
    UNKNOWN = "UNKNOWN"

class MarketSessionType(str, Enum):
    PREMARKET = "PREMARKET"
    REGULAR = "REGULAR"
    AFTER_HOURS = "AFTER_HOURS"
    CLOSED = "CLOSED"
    HOLIDAY = "HOLIDAY"
    EARLY_CLOSE = "EARLY_CLOSE"
    WEEKEND = "WEEKEND"
    UNKNOWN = "UNKNOWN"

class MarketDayType(str, Enum):
    TRADING_DAY = "TRADING_DAY"
    NON_TRADING_DAY = "NON_TRADING_DAY"
    HOLIDAY = "HOLIDAY"
    WEEKEND = "WEEKEND"
    EARLY_CLOSE = "EARLY_CLOSE"
    UNKNOWN = "UNKNOWN"

class SessionValidationStatus(str, Enum):
    VALID = "VALID"
    WARNING = "WARNING"
    INVALID = "INVALID"
    MISSING = "MISSING"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"

class CalendarDataSource(str, Enum):
    STATIC_DEFAULT = "STATIC_DEFAULT"
    MANUAL_FILE = "MANUAL_FILE"
    PROVIDER_METADATA = "PROVIDER_METADATA"
    LOCAL_CACHE = "LOCAL_CACHE"
    UNKNOWN = "UNKNOWN"

class CorporateActionType(str, Enum):
    SPLIT = "SPLIT"
    DIVIDEND = "DIVIDEND"
    SPECIAL_DIVIDEND = "SPECIAL_DIVIDEND"
    SPINOFF = "SPINOFF"
    MERGER = "MERGER"
    SYMBOL_CHANGE = "SYMBOL_CHANGE"
    UNKNOWN = "UNKNOWN"

class CorporateActionSource(str, Enum):
    PROVIDER_METADATA = "PROVIDER_METADATA"
    MANUAL_FILE = "MANUAL_FILE"
    LOCAL_CACHE = "LOCAL_CACHE"
    INFERRED_FROM_PRICE = "INFERRED_FROM_PRICE"
    UNKNOWN = "UNKNOWN"

class CorporateActionSeverity(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"

class CorporateActionGuardStatus(str, Enum):
    CLEAR = "CLEAR"
    WATCH = "WATCH"
    WARNING = "WARNING"
    BLOCK_FEATURES = "BLOCK_FEATURES"
    BLOCK_SIGNAL = "BLOCK_SIGNAL"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    UNKNOWN = "UNKNOWN"

class AdjustedPriceValidationStatus(str, Enum):
    CONSISTENT = "CONSISTENT"
    WARNING = "WARNING"
    INCONSISTENT = "INCONSISTENT"
    MISSING_ADJUSTED_DATA = "MISSING_ADJUSTED_DATA"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class CalendarReportType(str, Enum):
    CALENDAR_SUMMARY = "CALENDAR_SUMMARY"
    SESSION_VALIDATION = "SESSION_VALIDATION"
    TRADING_DAY_REVIEW = "TRADING_DAY_REVIEW"
    FULL_CALENDAR_REVIEW = "FULL_CALENDAR_REVIEW"

class CorporateActionReportType(str, Enum):
    CORPORATE_ACTION_SUMMARY = "CORPORATE_ACTION_SUMMARY"
    ADJUSTED_PRICE_VALIDATION = "ADJUSTED_PRICE_VALIDATION"
    SPLIT_DIVIDEND_REVIEW = "SPLIT_DIVIDEND_REVIEW"
    FULL_CORPORATE_ACTION_REVIEW = "FULL_CORPORATE_ACTION_REVIEW"


class SymbolLifecycleStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DELISTED = "DELISTED"
    SUSPENDED = "SUSPENDED"
    MERGED = "MERGED"
    ACQUIRED = "ACQUIRED"
    SYMBOL_CHANGED = "SYMBOL_CHANGED"
    UNKNOWN = "UNKNOWN"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"

class SymbolLifecycleSource(str, Enum):
    MANUAL_REGISTRY = "MANUAL_REGISTRY"
    UNIVERSE_SNAPSHOT = "UNIVERSE_SNAPSHOT"
    PROVIDER_METADATA = "PROVIDER_METADATA"
    LOCAL_CACHE = "LOCAL_CACHE"
    INFERRED_FROM_HISTORY = "INFERRED_FROM_HISTORY"
    UNKNOWN = "UNKNOWN"

class UniverseSnapshotType(str, Enum):
    CURRENT = "CURRENT"
    HISTORICAL = "HISTORICAL"
    BACKTEST_AS_OF = "BACKTEST_AS_OF"
    MANUAL = "MANUAL"
    TEST_FIXTURE = "TEST_FIXTURE"
    UNKNOWN = "UNKNOWN"

class SurvivorshipBiasRisk(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"

class UniverseGuardStatus(str, Enum):
    CLEAR = "CLEAR"
    WARNING = "WARNING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCK_BACKTEST = "BLOCK_BACKTEST"
    BLOCK_SIGNAL = "BLOCK_SIGNAL"
    UNKNOWN = "UNKNOWN"

class SymbolHistoryStatus(str, Enum):
    SUFFICIENT = "SUFFICIENT"
    SHORT_HISTORY = "SHORT_HISTORY"
    MISSING_HISTORY = "MISSING_HISTORY"
    STALE_HISTORY = "STALE_HISTORY"
    GAP_HISTORY = "GAP_HISTORY"
    UNKNOWN = "UNKNOWN"

class SymbolAliasType(str, Enum):
    TICKER_CHANGE = "TICKER_CHANGE"
    SHARE_CLASS_CHANGE = "SHARE_CLASS_CHANGE"
    MERGER_ALIAS = "MERGER_ALIAS"
    ACQUISITION_ALIAS = "ACQUISITION_ALIAS"
    MANUAL_ALIAS = "MANUAL_ALIAS"
    UNKNOWN = "UNKNOWN"

class UniverseLifecycleReportType(str, Enum):
    LIFECYCLE_REGISTRY = "LIFECYCLE_REGISTRY"
    UNIVERSE_SNAPSHOT = "UNIVERSE_SNAPSHOT"
    SURVIVORSHIP_REVIEW = "SURVIVORSHIP_REVIEW"
    DELISTING_REVIEW = "DELISTING_REVIEW"
    FULL_UNIVERSE_LIFECYCLE_REVIEW = "FULL_UNIVERSE_LIFECYCLE_REVIEW"

class LiquidityStatus(str, Enum):
    EXCELLENT = "EXCELLENT"
    GOOD = "GOOD"
    ACCEPTABLE = "ACCEPTABLE"
    THIN = "THIN"
    ILLIQUID = "ILLIQUID"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class TradabilityStatus(str, Enum):
    TRADABLE = "TRADABLE"
    CAUTION = "CAUTION"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCK_SIGNAL = "BLOCK_SIGNAL"
    BLOCK_BACKTEST_FILL = "BLOCK_BACKTEST_FILL"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class ExecutionRealismStatus(str, Enum):
    REALISTIC = "REALISTIC"
    ACCEPTABLE_WITH_WARNINGS = "ACCEPTABLE_WITH_WARNINGS"
    OPTIMISTIC = "OPTIMISTIC"
    UNREALISTIC = "UNREALISTIC"
    BLOCKED = "BLOCKED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class BorrowabilityProxyStatus(str, Enum):
    LIKELY_EASY = "LIKELY_EASY"
    LIKELY_NORMAL = "LIKELY_NORMAL"
    LIKELY_HARD = "LIKELY_HARD"
    LIKELY_UNAVAILABLE = "LIKELY_UNAVAILABLE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    UNKNOWN = "UNKNOWN"

class ExecutionRiskLevel(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"

class LiquidityMetricName(str, Enum):
    AVG_DAILY_VOLUME = "AVG_DAILY_VOLUME"
    AVG_DOLLAR_VOLUME = "AVG_DOLLAR_VOLUME"
    MEDIAN_DAILY_VOLUME = "MEDIAN_DAILY_VOLUME"
    MEDIAN_DOLLAR_VOLUME = "MEDIAN_DOLLAR_VOLUME"
    LAST_VOLUME = "LAST_VOLUME"
    LAST_DOLLAR_VOLUME = "LAST_DOLLAR_VOLUME"
    VOLUME_RATIO = "VOLUME_RATIO"
    PRICE_LEVEL = "PRICE_LEVEL"
    ATR_PCT = "ATR_PCT"
    GAP_PCT = "GAP_PCT"
    SPREAD_PROXY_BPS = "SPREAD_PROXY_BPS"
    SLIPPAGE_PROXY_BPS = "SLIPPAGE_PROXY_BPS"
    PARTICIPATION_RATE_PCT = "PARTICIPATION_RATE_PCT"
    STALE_DATA_DAYS = "STALE_DATA_DAYS"
    UNKNOWN = "UNKNOWN"

class ExecutionGuardReason(str, Enum):
    LOW_VOLUME = "LOW_VOLUME"
    LOW_DOLLAR_VOLUME = "LOW_DOLLAR_VOLUME"
    LOW_PRICE = "LOW_PRICE"
    HIGH_SPREAD_PROXY = "HIGH_SPREAD_PROXY"
    HIGH_SLIPPAGE_PROXY = "HIGH_SLIPPAGE_PROXY"
    HIGH_PARTICIPATION_RATE = "HIGH_PARTICIPATION_RATE"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LARGE_GAP = "LARGE_GAP"
    STALE_DATA = "STALE_DATA"
    CORPORATE_ACTION_RISK = "CORPORATE_ACTION_RISK"
    DELISTING_OR_LIFECYCLE_RISK = "DELISTING_OR_LIFECYCLE_RISK"
    CLOSED_SESSION = "CLOSED_SESSION"
    SHORT_BORROW_PROXY_RISK = "SHORT_BORROW_PROXY_RISK"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    UNKNOWN = "UNKNOWN"

class ExecutionReportType(str, Enum):
    LIQUIDITY_SUMMARY = "LIQUIDITY_SUMMARY"
    TRADABILITY_REVIEW = "TRADABILITY_REVIEW"
    BORROWABILITY_PROXY_REVIEW = "BORROWABILITY_PROXY_REVIEW"
    EXECUTION_REALISM_REVIEW = "EXECUTION_REALISM_REVIEW"
    FULL_EXECUTION_REVIEW = "FULL_EXECUTION_REVIEW"

class TransactionCostComponent(str, Enum):
    COMMISSION = "COMMISSION"
    REGULATORY_FEE_PROXY = "REGULATORY_FEE_PROXY"
    SPREAD_COST = "SPREAD_COST"
    SLIPPAGE = "SLIPPAGE"
    MARKET_IMPACT = "MARKET_IMPACT"
    VOLATILITY_PENALTY = "VOLATILITY_PENALTY"
    GAP_PENALTY = "GAP_PENALTY"
    PARTICIPATION_PENALTY = "PARTICIPATION_PENALTY"
    BORROW_COST_PROXY = "BORROW_COST_PROXY"
    SHORT_FRICTION_PROXY = "SHORT_FRICTION_PROXY"
    UNKNOWN = "UNKNOWN"

class TransactionSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    SHORT = "SHORT"
    COVER = "COVER"
    LONG = "LONG"
    UNKNOWN = "UNKNOWN"

class OrderSizeClass(str, Enum):
    MICRO = "MICRO"
    SMALL = "SMALL"
    MEDIUM = "MEDIUM"
    LARGE = "LARGE"
    OVERSIZED = "OVERSIZED"
    UNKNOWN = "UNKNOWN"

class SlippageCurveType(str, Enum):
    FLAT = "FLAT"
    LINEAR = "LINEAR"
    CONVEX = "CONVEX"
    STEPWISE = "STEPWISE"
    LIQUIDITY_ADJUSTED = "LIQUIDITY_ADJUSTED"
    VOLATILITY_ADJUSTED = "VOLATILITY_ADJUSTED"
    UNKNOWN = "UNKNOWN"

class MarketImpactStatus(str, Enum):
    NEGLIGIBLE = "NEGLIGIBLE"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    EXTREME = "EXTREME"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class CostRealismStatus(str, Enum):
    CONSERVATIVE = "CONSERVATIVE"
    REALISTIC = "REALISTIC"
    OPTIMISTIC = "OPTIMISTIC"
    UNREALISTIC = "UNREALISTIC"
    BLOCKED = "BLOCKED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class CostAdjustmentStatus(str, Enum):
    APPLIED = "APPLIED"
    PARTIAL = "PARTIAL"
    SKIPPED = "SKIPPED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class FillSimulationStatus(str, Enum):
    FILLED = "FILLED"
    PARTIAL_FILL = "PARTIAL_FILL"
    SKIPPED = "SKIPPED"
    BLOCKED = "BLOCKED"
    UNREALISTIC = "UNREALISTIC"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class TransactionCostReportType(str, Enum):
    COST_MODEL_SUMMARY = "COST_MODEL_SUMMARY"
    SLIPPAGE_CURVE_REVIEW = "SLIPPAGE_CURVE_REVIEW"
    MARKET_IMPACT_REVIEW = "MARKET_IMPACT_REVIEW"
    COST_ADJUSTED_TRADE_REVIEW = "COST_ADJUSTED_TRADE_REVIEW"
    FULL_TRANSACTION_COST_REVIEW = "FULL_TRANSACTION_COST_REVIEW"


class CostStressType(str, Enum):
    SLIPPAGE = "SLIPPAGE"
    SPREAD = "SPREAD"
    MARKET_IMPACT = "MARKET_IMPACT"
    FEE = "FEE"
    PARTICIPATION = "PARTICIPATION"
    LIQUIDITY_FILTER = "LIQUIDITY_FILTER"
    FILL_REALISM = "FILL_REALISM"
    COMBINED = "COMBINED"
    UNKNOWN = "UNKNOWN"

class CostStressSeverity(str, Enum):
    BASELINE = "BASELINE"
    MILD = "MILD"
    MODERATE = "MODERATE"
    SEVERE = "SEVERE"
    EXTREME = "EXTREME"
    CUSTOM = "CUSTOM"
    UNKNOWN = "UNKNOWN"

class CostRobustnessStatus(str, Enum):
    ROBUST = "ROBUST"
    ACCEPTABLE = "ACCEPTABLE"
    FRAGILE = "FRAGILE"
    VERY_FRAGILE = "VERY_FRAGILE"
    FAILED = "FAILED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class ExecutionSensitivityAxis(str, Enum):
    SLIPPAGE_BPS = "SLIPPAGE_BPS"
    SPREAD_BPS = "SPREAD_BPS"
    IMPACT_BPS = "IMPACT_BPS"
    COMMISSION_BPS = "COMMISSION_BPS"
    PARTICIPATION_PCT = "PARTICIPATION_PCT"
    MIN_DOLLAR_VOLUME = "MIN_DOLLAR_VOLUME"
    FILL_REALISM_MODE = "FILL_REALISM_MODE"
    LIQUIDITY_STATUS = "LIQUIDITY_STATUS"
    UNKNOWN = "UNKNOWN"

class FillRealismMode(str, Enum):
    OPTIMISTIC = "OPTIMISTIC"
    BASELINE = "BASELINE"
    CONSERVATIVE = "CONSERVATIVE"
    PESSIMISTIC = "PESSIMISTIC"
    STRICT = "STRICT"
    UNKNOWN = "UNKNOWN"

class CostStressResultStatus(str, Enum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class CostFragilityReason(str, Enum):
    PROFIT_ERASED_BY_COSTS = "PROFIT_ERASED_BY_COSTS"
    SHARPE_COLLAPSE = "SHARPE_COLLAPSE"
    DRAWDOWN_EXPANSION = "DRAWDOWN_EXPANSION"
    LOW_MARGIN_PER_TRADE = "LOW_MARGIN_PER_TRADE"
    HIGH_TURNOVER = "HIGH_TURNOVER"
    HIGH_IMPACT_SENSITIVITY = "HIGH_IMPACT_SENSITIVITY"
    HIGH_SLIPPAGE_SENSITIVITY = "HIGH_SLIPPAGE_SENSITIVITY"
    LOW_LIQUIDITY_DEPENDENCE = "LOW_LIQUIDITY_DEPENDENCE"
    STRICT_FILL_FAILURE = "STRICT_FILL_FAILURE"
    UNKNOWN = "UNKNOWN"

class CostRobustnessReportType(str, Enum):
    STRESS_SCENARIO_SUMMARY = "STRESS_SCENARIO_SUMMARY"
    SENSITIVITY_MATRIX = "SENSITIVITY_MATRIX"
    WALK_FORWARD_COST_ROBUSTNESS = "WALK_FORWARD_COST_ROBUSTNESS"
    FRAGILITY_REVIEW = "FRAGILITY_REVIEW"
    FULL_COST_ROBUSTNESS_REVIEW = "FULL_COST_ROBUSTNESS_REVIEW"

class CostVolatilityRegime(str, Enum):
    VERY_LOW = "VERY_LOW"
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    EXTREME = "EXTREME"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class CostLiquidityRegime(str, Enum):
    DEEP = "DEEP"
    NORMAL = "NORMAL"
    THIN = "THIN"
    ILLIQUID = "ILLIQUID"
    FROZEN = "FROZEN"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class CostSpreadRegime(str, Enum):
    TIGHT = "TIGHT"
    NORMAL = "NORMAL"
    WIDE = "WIDE"
    VERY_WIDE = "VERY_WIDE"
    UNRELIABLE = "UNRELIABLE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class CostSessionRegime(str, Enum):
    REGULAR = "REGULAR"
    OPENING_WINDOW = "OPENING_WINDOW"
    CLOSING_WINDOW = "CLOSING_WINDOW"
    PREMARKET = "PREMARKET"
    AFTER_HOURS = "AFTER_HOURS"
    CLOSED = "CLOSED"
    HOLIDAY = "HOLIDAY"
    UNKNOWN = "UNKNOWN"

class CostLifecycleRegime(str, Enum):
    NORMAL = "NORMAL"
    CORPORATE_ACTION_WATCH = "CORPORATE_ACTION_WATCH"
    POST_SPLIT_WINDOW = "POST_SPLIT_WINDOW"
    ADJUSTED_DATA_RISK = "ADJUSTED_DATA_RISK"
    LIFECYCLE_REVIEW = "LIFECYCLE_REVIEW"
    DELISTING_RISK = "DELISTING_RISK"
    UNKNOWN = "UNKNOWN"

class CombinedCostRegime(str, Enum):
    NORMAL = "NORMAL"
    CONSERVATIVE = "CONSERVATIVE"
    STRESSED = "STRESSED"
    HIGH_RISK = "HIGH_RISK"
    BLOCKED = "BLOCKED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class RegimeCostCurveProfile(str, Enum):
    BASELINE = "BASELINE"
    LIQUID = "LIQUID"
    CONSERVATIVE = "CONSERVATIVE"
    STRESSED = "STRESSED"
    EXTREME = "EXTREME"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class AdaptiveExecutionDecision(str, Enum):
    USE_BASELINE_COSTS = "USE_BASELINE_COSTS"
    USE_CONSERVATIVE_COSTS = "USE_CONSERVATIVE_COSTS"
    USE_STRESSED_COSTS = "USE_STRESSED_COSTS"
    REQUIRE_REVIEW = "REQUIRE_REVIEW"
    BLOCK_FILL_SIMULATION = "BLOCK_FILL_SIMULATION"
    BLOCK_SIGNAL_METADATA = "BLOCK_SIGNAL_METADATA"
    UNKNOWN = "UNKNOWN"

class RegimeCostAdjustmentStatus(str, Enum):
    APPLIED = "APPLIED"
    PARTIAL = "PARTIAL"
    SKIPPED = "SKIPPED"
    BLOCKED = "BLOCKED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class RegimeCostReportType(str, Enum):
    REGIME_COST_SUMMARY = "REGIME_COST_SUMMARY"
    COST_CURVE_SELECTION = "COST_CURVE_SELECTION"
    ADAPTIVE_EXECUTION_REVIEW = "ADAPTIVE_EXECUTION_REVIEW"
    REGIME_AWARE_BACKTEST_REVIEW = "REGIME_AWARE_BACKTEST_REVIEW"
    FULL_REGIME_COST_REVIEW = "FULL_REGIME_COST_REVIEW"


class RegimeTimeframe(str, Enum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    CUSTOM = "CUSTOM"
    UNKNOWN = "UNKNOWN"

class RegimeConfirmationStatus(str, Enum):
    CONFIRMED = "CONFIRMED"
    PARTIAL = "PARTIAL"
    DIVERGENT = "DIVERGENT"
    CONFLICTED = "CONFLICTED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class TrendRegime(str, Enum):
    STRONG_UPTREND = "STRONG_UPTREND"
    UPTREND = "UPTREND"
    RANGE = "RANGE"
    DOWNTREND = "DOWNTREND"
    STRONG_DOWNTREND = "STRONG_DOWNTREND"
    CHOPPY = "CHOPPY"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class VolatilityMapRegime(str, Enum):
    COMPRESSED = "COMPRESSED"
    NORMAL = "NORMAL"
    EXPANDING = "EXPANDING"
    HIGH = "HIGH"
    EXTREME = "EXTREME"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class MomentumRegime(str, Enum):
    STRONG_POSITIVE = "STRONG_POSITIVE"
    POSITIVE = "POSITIVE"
    NEUTRAL = "NEUTRAL"
    NEGATIVE = "NEGATIVE"
    STRONG_NEGATIVE = "STRONG_NEGATIVE"
    EXHAUSTED = "EXHAUSTED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class LiquidityMapRegime(str, Enum):
    DEEP = "DEEP"
    NORMAL = "NORMAL"
    THINNING = "THINNING"
    THIN = "THIN"
    ILLIQUID = "ILLIQUID"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class BreadthRegime(str, Enum):
    BROAD_RISK_ON = "BROAD_RISK_ON"
    RISK_ON = "RISK_ON"
    MIXED = "MIXED"
    DETERIORATING = "DETERIORATING"
    RISK_OFF = "RISK_OFF"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class CrossSectionalRegime(str, Enum):
    BROAD_UPTREND = "BROAD_UPTREND"
    SELECTIVE_UPTREND = "SELECTIVE_UPTREND"
    ROTATION = "ROTATION"
    DISPERSION_HIGH = "DISPERSION_HIGH"
    BROAD_DOWNTREND = "BROAD_DOWNTREND"
    RISK_OFF = "RISK_OFF"
    MIXED = "MIXED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class RegimeAlignmentStatus(str, Enum):
    ALIGNED = "ALIGNED"
    MOSTLY_ALIGNED = "MOSTLY_ALIGNED"
    MIXED = "MIXED"
    DIVERGENT = "DIVERGENT"
    CONFLICTED = "CONFLICTED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class RegimeTransitionType(str, Enum):
    TREND_TO_RANGE = "TREND_TO_RANGE"
    RANGE_TO_TREND = "RANGE_TO_TREND"
    UPTREND_TO_DOWNTREND = "UPTREND_TO_DOWNTREND"
    DOWNTREND_TO_UPTREND = "DOWNTREND_TO_UPTREND"
    LOW_VOL_TO_HIGH_VOL = "LOW_VOL_TO_HIGH_VOL"
    HIGH_VOL_TO_LOW_VOL = "HIGH_VOL_TO_LOW_VOL"
    LIQUIDITY_NORMAL_TO_THIN = "LIQUIDITY_NORMAL_TO_THIN"
    BREADTH_RISK_ON_TO_OFF = "BREADTH_RISK_ON_TO_OFF"
    MOMENTUM_EXHAUSTION = "MOMENTUM_EXHAUSTION"
    REGIME_BREAK = "REGIME_BREAK"
    UNKNOWN = "UNKNOWN"

class RegimeTransitionRisk(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    UNKNOWN = "UNKNOWN"

class RegimeMapGuardStatus(str, Enum):
    CLEAR = "CLEAR"
    WARNING = "WARNING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    SUPPRESS_CANDIDATE = "SUPPRESS_CANDIDATE"
    BLOCK_SIGNAL_METADATA = "BLOCK_SIGNAL_METADATA"
    UNKNOWN = "UNKNOWN"

class RegimeMapReportType(str, Enum):
    TIMEFRAME_CONFIRMATION = "TIMEFRAME_CONFIRMATION"
    CROSS_SECTIONAL_MAP = "CROSS_SECTIONAL_MAP"
    REGIME_ALIGNMENT = "REGIME_ALIGNMENT"
    TRANSITION_RISK = "TRANSITION_RISK"
    FULL_REGIME_MAP_REVIEW = "FULL_REGIME_MAP_REVIEW"
