import re

def update_enums():
    with open('usa_signal_bot/core/enums.py', 'r') as f:
        content = f.read()

    new_enums = """
class SandboxRuntimeAdmissionReplayStatus(str, Enum):
    DRAFT = "DRAFT"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED_ALL_BLOCKED = "COMPLETED_ALL_BLOCKED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class SandboxRuntimeAdmissionReplayOutcome(str, Enum):
    ALL_SANDBOX_RUNTIME_ADMISSION_ATTEMPTS_BLOCKED = "ALL_SANDBOX_RUNTIME_ADMISSION_ATTEMPTS_BLOCKED"
    SANDBOX_RUNTIME_ADMISSION_ATTEMPT_ALLOWED = "SANDBOX_RUNTIME_ADMISSION_ATTEMPT_ALLOWED"
    BLOCKER_RULES_INCOMPLETE = "BLOCKER_RULES_INCOMPLETE"
    BLOCKER_EVENTS_MISSING = "BLOCKER_EVENTS_MISSING"
    REPLAY_FAILED = "REPLAY_FAILED"
    BLOCKED = "BLOCKED"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class SandboxRuntimeAdmissionReplayDecision(str, Enum):
    DENY_SANDBOX_RUNTIME_ADMISSION = "DENY_SANDBOX_RUNTIME_ADMISSION"
    DENY_PAPER_SANDBOX_RUNTIME = "DENY_PAPER_SANDBOX_RUNTIME"
    DENY_SIMULATOR_ADMISSION = "DENY_SIMULATOR_ADMISSION"
    DENY_PAPER_ADMISSION = "DENY_PAPER_ADMISSION"
    DENY_PAPER_ORDER = "DENY_PAPER_ORDER"
    DENY_PAPER_STATE_COMMIT = "DENY_PAPER_STATE_COMMIT"
    DENY_BROKER_SEND = "DENY_BROKER_SEND"
    DENY_CONFIG_PATCH = "DENY_CONFIG_PATCH"
    DENY_TELEGRAM_REAL_SEND = "DENY_TELEGRAM_REAL_SEND"
    BLOCK = "BLOCK"
    UNKNOWN = "UNKNOWN"

class SimulatorEvidenceFreezeStatus(str, Enum):
    DRAFT = "DRAFT"
    FROZEN = "FROZEN"
    VALIDATED = "VALIDATED"
    PARTIAL = "PARTIAL"
    STALE = "STALE"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class SimulatorEvidenceFreezeDecision(str, Enum):
    FREEZE_SIMULATOR_EVIDENCE = "FREEZE_SIMULATOR_EVIDENCE"
    REQUEST_SIMULATOR_DOSSIER_REFRESH = "REQUEST_SIMULATOR_DOSSIER_REFRESH"
    REQUEST_SIMULATOR_ACCEPTANCE_SEAL_REFRESH = "REQUEST_SIMULATOR_ACCEPTANCE_SEAL_REFRESH"
    REQUEST_SANDBOX_REPLAY_REFRESH = "REQUEST_SANDBOX_REPLAY_REFRESH"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    REJECT = "REJECT"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class PrePaperHandoffFreezeGateStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    VALIDATED_HANDOFF_FROZEN = "VALIDATED_HANDOFF_FROZEN"
    REQUEST_CHANGES = "REQUEST_CHANGES"
    BLOCKED = "BLOCKED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class PrePaperHandoffFreezeGateDecision(str, Enum):
    COMPLETE_PRE_PAPER_HANDOFF_FREEZE = "COMPLETE_PRE_PAPER_HANDOFF_FREEZE"
    REQUEST_SANDBOX_REPLAY = "REQUEST_SANDBOX_REPLAY"
    REQUEST_SIMULATOR_EVIDENCE_FREEZE = "REQUEST_SIMULATOR_EVIDENCE_FREEZE"
    REQUEST_SIMULATOR_DOSSIER_REFRESH = "REQUEST_SIMULATOR_DOSSIER_REFRESH"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    REJECT = "REJECT"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class HandoffFreezeRuleStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    NOT_CHECKED = "NOT_CHECKED"
    UNKNOWN = "UNKNOWN"

class HandoffFreezeAssertionStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class PrePaperHandoffFreezeRiskFlag(str, Enum):
    REAL_ORDER_RISK = "REAL_ORDER_RISK"
    PAPER_ORDER_RISK = "PAPER_ORDER_RISK"
    BROKER_ORDER_RISK = "BROKER_ORDER_RISK"
    PAPER_STATE_MUTATION_RISK = "PAPER_STATE_MUTATION_RISK"
    PAPER_POSITION_MUTATION_RISK = "PAPER_POSITION_MUTATION_RISK"
    PAPER_PORTFOLIO_MUTATION_RISK = "PAPER_PORTFOLIO_MUTATION_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    PRODUCTION_CONFIG_WRITE_RISK = "PRODUCTION_CONFIG_WRITE_RISK"
    ACTIVE_PAPER_ENABLE_RISK = "ACTIVE_PAPER_ENABLE_RISK"
    PAPER_ADMISSION_RISK = "PAPER_ADMISSION_RISK"
    SHADOW_LAUNCH_RISK = "SHADOW_LAUNCH_RISK"
    PAPER_MODE_LAUNCH_RISK = "PAPER_MODE_LAUNCH_RISK"
    PAPER_MODE_REHEARSAL_RISK = "PAPER_MODE_REHEARSAL_RISK"
    LOCAL_PAPER_SIMULATOR_RISK = "LOCAL_PAPER_SIMULATOR_RISK"
    SIMULATED_ADMISSION_RISK = "SIMULATED_ADMISSION_RISK"
    SANDBOX_RUNTIME_ADMISSION_RISK = "SANDBOX_RUNTIME_ADMISSION_RISK"
    PAPER_SANDBOX_RUNTIME_RISK = "PAPER_SANDBOX_RUNTIME_RISK"
    PRE_PAPER_HANDOFF_RISK = "PRE_PAPER_HANDOFF_RISK"
    ACTIVATION_ALLOWED_RISK = "ACTIVATION_ALLOWED_RISK"
    ADMISSION_ALLOWED_RISK = "ADMISSION_ALLOWED_RISK"
    TRANSITION_ALLOWED_RISK = "TRANSITION_ALLOWED_RISK"
    ORDER_CREATED_RISK = "ORDER_CREATED_RISK"
    MUTATION_DETECTED_RISK = "MUTATION_DETECTED_RISK"
    SANDBOX_REPLAY_FAILED = "SANDBOX_REPLAY_FAILED"
    SANDBOX_RUNTIME_ADMISSION_ATTEMPT_NOT_BLOCKED = "SANDBOX_RUNTIME_ADMISSION_ATTEMPT_NOT_BLOCKED"
    SIMULATOR_EVIDENCE_FREEZE_FAILED = "SIMULATOR_EVIDENCE_FREEZE_FAILED"
    SIMULATOR_EVIDENCE_FREEZE_STALE = "SIMULATOR_EVIDENCE_FREEZE_STALE"
    SIMULATOR_ACCEPTANCE_SEAL_FAILED = "SIMULATOR_ACCEPTANCE_SEAL_FAILED"
    HANDOFF_FREEZE_GATE_INVALID = "HANDOFF_FREEZE_GATE_INVALID"
    HANDOFF_FREEZE_RULE_FAILED = "HANDOFF_FREEZE_RULE_FAILED"
    HANDOFF_FREEZE_ASSERTION_FAILED = "HANDOFF_FREEZE_ASSERTION_FAILED"
    SECRET_RISK = "SECRET_RISK"
    UNKNOWN = "UNKNOWN"

class PrePaperHandoffFreezeReportType(str, Enum):
    SANDBOX_RUNTIME_ADMISSION_REPLAY_REPORT = "SANDBOX_RUNTIME_ADMISSION_REPLAY_REPORT"
    SIMULATOR_EVIDENCE_FREEZE_REPORT = "SIMULATOR_EVIDENCE_FREEZE_REPORT"
    FINAL_PRE_PAPER_HANDOFF_FREEZE_GATE_REPORT = "FINAL_PRE_PAPER_HANDOFF_FREEZE_GATE_REPORT"
    SAFETY_REVIEW = "SAFETY_REVIEW"
    FULL_PRE_PAPER_HANDOFF_FREEZE_REVIEW = "FULL_PRE_PAPER_HANDOFF_FREEZE_REVIEW"

"""
    if "SandboxRuntimeAdmissionReplayStatus" not in content:
        content += new_enums

    if "PRE_PAPER_HANDOFF_FREEZE_REPORT" not in content:
        content = re.sub(
            r'(class NotificationType\(str, Enum\):)',
            r'\1\n    PRE_PAPER_HANDOFF_FREEZE_REPORT = "PRE_PAPER_HANDOFF_FREEZE_REPORT"\n    SANDBOX_RUNTIME_ADMISSION_REPLAY_WARNING = "SANDBOX_RUNTIME_ADMISSION_REPLAY_WARNING"\n    SIMULATOR_EVIDENCE_FREEZE_WARNING = "SIMULATOR_EVIDENCE_FREEZE_WARNING"',
            content
        )

    if "PRE_PAPER_HANDOFF_FREEZE_BLOCKED" not in content:
        content = re.sub(
            r'(class AlertType\(str, Enum\):)',
            r'\1\n    PRE_PAPER_HANDOFF_FREEZE_BLOCKED = "PRE_PAPER_HANDOFF_FREEZE_BLOCKED"\n    SANDBOX_RUNTIME_ADMISSION_REPLAY_BLOCKED = "SANDBOX_RUNTIME_ADMISSION_REPLAY_BLOCKED"\n    SIMULATOR_EVIDENCE_FREEZE_BLOCKED = "SIMULATOR_EVIDENCE_FREEZE_BLOCKED"',
            content
        )

    with open('usa_signal_bot/core/enums.py', 'w') as f:
        f.write(content)
    print("Enums updated.")

if __name__ == '__main__':
    update_enums()
