import os

print("Applying phase 107 enums...")

ENUMS_ADDITION = """
class ProviderRuntimeStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    CONTRACT_READY = "CONTRACT_READY"
    DRY_RUN_READY = "DRY_RUN_READY"
    VALIDATED = "VALIDATED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    ARCHIVED = "ARCHIVED"
    UNKNOWN = "UNKNOWN"

class ProviderRuntimeDecision(str, Enum):
    CREATE_PROVIDER_RUNTIME = "CREATE_PROVIDER_RUNTIME"
    RUN_CACHE_AWARE_DRY_RUN = "RUN_CACHE_AWARE_DRY_RUN"
    REQUEST_PROVIDER_ABSTRACTION_REFRESH = "REQUEST_PROVIDER_ABSTRACTION_REFRESH"
    REQUEST_ADAPTER_FIX = "REQUEST_ADAPTER_FIX"
    REQUEST_CONTRACT_FIX = "REQUEST_CONTRACT_FIX"
    REQUEST_CACHE_POLICY_REVIEW = "REQUEST_CACHE_POLICY_REVIEW"
    REQUEST_MANUAL_REVIEW = "REQUEST_MANUAL_REVIEW"
    BLOCK = "BLOCK"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNKNOWN = "UNKNOWN"

class ProviderImplementationStatus(str, Enum):
    SKELETON_UPGRADED = "SKELETON_UPGRADED"
    IMPLEMENTED_CONTRACT_ONLY = "IMPLEMENTED_CONTRACT_ONLY"
    IMPLEMENTED_LOCAL_FIXTURE = "IMPLEMENTED_LOCAL_FIXTURE"
    IMPLEMENTED_NETWORK_GUARDED = "IMPLEMENTED_NETWORK_GUARDED"
    VALIDATED_NO_NETWORK = "VALIDATED_NO_NETWORK"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"

class ProviderFetchMode(str, Enum):
    METADATA_ONLY = "METADATA_ONLY"
    CACHE_ONLY = "CACHE_ONLY"
    LOCAL_FIXTURE_ONLY = "LOCAL_FIXTURE_ONLY"
    NETWORK_GUARDED_DISABLED = "NETWORK_GUARDED_DISABLED"
    NETWORK_GUARDED_ALLOWED_FUTURE = "NETWORK_GUARDED_ALLOWED_FUTURE"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class ProviderCacheLookupStatus(str, Enum):
    CACHE_HIT = "CACHE_HIT"
    CACHE_MISS = "CACHE_MISS"
    CACHE_STALE = "CACHE_STALE"
    CACHE_DISABLED = "CACHE_DISABLED"
    CACHE_PATH_MISSING = "CACHE_PATH_MISSING"
    DRY_RUN_ONLY = "DRY_RUN_ONLY"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class ProviderFetchDryRunStatus(str, Enum):
    PLANNED = "PLANNED"
    CACHE_HIT_SIMULATED = "CACHE_HIT_SIMULATED"
    CACHE_MISS_SIMULATED = "CACHE_MISS_SIMULATED"
    FETCH_SKIPPED_NETWORK_DISABLED = "FETCH_SKIPPED_NETWORK_DISABLED"
    FETCH_SKIPPED_METADATA_ONLY = "FETCH_SKIPPED_METADATA_ONLY"
    FETCH_SKIPPED_DRY_RUN = "FETCH_SKIPPED_DRY_RUN"
    VALIDATED = "VALIDATED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"

class ProviderContractTestStatus(str, Enum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"
    UNKNOWN = "UNKNOWN"

class ProviderRuntimeRiskFlag(str, Enum):
    PROVIDER_ABSTRACTION_MISSING = "PROVIDER_ABSTRACTION_MISSING"
    PROVIDER_ABSTRACTION_INVALID = "PROVIDER_ABSTRACTION_INVALID"
    ADAPTER_INVALID = "ADAPTER_INVALID"
    CONTRACT_TEST_FAILED = "CONTRACT_TEST_FAILED"
    CACHE_KEY_INVALID = "CACHE_KEY_INVALID"
    CACHE_LOOKUP_FAILED = "CACHE_LOOKUP_FAILED"
    NETWORK_FETCH_ATTEMPTED = "NETWORK_FETCH_ATTEMPTED"
    NETWORK_ENABLED_TOO_EARLY = "NETWORK_ENABLED_TOO_EARLY"
    PAID_API_RISK = "PAID_API_RISK"
    SCRAPING_RISK = "SCRAPING_RISK"
    HTML_PARSE_RISK = "HTML_PARSE_RISK"
    BROKER_RISK = "BROKER_RISK"
    ORDER_RISK = "ORDER_RISK"
    PAPER_MUTATION_RISK = "PAPER_MUTATION_RISK"
    TELEGRAM_REAL_SEND_RISK = "TELEGRAM_REAL_SEND_RISK"
    DASHBOARD_RISK = "DASHBOARD_RISK"
    CREDENTIAL_REQUIRED_RISK = "CREDENTIAL_REQUIRED_RISK"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    RESPONSE_NORMALIZATION_FAILED = "RESPONSE_NORMALIZATION_FAILED"
    UNKNOWN = "UNKNOWN"

class ProviderRuntimeReportType(str, Enum):
    PROVIDER_RUNTIME_REPORT = "PROVIDER_RUNTIME_REPORT"
    CACHE_AWARE_FETCH_DRY_RUN_REPORT = "CACHE_AWARE_FETCH_DRY_RUN_REPORT"
    PROVIDER_CONTRACT_TEST_REPORT = "PROVIDER_CONTRACT_TEST_REPORT"
    PROVIDER_ADAPTER_IMPLEMENTATION_REPORT = "PROVIDER_ADAPTER_IMPLEMENTATION_REPORT"
    FULL_PHASE107_REVIEW = "FULL_PHASE107_REVIEW"
"""

with open("usa_signal_bot/core/enums.py", "r") as f:
    content = f.read()

if "ProviderRuntimeStatus" not in content:
    content += "\n" + ENUMS_ADDITION

    content = content.replace(
        'class NotificationType(str, Enum):',
        'class NotificationType(str, Enum):\n    PROVIDER_RUNTIME_REPORT = "PROVIDER_RUNTIME_REPORT"\n    PROVIDER_CONTRACT_TEST_WARNING = "PROVIDER_CONTRACT_TEST_WARNING"\n    PROVIDER_FETCH_DRY_RUN_WARNING = "PROVIDER_FETCH_DRY_RUN_WARNING"'
    )

    content = content.replace(
        'class AlertType(str, Enum):',
        'class AlertType(str, Enum):\n    PROVIDER_RUNTIME_BLOCKED = "PROVIDER_RUNTIME_BLOCKED"\n    PROVIDER_CONTRACT_TEST_BLOCKED = "PROVIDER_CONTRACT_TEST_BLOCKED"\n    PROVIDER_FETCH_DRY_RUN_BLOCKED = "PROVIDER_FETCH_DRY_RUN_BLOCKED"'
    )

    with open("usa_signal_bot/core/enums.py", "w") as f:
        f.write(content)
